[35mDEBUG   [0m tests.conftest:conftest.py:51 Running fixture setup: test_id
[35mDEBUG   [0m tests.conftest:conftest.py:57 Running test: test_publish_with_missing_content_topic with id: 2024-11-07_06-06-02__f92c9d06-6108-4921-beef-62c226d57289
[35mDEBUG   [0m src.steps.common:common.py:18 Running fixture setup: common_setup
[35mDEBUG   [0m src.steps.relay:relay.py:28 Running fixture setup: relay_setup
[35mDEBUG   [0m src.steps.relay:relay.py:34 Running fixture setup: setup_main_relay_nodes
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:19 Docker client initialized with image wakuorg/nwaku:latest
[35mDEBUG   [0m src.node.waku_node:waku_node.py:85 WakuNode instance initialized with log path ./log/docker/node1_2024-11-07_06-06-02__f92c9d06-6108-4921-beef-62c226d57289__wakuorg_nwaku:latest.log
[35mDEBUG   [0m src.node.waku_node:waku_node.py:89 Starting Node...
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:22 Attempting to create or retrieve network waku
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:25 Network waku already exists
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:108 Generated random external IP 172.18.231.20
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:101 Generated ports ['40219', '40220', '40221', '40222', '40223']
[35mDEBUG   [0m src.node.waku_node:waku_node.py:436 RLN credentials were not set
[32mINFO    [0m src.node.waku_node:waku_node.py:165 RLN credentials not set or credential store not available, starting without RLN
[35mDEBUG   [0m src.node.waku_node:waku_node.py:167 Using volumes []
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:49 docker run -i -t -p 40219:40219 -p 40220:40220 -p 40221:40221 -p 40222:40222 -p 40223:40223 wakuorg/nwaku:latest --listen-address=0.0.0.0 --rest=true --rest-admin=true --websocket-support=true --log-level=TRACE --rest-relay-cache-capacity=100 --websocket-port=40221 --rest-port=40219 --tcp-port=40220 --discv5-udp-port=40222 --rest-address=0.0.0.0 --nat=extip:172.18.231.20 --peer-exchange=true --discv5-discovery=true --cluster-id=3 --nodekey=ad690be4af1d8cae81abd2c4fcb472a73b7439f3cce66cbfcd28d779dd95aded --max-connections=1000 --filter-subscription-timeout=600 --shard=0 --metrics-server=true --metrics-server-address=0.0.0.0 --metrics-server-port=40223 --metrics-logging=true --relay=true
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:55 docker network connect --ip 172.18.231.20 waku 17bee5cd92978c53d69a97cc543fa23a241c07664848c2c9d3a7adeff65d6e4b
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:58 Container started with ID 17bee5cd9297. Setting up logs at ./log/docker/node1_2024-11-07_06-06-02__f92c9d06-6108-4921-beef-62c226d57289__wakuorg_nwaku:latest.log
[35mDEBUG   [0m src.node.waku_node:waku_node.py:179 Started container from image wakuorg/nwaku:latest. REST: 40219
[35mDEBUG   [0m src.libs.common:common.py:35 Sleeping for 1 seconds
[31m[1mERROR   [0m src.node.docker_mananger:docker_mananger.py:89 Max retries reached for container 8997ad78df2f. Exiting log stream.
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X GET "http://127.0.0.1:40219/health" -H "Content-Type: application/json" -d 'None'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'{"nodeHealth":"Ready","protocolsHealth":[]}'
[32mINFO    [0m src.node.waku_node:waku_node.py:279 Node protocols are initialized !!
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X GET "http://127.0.0.1:40219/debug/v1/info" -H "Content-Type: application/json" -d 'None'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'{"listenAddresses":["/ip4/172.18.231.20/tcp/40220/p2p/16Uiu2HAmTzHiEshMuAvrNPvQWjMY5WySYXEArGhDtMpwTdQTWenS","/ip4/172.18.231.20/tcp/40221/ws/p2p/16Uiu2HAmTzHiEshMuAvrNPvQWjMY5WySYXEArGhDtMpwTdQTWenS"],"enrUri":"enr:-L24QEHCAZNPIf2r4F5cFluq5WHZ8j3nWAGH-6q4yZqE-c0Bf-n4qMlODHE_Y1jxAkqBpMBW4PEpE27HtRAJcDb15hkCgmlkgnY0gmlwhKwS5xSKbXVsdGlhZGRyc5YACASsEucUBp0cAAoErBLnFAadHd0DgnJzhQADAQAAiXNlY3AyNTZrMaED49D4OviPoJbqdjVqALoNF0XfxLmDQUP4hIkKiHVFggeDdGNwgp0cg3VkcIKdHoV3YWt1MgE"}'
[32mINFO    [0m src.node.waku_node:waku_node.py:284 REST service is ready !!
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:19 Docker client initialized with image wakuorg/nwaku:latest
[35mDEBUG   [0m src.node.waku_node:waku_node.py:85 WakuNode instance initialized with log path ./log/docker/node2_2024-11-07_06-06-02__f92c9d06-6108-4921-beef-62c226d57289__wakuorg_nwaku:latest.log
[35mDEBUG   [0m src.node.waku_node:waku_node.py:89 Starting Node...
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:22 Attempting to create or retrieve network waku
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:25 Network waku already exists
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:108 Generated random external IP 172.18.161.199
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:101 Generated ports ['20878', '20879', '20880', '20881', '20882']
[35mDEBUG   [0m src.node.waku_node:waku_node.py:436 RLN credentials were not set
[32mINFO    [0m src.node.waku_node:waku_node.py:165 RLN credentials not set or credential store not available, starting without RLN
[35mDEBUG   [0m src.node.waku_node:waku_node.py:167 Using volumes []
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:49 docker run -i -t -p 20878:20878 -p 20879:20879 -p 20880:20880 -p 20881:20881 -p 20882:20882 wakuorg/nwaku:latest --listen-address=0.0.0.0 --rest=true --rest-admin=true --websocket-support=true --log-level=TRACE --rest-relay-cache-capacity=100 --websocket-port=20880 --rest-port=20878 --tcp-port=20879 --discv5-udp-port=20881 --rest-address=0.0.0.0 --nat=extip:172.18.161.199 --peer-exchange=true --discv5-discovery=true --cluster-id=3 --nodekey=a6e3bef47bd954cbe8dd7be49c2da3aeddec5b822cced528b299cfbec9cae2b9 --max-connections=1000 --filter-subscription-timeout=600 --shard=0 --metrics-server=true --metrics-server-address=0.0.0.0 --metrics-server-port=20882 --metrics-logging=true --relay=true --discv5-bootstrap-node=enr:-L24QEHCAZNPIf2r4F5cFluq5WHZ8j3nWAGH-6q4yZqE-c0Bf-n4qMlODHE_Y1jxAkqBpMBW4PEpE27HtRAJcDb15hkCgmlkgnY0gmlwhKwS5xSKbXVsdGlhZGRyc5YACASsEucUBp0cAAoErBLnFAadHd0DgnJzhQADAQAAiXNlY3AyNTZrMaED49D4OviPoJbqdjVqALoNF0XfxLmDQUP4hIkKiHVFggeDdGNwgp0cg3VkcIKdHoV3YWt1MgE
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:55 docker network connect --ip 172.18.161.199 waku 3dec8fc3daef6c8f2106787871d39ff66b528bbd44d2e009d060df798bd43066
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:58 Container started with ID 3dec8fc3daef. Setting up logs at ./log/docker/node2_2024-11-07_06-06-02__f92c9d06-6108-4921-beef-62c226d57289__wakuorg_nwaku:latest.log
[35mDEBUG   [0m src.node.waku_node:waku_node.py:179 Started container from image wakuorg/nwaku:latest. REST: 20878
[35mDEBUG   [0m src.libs.common:common.py:35 Sleeping for 1 seconds
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X GET "http://127.0.0.1:20878/health" -H "Content-Type: application/json" -d 'None'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'{"nodeHealth":"Ready","protocolsHealth":[]}'
[32mINFO    [0m src.node.waku_node:waku_node.py:279 Node protocols are initialized !!
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X GET "http://127.0.0.1:20878/debug/v1/info" -H "Content-Type: application/json" -d 'None'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'{"listenAddresses":["/ip4/172.18.161.199/tcp/20879/p2p/16Uiu2HAmNwnVVocpHSXSHvNSzAvLCQF5EiyZBeL3GFFE8KyhEYtu","/ip4/172.18.161.199/tcp/20880/ws/p2p/16Uiu2HAmNwnVVocpHSXSHvNSzAvLCQF5EiyZBeL3GFFE8KyhEYtu"],"enrUri":"enr:-L24QMAFf8NAb5vPhInAqXVU3cCYIWeT-QYaerpAgsuqldSsaHh_FN2mMdqZqfteVn5gze_F8sO9wiutUHpw9knev8QCgmlkgnY0gmlwhKwSoceKbXVsdGlhZGRyc5YACASsEqHHBlGPAAoErBKhxwZRkN0DgnJzhQADAQAAiXNlY3AyNTZrMaEDmOJVpwgxuZDg_JlUidgEFWqDDLnDhTx_-Op-oWI236aDdGNwglGPg3VkcIJRkYV3YWt1MgE"}'
[32mINFO    [0m src.node.waku_node:waku_node.py:284 REST service is ready !!
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X POST "http://127.0.0.1:20878/admin/v1/peers" -H "Content-Type: application/json" -d '["/ip4/172.18.231.20/tcp/40220/p2p/16Uiu2HAmTzHiEshMuAvrNPvQWjMY5WySYXEArGhDtMpwTdQTWenS"]'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'OK'
[35mDEBUG   [0m src.steps.relay:relay.py:59 Running fixture setup: subscribe_main_relay_nodes
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X POST "http://127.0.0.1:40219/relay/v1/subscriptions" -H "Content-Type: application/json" -d '["/waku/2/rs/3/1"]'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'OK'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X POST "http://127.0.0.1:20878/relay/v1/subscriptions" -H "Content-Type: application/json" -d '["/waku/2/rs/3/1"]'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'OK'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X POST "http://127.0.0.1:40219/relay/v1/messages/%2Fwaku%2F2%2Frs%2F3%2F1" -H "Content-Type: application/json" -d '{"payload": "UmVsYXkgd29ya3MhIQ==", "contentTopic": "/test/1/waku-relay/proto", "timestamp": '$(date +%s%N)'}'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'OK'
[35mDEBUG   [0m src.libs.common:common.py:35 Sleeping for 0.1 seconds
[35mDEBUG   [0m src.steps.relay:relay.py:123 Checking that peer NODE_1:wakuorg/nwaku:latest can find the published message
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X GET "http://127.0.0.1:40219/relay/v1/messages/%2Fwaku%2F2%2Frs%2F3%2F1" -H "Content-Type: application/json" -d 'None'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'[{"payload":"UmVsYXkgd29ya3MhIQ==","contentTopic":"/test/1/waku-relay/proto","version":0,"timestamp":1730959565618510592,"ephemeral":false}]'
[35mDEBUG   [0m src.steps.relay:relay.py:123 Checking that peer NODE_2:wakuorg/nwaku:latest can find the published message
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X GET "http://127.0.0.1:20878/relay/v1/messages/%2Fwaku%2F2%2Frs%2F3%2F1" -H "Content-Type: application/json" -d 'None'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'[{"payload":"UmVsYXkgd29ya3MhIQ==","contentTopic":"/test/1/waku-relay/proto","version":0,"timestamp":1730959565618510592,"ephemeral":false}]'
[32mINFO    [0m src.steps.relay:relay.py:71 WARM UP successful!!
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X POST "http://127.0.0.1:40219/relay/v1/messages/%2Fwaku%2F2%2Frs%2F3%2F1" -H "Content-Type: application/json" -d '{"payload": "UmVsYXkgd29ya3MhIQ==", "timestamp": '$(date +%s%N)'}'
[31m[1mERROR   [0m src.node.api_clients.base_client:base_client.py:16 HTTP error occurred: 400 Client Error: Bad Request for url: http://127.0.0.1:40219/relay/v1/messages/%2Fwaku%2F2%2Frs%2F3%2F1. Response content: b'Invalid content body, could not decode. Unable to deserialize data'
[35mDEBUG   [0m tests.conftest:conftest.py:59 Running fixture teardown: test_setup
[35mDEBUG   [0m tests.conftest:conftest.py:83 Running fixture teardown: close_open_nodes
[35mDEBUG   [0m src.node.waku_node:waku_node.py:223 Stopping container with id 17bee5cd9297
[35mDEBUG   [0m src.node.waku_node:waku_node.py:230 Container stopped.
[35mDEBUG   [0m src.node.waku_node:waku_node.py:223 Stopping container with id 3dec8fc3daef
[31m[1mERROR   [0m src.node.docker_mananger:docker_mananger.py:89 Max retries reached for container 17bee5cd9297. Exiting log stream.
[35mDEBUG   [0m src.node.waku_node:waku_node.py:230 Container stopped.
[35mDEBUG   [0m tests.conftest:conftest.py:98 Running fixture teardown: check_waku_log_errors
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:144 No errors found in the waku logs.
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:144 No errors found in the waku logs.