[35mDEBUG   [0m tests.conftest:conftest.py:51 Running fixture setup: test_id
[35mDEBUG   [0m tests.conftest:conftest.py:57 Running test: test_filter_subscribe_with_invalid_request_id with id: 2024-09-27_03-19-48__f2b602da-df2e-4d43-b941-e5aa9017be7a
[35mDEBUG   [0m src.steps.common:common.py:17 Running fixture setup: common_setup
[35mDEBUG   [0m src.steps.filter:filter.py:28 Running fixture setup: filter_setup
[35mDEBUG   [0m src.steps.filter:filter.py:34 Running fixture setup: setup_main_relay_node
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:18 Docker client initialized with image wakuorg/nwaku:latest
[35mDEBUG   [0m src.node.waku_node:waku_node.py:85 WakuNode instance initialized with log path ./log/docker/node1_2024-09-27_03-19-48__f2b602da-df2e-4d43-b941-e5aa9017be7a__wakuorg_nwaku:latest.log
[35mDEBUG   [0m src.node.waku_node:waku_node.py:89 Starting Node...
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:21 Attempting to create or retrieve network waku
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:24 Network waku already exists
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:81 Generated random external IP 172.18.104.162
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:74 Generated ports ['8226', '8227', '8228', '8229', '8230']
[35mDEBUG   [0m src.node.waku_node:waku_node.py:434 RLN credentials were not set
[32mINFO    [0m src.node.waku_node:waku_node.py:163 RLN credentials not set or credential store not available, starting without RLN
[35mDEBUG   [0m src.node.waku_node:waku_node.py:165 Using volumes []
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:48 docker run -i -t -p 8226:8226 -p 8227:8227 -p 8228:8228 -p 8229:8229 -p 8230:8230 wakuorg/nwaku:latest --listen-address=0.0.0.0 --rest=true --rest-admin=true --websocket-support=true --log-level=TRACE --rest-relay-cache-capacity=100 --websocket-port=8228 --rest-port=8226 --tcp-port=8227 --discv5-udp-port=8229 --rest-address=0.0.0.0 --nat=extip:172.18.104.162 --peer-exchange=true --discv5-discovery=true --cluster-id=3 --nodekey=5e8c9c4a2f3fad2fd7fdd72e45298fcdc1a69a207e9bedb86efa5a18aebaa3d3 --shard=0 --metrics-server=true --metrics-server-address=0.0.0.0 --metrics-server-port=8230 --metrics-logging=true --relay=true --filter=true
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:54 docker network connect --ip 172.18.104.162 waku de0667730498f3d9aa379d9f723fe2788566da0aa173d7a311e9c48a98b28ea2
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:57 Container started with ID de0667730498. Setting up logs at ./log/docker/node1_2024-09-27_03-19-48__f2b602da-df2e-4d43-b941-e5aa9017be7a__wakuorg_nwaku:latest.log
[35mDEBUG   [0m src.node.waku_node:waku_node.py:177 Started container from image wakuorg/nwaku:latest. REST: 8226
[35mDEBUG   [0m src.libs.common:common.py:35 Sleeping for 1 seconds
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X GET "http://127.0.0.1:8226/health" -H "Content-Type: application/json" -d 'None'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'{"nodeHealth":"Ready","protocolsHealth":[]}'
[32mINFO    [0m src.node.waku_node:waku_node.py:277 Node protocols are initialized !!
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X GET "http://127.0.0.1:8226/debug/v1/info" -H "Content-Type: application/json" -d 'None'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'{"listenAddresses":["/ip4/172.18.104.162/tcp/8227/p2p/16Uiu2HAmMmsWKEuuUezCdv62JtKMCUtcU3FzZj2cPjyp8Kvaycpx","/ip4/172.18.104.162/tcp/8228/ws/p2p/16Uiu2HAmMmsWKEuuUezCdv62JtKMCUtcU3FzZj2cPjyp8Kvaycpx"],"enrUri":"enr:-LO4QKaoymKljw4uoaz4-N0WrRPcDJIHyPF5wydCV-iyEiC-fwhATRNwZVlPCW6YemRhuuXjv_13hS4CxGQNm0NwH74BgmlkgnY0gmlwhKwSaKKKbXVsdGlhZGRyc4wACgSsEmiiBiAk3QOCcnOFAAMBAACJc2VjcDI1NmsxoQOHfIJPdyeEKEpozTQl2NksNQf8V0VPV-U7Fh0Y_3U5uYN0Y3CCICODdWRwgiAlhXdha3UyBQ"}'
[32mINFO    [0m src.node.waku_node:waku_node.py:282 REST service is ready !!
[35mDEBUG   [0m src.steps.filter:filter.py:39 Running fixture setup: setup_main_filter_node
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:18 Docker client initialized with image wakuorg/go-waku:latest
[35mDEBUG   [0m src.node.waku_node:waku_node.py:85 WakuNode instance initialized with log path ./log/docker/node2_2024-09-27_03-19-48__f2b602da-df2e-4d43-b941-e5aa9017be7a__wakuorg_go-waku:latest.log
[35mDEBUG   [0m src.node.waku_node:waku_node.py:89 Starting Node...
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:21 Attempting to create or retrieve network waku
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:24 Network waku already exists
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:81 Generated random external IP 172.18.182.56
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:74 Generated ports ['48706', '48707', '48708', '48709', '48710']
[35mDEBUG   [0m src.node.waku_node:waku_node.py:434 RLN credentials were not set
[32mINFO    [0m src.node.waku_node:waku_node.py:163 RLN credentials not set or credential store not available, starting without RLN
[35mDEBUG   [0m src.node.waku_node:waku_node.py:165 Using volumes []
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:48 docker run -i -t -p 48706:48706 -p 48707:48707 -p 48708:48708 -p 48709:48709 -p 48710:48710 wakuorg/go-waku:latest --listen-address=0.0.0.0 --rest=true --rest-admin=true --websocket-support=true --log-level=DEBUG --rest-relay-cache-capacity=100 --websocket-port=48708 --rest-port=48706 --tcp-port=48707 --discv5-udp-port=48709 --rest-address=0.0.0.0 --nat=extip:172.18.182.56 --peer-exchange=true --discv5-discovery=true --cluster-id=3 --nodekey=0ada7397f26b14bb4b8bfbdfeb6fdfe3fb8d0bdeec254fbeeff6e8b7f04bbabc --min-relay-peers-to-publish=1 --rest-filter-cache-capacity=50 --peer-store-capacity=10 --relay=false --discv5-bootstrap-node=enr:-LO4QKaoymKljw4uoaz4-N0WrRPcDJIHyPF5wydCV-iyEiC-fwhATRNwZVlPCW6YemRhuuXjv_13hS4CxGQNm0NwH74BgmlkgnY0gmlwhKwSaKKKbXVsdGlhZGRyc4wACgSsEmiiBiAk3QOCcnOFAAMBAACJc2VjcDI1NmsxoQOHfIJPdyeEKEpozTQl2NksNQf8V0VPV-U7Fh0Y_3U5uYN0Y3CCICODdWRwgiAlhXdha3UyBQ --filternode=/ip4/172.18.104.162/tcp/8227/p2p/16Uiu2HAmMmsWKEuuUezCdv62JtKMCUtcU3FzZj2cPjyp8Kvaycpx
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:54 docker network connect --ip 172.18.182.56 waku c5d1d599ede3ce109cb7b9070af421f1acef1d3b81622acef1ec2737772cb464
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:57 Container started with ID c5d1d599ede3. Setting up logs at ./log/docker/node2_2024-09-27_03-19-48__f2b602da-df2e-4d43-b941-e5aa9017be7a__wakuorg_go-waku:latest.log
[35mDEBUG   [0m src.node.waku_node:waku_node.py:177 Started container from image wakuorg/go-waku:latest. REST: 48706
[35mDEBUG   [0m src.libs.common:common.py:35 Sleeping for 1 seconds
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X GET "http://127.0.0.1:48706/debug/v1/info" -H "Content-Type: application/json" -d 'None'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'{"enrUri":"enr:-Ji4QGp77OQG1GsWh_1jflyyliMAC2od_DCTl68SRgXDGpx8Z-fggT1xYntpOah9nmtPVmnXXQ2dE7FDdN5Ew44hvpKGAZIxffSDgmlkgnY0gmlwhKwRAAmJc2VjcDI1NmsxoQPDbCE0qlGt6C2fkTGGdi9_f30OEoHBw9vB9HSVXteVlYN0Y3CCvkODdWRwgr5FhXdha3UygA","listenAddresses":["/ip4/127.0.0.1/tcp/48707/p2p/16Uiu2HAmRoqUvDthQ1BkU64AHEaFyAzUqUEj8UUtfUNJBCKfXRYY","/ip4/127.0.0.1/tcp/48708/ws/p2p/16Uiu2HAmRoqUvDthQ1BkU64AHEaFyAzUqUEj8UUtfUNJBCKfXRYY","/ip4/172.17.0.9/tcp/48707/p2p/16Uiu2HAmRoqUvDthQ1BkU64AHEaFyAzUqUEj8UUtfUNJBCKfXRYY","/ip4/172.17.0.9/tcp/48708/ws/p2p/16Uiu2HAmRoqUvDthQ1BkU64AHEaFyAzUqUEj8UUtfUNJBCKfXRYY"]}'
[32mINFO    [0m src.node.waku_node:waku_node.py:282 REST service is ready !!
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X POST "http://127.0.0.1:48706/admin/v1/peers" -H "Content-Type: application/json" -d '{"multiaddr": "/ip4/172.18.104.162/tcp/8227/p2p/16Uiu2HAmMmsWKEuuUezCdv62JtKMCUtcU3FzZj2cPjyp8Kvaycpx", "protocols": ["/vac/waku/relay/2.0.0"], "shards": [0, 1, 2, 3, 4, 5, 6, 7, 8]}'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'null'
[35mDEBUG   [0m src.steps.filter:filter.py:47 Running fixture setup: subscribe_main_nodes
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X POST "http://127.0.0.1:8226/relay/v1/subscriptions" -H "Content-Type: application/json" -d '["/waku/2/rs/3/1"]'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'OK'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X POST "http://127.0.0.1:48706/filter/v2/subscriptions" -H "Content-Type: application/json" -d '{"requestId": "f74a9129-fe52-4206-a1c5-fa0af30b5ee7", "contentFilters": ["/test/1/waku-filter/proto"], "pubsubTopic": "/waku/2/rs/3/1"}'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'{"requestId":"f74a9129-fe52-4206-a1c5-fa0af30b5ee7","statusDesc":"OK"}'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X POST "http://127.0.0.1:48706/filter/v2/subscriptions" -H "Content-Type: application/json" -d '{"requestId": 1, "contentFilters": ["/test/1/waku-filter/proto"], "pubsubTopic": "/waku/2/rs/3/1"}'
[31m[1mERROR   [0m src.node.api_clients.base_client:base_client.py:16 HTTP error occurred: 400 Client Error: Bad Request for url: http://127.0.0.1:48706/filter/v2/subscriptions. Response content: b''
[35mDEBUG   [0m tests.conftest:conftest.py:59 Running fixture teardown: test_setup
[35mDEBUG   [0m tests.conftest:conftest.py:83 Running fixture teardown: close_open_nodes
[35mDEBUG   [0m src.node.waku_node:waku_node.py:221 Stopping container with id de0667730498
[35mDEBUG   [0m src.node.waku_node:waku_node.py:228 Container stopped.
[35mDEBUG   [0m src.node.waku_node:waku_node.py:221 Stopping container with id c5d1d599ede3
[35mDEBUG   [0m src.node.waku_node:waku_node.py:228 Container stopped.
[35mDEBUG   [0m tests.conftest:conftest.py:98 Running fixture teardown: check_waku_log_errors
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:117 No errors found in the waku logs.
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:117 No errors found in the waku logs.