[35mDEBUG   [0m tests.conftest:conftest.py:51 Running fixture setup: test_id
[35mDEBUG   [0m tests.conftest:conftest.py:57 Running test: test_passing_cursor_of_non_existing_message_from_the_store with id: 2024-12-20_04-18-27__fb607678-de39-4248-9e1e-2e5ebc918f8d
[35mDEBUG   [0m src.steps.common:common.py:18 Running fixture setup: common_setup
[35mDEBUG   [0m src.steps.store:store.py:31 Running fixture setup: store_setup
[35mDEBUG   [0m src.steps.store:store.py:39 Running fixture setup: node_setup
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:19 Docker client initialized with image wakuorg/nwaku:latest
[35mDEBUG   [0m src.node.waku_node:waku_node.py:85 WakuNode instance initialized with log path ./log/docker/publishing_node1_2024-12-20_04-18-27__fb607678-de39-4248-9e1e-2e5ebc918f8d__wakuorg_nwaku:latest.log
[35mDEBUG   [0m src.node.waku_node:waku_node.py:89 Starting Node...
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:22 Attempting to create or retrieve network waku
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:25 Network waku already exists
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:108 Generated random external IP 172.18.7.219
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:101 Generated ports ['8635', '8636', '8637', '8638', '8639']
[35mDEBUG   [0m src.node.waku_node:waku_node.py:439 RLN credentials were not set
[32mINFO    [0m src.node.waku_node:waku_node.py:168 RLN credentials not set or credential store not available, starting without RLN
[35mDEBUG   [0m src.node.waku_node:waku_node.py:170 Using volumes []
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:49 docker run -i -t -p 8635:8635 -p 8636:8636 -p 8637:8637 -p 8638:8638 -p 8639:8639 wakuorg/nwaku:latest --listen-address=0.0.0.0 --rest=true --rest-admin=true --websocket-support=true --log-level=TRACE --rest-relay-cache-capacity=100 --websocket-port=8637 --rest-port=8635 --tcp-port=8636 --discv5-udp-port=8638 --rest-address=0.0.0.0 --nat=extip:172.18.7.219 --peer-exchange=true --discv5-discovery=true --cluster-id=3 --nodekey=ea0cda0f371b13640f4afd0aa7356c3b5391d1d1a1f39d1c2c904c7a0ae784ba --shard=0 --metrics-server=true --metrics-server-address=0.0.0.0 --metrics-server-port=8639 --metrics-logging=true --store=true --relay=true
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:55 docker network connect --ip 172.18.7.219 waku ffab54edf6f3116d981d10b9be94ec38bc6066b9478867bfa7f6e33f2fe575c7
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:58 Container started with ID ffab54edf6f3. Setting up logs at ./log/docker/publishing_node1_2024-12-20_04-18-27__fb607678-de39-4248-9e1e-2e5ebc918f8d__wakuorg_nwaku:latest.log
[35mDEBUG   [0m src.node.waku_node:waku_node.py:182 Started container from image wakuorg/nwaku:latest. REST: 8635
[35mDEBUG   [0m src.libs.common:common.py:35 Sleeping for 1 seconds
[1m[31mERROR   [0m src.node.docker_mananger:docker_mananger.py:89 Max retries reached for container ad7eeacea8d2. Exiting log stream.
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X GET "http://127.0.0.1:8635/health" -H "Content-Type: application/json" -d 'None'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'{"nodeHealth":"Ready","protocolsHealth":[]}'
[32mINFO    [0m src.node.waku_node:waku_node.py:282 Node protocols are initialized !!
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X GET "http://127.0.0.1:8635/debug/v1/info" -H "Content-Type: application/json" -d 'None'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'{"listenAddresses":["/ip4/172.18.7.219/tcp/8636/p2p/16Uiu2HAmNuPVc95rMhAvyaYvgeKPgXNb6yuhbsgRBe8izrt9ozKR","/ip4/172.18.7.219/tcp/8637/ws/p2p/16Uiu2HAmNuPVc95rMhAvyaYvgeKPgXNb6yuhbsgRBe8izrt9ozKR"],"enrUri":"enr:-L24QA_Cf7RxMsNDWL4C9hfRbhCo46ORqXjqhJhj8ZgiHPWzU8pnB6pz_duXdxm8NSkr_HFk-5c2kdnMgDp8SNfrNSUCgmlkgnY0gmlwhKwSB9uKbXVsdGlhZGRyc5YACASsEgfbBiG8AAoErBIH2wYhvd0DgnJzhQADAQAAiXNlY3AyNTZrMaEDmEUrPZUHd1jVZW7vSf75mA4_tsYcoMul-8OfFGi0B4CDdGNwgiG8g3VkcIIhvoV3YWt1MgM"}'
[32mINFO    [0m src.node.waku_node:waku_node.py:287 REST service is ready !!
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:19 Docker client initialized with image wakuorg/nwaku:latest
[35mDEBUG   [0m src.node.waku_node:waku_node.py:85 WakuNode instance initialized with log path ./log/docker/store_node1_2024-12-20_04-18-27__fb607678-de39-4248-9e1e-2e5ebc918f8d__wakuorg_nwaku:latest.log
[35mDEBUG   [0m src.node.waku_node:waku_node.py:89 Starting Node...
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:22 Attempting to create or retrieve network waku
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:25 Network waku already exists
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:108 Generated random external IP 172.18.111.44
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:101 Generated ports ['10562', '10563', '10564', '10565', '10566']
[35mDEBUG   [0m src.node.waku_node:waku_node.py:439 RLN credentials were not set
[32mINFO    [0m src.node.waku_node:waku_node.py:168 RLN credentials not set or credential store not available, starting without RLN
[35mDEBUG   [0m src.node.waku_node:waku_node.py:170 Using volumes []
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:49 docker run -i -t -p 10562:10562 -p 10563:10563 -p 10564:10564 -p 10565:10565 -p 10566:10566 wakuorg/nwaku:latest --listen-address=0.0.0.0 --rest=true --rest-admin=true --websocket-support=true --log-level=TRACE --rest-relay-cache-capacity=100 --websocket-port=10564 --rest-port=10562 --tcp-port=10563 --discv5-udp-port=10565 --rest-address=0.0.0.0 --nat=extip:172.18.111.44 --peer-exchange=true --discv5-discovery=true --cluster-id=3 --nodekey=0cdfe5a586ebfbb6ba74cee944cb81d737e1d3efe9d4e23bcacb8f4c86eefcba --shard=0 --metrics-server=true --metrics-server-address=0.0.0.0 --metrics-server-port=10566 --metrics-logging=true --discv5-bootstrap-node=enr:-L24QA_Cf7RxMsNDWL4C9hfRbhCo46ORqXjqhJhj8ZgiHPWzU8pnB6pz_duXdxm8NSkr_HFk-5c2kdnMgDp8SNfrNSUCgmlkgnY0gmlwhKwSB9uKbXVsdGlhZGRyc5YACASsEgfbBiG8AAoErBIH2wYhvd0DgnJzhQADAQAAiXNlY3AyNTZrMaEDmEUrPZUHd1jVZW7vSf75mA4_tsYcoMul-8OfFGi0B4CDdGNwgiG8g3VkcIIhvoV3YWt1MgM --storenode=/ip4/172.18.7.219/tcp/8636/p2p/16Uiu2HAmNuPVc95rMhAvyaYvgeKPgXNb6yuhbsgRBe8izrt9ozKR --store=true --relay=true
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:55 docker network connect --ip 172.18.111.44 waku 7b2855f51fd8bf1adaeddf042a36939c74b8ca1eab4b3592548b3ed49ff04fda
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:58 Container started with ID 7b2855f51fd8. Setting up logs at ./log/docker/store_node1_2024-12-20_04-18-27__fb607678-de39-4248-9e1e-2e5ebc918f8d__wakuorg_nwaku:latest.log
[35mDEBUG   [0m src.node.waku_node:waku_node.py:182 Started container from image wakuorg/nwaku:latest. REST: 10562
[35mDEBUG   [0m src.libs.common:common.py:35 Sleeping for 1 seconds
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X GET "http://127.0.0.1:10562/health" -H "Content-Type: application/json" -d 'None'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'{"nodeHealth":"Ready","protocolsHealth":[]}'
[32mINFO    [0m src.node.waku_node:waku_node.py:282 Node protocols are initialized !!
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X GET "http://127.0.0.1:10562/debug/v1/info" -H "Content-Type: application/json" -d 'None'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'{"listenAddresses":["/ip4/172.18.111.44/tcp/10563/p2p/16Uiu2HAm1B35LRPfdxMUwHw8WinZq9vtdfbCK6wdGSvXL1iqRZj9","/ip4/172.18.111.44/tcp/10564/ws/p2p/16Uiu2HAm1B35LRPfdxMUwHw8WinZq9vtdfbCK6wdGSvXL1iqRZj9"],"enrUri":"enr:-L24QN6rp6E0gXfwNrxm_ttm82ok3WtFpATVswSWV5FW22fcajicmCXfjtBkpLM8ZM3-kleDtIQS_SpQYVeIsOkiCbMCgmlkgnY0gmlwhKwSbyyKbXVsdGlhZGRyc5YACASsEm8sBilDAAoErBJvLAYpRN0DgnJzhQADAQAAiXNlY3AyNTZrMaECVWZDIjo_YxYaDkX22JzGrRwqcfh_ypMPelBEISP9juyDdGNwgilDg3VkcIIpRYV3YWt1MgM"}'
[32mINFO    [0m src.node.waku_node:waku_node.py:287 REST service is ready !!
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X POST "http://127.0.0.1:10562/admin/v1/peers" -H "Content-Type: application/json" -d '["/ip4/172.18.7.219/tcp/8636/p2p/16Uiu2HAmNuPVc95rMhAvyaYvgeKPgXNb6yuhbsgRBe8izrt9ozKR"]'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'OK'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X POST "http://127.0.0.1:8635/relay/v1/subscriptions" -H "Content-Type: application/json" -d '["/waku/2/rs/3/0"]'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'OK'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X POST "http://127.0.0.1:10562/relay/v1/subscriptions" -H "Content-Type: application/json" -d '["/waku/2/rs/3/0"]'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'OK'
[35mDEBUG   [0m src.steps.store:store.py:132 Relaying message
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X POST "http://127.0.0.1:8635/relay/v1/messages/%2Fwaku%2F2%2Frs%2F3%2F0" -H "Content-Type: application/json" -d '{"payload": "TWVzc2FnZV8w", "contentTopic": "/myapp/1/latest/proto", "timestamp": '$(date +%s%N)'}'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'OK'
[35mDEBUG   [0m src.libs.common:common.py:35 Sleeping for 0.2 seconds
[35mDEBUG   [0m src.steps.store:store.py:132 Relaying message
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X POST "http://127.0.0.1:8635/relay/v1/messages/%2Fwaku%2F2%2Frs%2F3%2F0" -H "Content-Type: application/json" -d '{"payload": "TWVzc2FnZV8x", "contentTopic": "/myapp/1/latest/proto", "timestamp": '$(date +%s%N)'}'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'OK'
[35mDEBUG   [0m src.libs.common:common.py:35 Sleeping for 0.2 seconds
[35mDEBUG   [0m src.steps.store:store.py:132 Relaying message
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X POST "http://127.0.0.1:8635/relay/v1/messages/%2Fwaku%2F2%2Frs%2F3%2F0" -H "Content-Type: application/json" -d '{"payload": "TWVzc2FnZV8y", "contentTopic": "/myapp/1/latest/proto", "timestamp": '$(date +%s%N)'}'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'OK'
[35mDEBUG   [0m src.libs.common:common.py:35 Sleeping for 0.2 seconds
[35mDEBUG   [0m src.steps.store:store.py:132 Relaying message
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X POST "http://127.0.0.1:8635/relay/v1/messages/%2Fwaku%2F2%2Frs%2F3%2F0" -H "Content-Type: application/json" -d '{"payload": "TWVzc2FnZV8z", "contentTopic": "/myapp/1/latest/proto", "timestamp": '$(date +%s%N)'}'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'OK'
[35mDEBUG   [0m src.libs.common:common.py:35 Sleeping for 0.2 seconds
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X GET "http://127.0.0.1:8635/store/v3/messages?pubsubTopic=%2Fwaku%2F2%2Frs%2F3%2F0&cursor=xumiXhEdDcCM6jZjC6lnKFzp75zzs%2BlAlsQvM%2FYgf7s%3D&pageSize=100&ascending=true" -H "Content-Type: application/json" -d 'None'
[1m[31mERROR   [0m src.node.api_clients.base_client:base_client.py:16 HTTP error occurred: 500 Server Error: Internal Server Error for url: http://127.0.0.1:8635/store/v3/messages?pubsubTopic=%2Fwaku%2F2%2Frs%2F3%2F0&cursor=xumiXhEdDcCM6jZjC6lnKFzp75zzs%2BlAlsQvM%2FYgf7s%3D&pageSize=100&ascending=true. Response content: b'error in handleSelfStoreRequest: BAD_RESPONSE: archive error: DIRVER_ERROR: cursor not found'
[35mDEBUG   [0m tests.conftest:conftest.py:59 Running fixture teardown: test_setup
[35mDEBUG   [0m tests.conftest:conftest.py:83 Running fixture teardown: close_open_nodes
[35mDEBUG   [0m src.node.waku_node:waku_node.py:226 Stopping container with id ffab54edf6f3
[35mDEBUG   [0m src.node.waku_node:waku_node.py:233 Container stopped.
[35mDEBUG   [0m src.node.waku_node:waku_node.py:226 Stopping container with id 7b2855f51fd8
[1m[31mERROR   [0m src.node.docker_mananger:docker_mananger.py:89 Max retries reached for container ffab54edf6f3. Exiting log stream.
[35mDEBUG   [0m src.node.waku_node:waku_node.py:233 Container stopped.
[35mDEBUG   [0m tests.conftest:conftest.py:98 Running fixture teardown: check_waku_log_errors
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:144 No errors found in the waku logs.
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:144 No errors found in the waku logs.