[35mDEBUG   [0m tests.conftest:conftest.py:51 Running fixture setup: test_id
[35mDEBUG   [0m tests.conftest:conftest.py:57 Running test: test_cant_retrieve_messages_on_not_subscribed_content_topic with id: 2024-08-06_04-20-58__8801ae98-ea41-41ad-bfbf-e0ed951308e4
[35mDEBUG   [0m src.steps.common:common.py:17 Running fixture setup: common_setup
[35mDEBUG   [0m src.steps.relay:relay.py:29 Running fixture setup: relay_setup
[35mDEBUG   [0m src.steps.sharding:sharding.py:31 Running fixture setup: sharding_setup
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:17 Docker client initialized with image wakuorg/nwaku:latest
[35mDEBUG   [0m src.node.waku_node:waku_node.py:81 WakuNode instance initialized with log path ./log/docker/node1_2024-08-06_04-20-58__8801ae98-ea41-41ad-bfbf-e0ed951308e4__wakuorg_nwaku:latest.log
[35mDEBUG   [0m src.node.waku_node:waku_node.py:85 Starting Node...
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:20 Attempting to create or retrieve network waku
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:23 Network waku already exists
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:80 Generated random external IP 172.18.4.30
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:73 Generated ports ['28985', '28986', '28987', '28988', '28989']
[35mDEBUG   [0m src.node.waku_node:waku_node.py:428 RLN credentials were not set
[32mINFO    [0m src.node.waku_node:waku_node.py:157 RLN credentials not set or credential store not available, starting without RLN
[35mDEBUG   [0m src.node.waku_node:waku_node.py:159 Using volumes []
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:47 docker run -i -t -p 28985:28985 -p 28986:28986 -p 28987:28987 -p 28988:28988 -p 28989:28989 wakuorg/nwaku:latest --listen-address=0.0.0.0 --rest=true --rest-admin=true --websocket-support=true --log-level=TRACE --rest-relay-cache-capacity=100 --websocket-port=28987 --rest-port=28985 --tcp-port=28986 --discv5-udp-port=28988 --rest-address=0.0.0.0 --nat=extip:172.18.4.30 --peer-exchange=true --discv5-discovery=true --cluster-id=2 --shard=0 --metrics-server=true --metrics-server-address=0.0.0.0 --metrics-server-port=28989 --metrics-logging=true --relay=true --nodekey=30348dd51465150e04a5d9d932c72864c8967f806cce60b5d26afeca1e77eb68 --filter=true --content-topic=/myapp/1/latest/proto
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:53 docker network connect --ip 172.18.4.30 waku 59f72c7718c56db988efe8e3a0f5eb85048af88b970df2dd6cd32241d349acef
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:56 Container started with ID 59f72c7718c5. Setting up logs at ./log/docker/node1_2024-08-06_04-20-58__8801ae98-ea41-41ad-bfbf-e0ed951308e4__wakuorg_nwaku:latest.log
[35mDEBUG   [0m src.node.waku_node:waku_node.py:171 Started container from image wakuorg/nwaku:latest. REST: 28985
[35mDEBUG   [0m src.libs.common:common.py:35 Sleeping for 1 seconds
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X GET "http://127.0.0.1:28985/health" -H "Content-Type: application/json" -d 'None'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'{"nodeHealth":"Ready","protocolsHealth":[]}'
[32mINFO    [0m src.node.waku_node:waku_node.py:274 Node protocols are initialized !!
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X GET "http://127.0.0.1:28985/debug/v1/info" -H "Content-Type: application/json" -d 'None'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'{"listenAddresses":["/ip4/172.18.4.30/tcp/28986/p2p/16Uiu2HAmGNtM2rQ8abySFNhqPDFY4cmfAEpfo9Z9fD3NekoFR2ip","/ip4/172.18.4.30/tcp/28987/ws/p2p/16Uiu2HAmGNtM2rQ8abySFNhqPDFY4cmfAEpfo9Z9fD3NekoFR2ip"],"enrUri":"enr:-LO4QO_nkFh5v0giRyFF_AuJdrtmEwUgARuLRBa-9xaNwbkcOgfeTnKaJ6_equqftQfs2jrX_evX8NTGncWTIe0krEcBgmlkgnY0gmlwhKwSBB6KbXVsdGlhZGRyc4wACgSsEgQeBnE73QOCcnOFAAIBAACJc2VjcDI1NmsxoQM3Tqpf5eFn4Jztm4gB0Y0JVSJyxyZsW8QR-QU5DZb-PYN0Y3CCcTqDdWRwgnE8hXdha3UyBQ"}'
[32mINFO    [0m src.node.waku_node:waku_node.py:279 REST service is ready !!
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:17 Docker client initialized with image wakuorg/nwaku:latest
[35mDEBUG   [0m src.node.waku_node:waku_node.py:81 WakuNode instance initialized with log path ./log/docker/node2_2024-08-06_04-20-58__8801ae98-ea41-41ad-bfbf-e0ed951308e4__wakuorg_nwaku:latest.log
[35mDEBUG   [0m src.node.waku_node:waku_node.py:85 Starting Node...
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:20 Attempting to create or retrieve network waku
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:23 Network waku already exists
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:80 Generated random external IP 172.18.113.100
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:73 Generated ports ['57597', '57598', '57599', '57600', '57601']
[35mDEBUG   [0m src.node.waku_node:waku_node.py:428 RLN credentials were not set
[32mINFO    [0m src.node.waku_node:waku_node.py:157 RLN credentials not set or credential store not available, starting without RLN
[35mDEBUG   [0m src.node.waku_node:waku_node.py:159 Using volumes []
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:47 docker run -i -t -p 57597:57597 -p 57598:57598 -p 57599:57599 -p 57600:57600 -p 57601:57601 wakuorg/nwaku:latest --listen-address=0.0.0.0 --rest=true --rest-admin=true --websocket-support=true --log-level=TRACE --rest-relay-cache-capacity=100 --websocket-port=57599 --rest-port=57597 --tcp-port=57598 --discv5-udp-port=57600 --rest-address=0.0.0.0 --nat=extip:172.18.113.100 --peer-exchange=true --discv5-discovery=true --cluster-id=2 --shard=0 --metrics-server=true --metrics-server-address=0.0.0.0 --metrics-server-port=57601 --metrics-logging=true --relay=true --discv5-bootstrap-node=enr:-LO4QO_nkFh5v0giRyFF_AuJdrtmEwUgARuLRBa-9xaNwbkcOgfeTnKaJ6_equqftQfs2jrX_evX8NTGncWTIe0krEcBgmlkgnY0gmlwhKwSBB6KbXVsdGlhZGRyc4wACgSsEgQeBnE73QOCcnOFAAIBAACJc2VjcDI1NmsxoQM3Tqpf5eFn4Jztm4gB0Y0JVSJyxyZsW8QR-QU5DZb-PYN0Y3CCcTqDdWRwgnE8hXdha3UyBQ --content-topic=/myapp/1/latest/proto
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:53 docker network connect --ip 172.18.113.100 waku 7b02099fa07b585d34d444cdf00e85613310ef995ca26b2e5bba85e150e9ba41
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:56 Container started with ID 7b02099fa07b. Setting up logs at ./log/docker/node2_2024-08-06_04-20-58__8801ae98-ea41-41ad-bfbf-e0ed951308e4__wakuorg_nwaku:latest.log
[35mDEBUG   [0m src.node.waku_node:waku_node.py:171 Started container from image wakuorg/nwaku:latest. REST: 57597
[35mDEBUG   [0m src.libs.common:common.py:35 Sleeping for 1 seconds
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X GET "http://127.0.0.1:57597/health" -H "Content-Type: application/json" -d 'None'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'{"nodeHealth":"Ready","protocolsHealth":[]}'
[32mINFO    [0m src.node.waku_node:waku_node.py:274 Node protocols are initialized !!
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X GET "http://127.0.0.1:57597/debug/v1/info" -H "Content-Type: application/json" -d 'None'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'{"listenAddresses":["/ip4/172.18.113.100/tcp/57598/p2p/16Uiu2HAmN8wcsprH2qMUjnzrBmfjQNhjHgJvuihYmq1eAoZBqHm4","/ip4/172.18.113.100/tcp/57599/ws/p2p/16Uiu2HAmN8wcsprH2qMUjnzrBmfjQNhjHgJvuihYmq1eAoZBqHm4"],"enrUri":"enr:-LO4QHq9eg_Ge998YZbxDxSwZDAGsEXNSlprnHiVfJ-Xvx47Te48zQoDBDK0ahN_aoYWSatQ2GfKRg0Mb3-udTNnYRMBgmlkgnY0gmlwhKwScWSKbXVsdGlhZGRyc4wACgSsEnFkBuD_3QOCcnOFAAIBAACJc2VjcDI1NmsxoQOM4ltUFuf3YY2FCiUNf8HoD9dVK9zfZmyjhdPaM4ItW4N0Y3CC4P6DdWRwguEAhXdha3UyAQ"}'
[32mINFO    [0m src.node.waku_node:waku_node.py:279 REST service is ready !!
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X POST "http://127.0.0.1:57597/admin/v1/peers" -H "Content-Type: application/json" -d '["/ip4/172.18.4.30/tcp/28986/p2p/16Uiu2HAmGNtM2rQ8abySFNhqPDFY4cmfAEpfo9Z9fD3NekoFR2ip"]'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'OK'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X POST "http://127.0.0.1:28985/relay/v1/auto/subscriptions" -H "Content-Type: application/json" -d '["/myapp/1/latest/proto"]'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'OK'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X POST "http://127.0.0.1:57597/relay/v1/auto/subscriptions" -H "Content-Type: application/json" -d '["/myapp/1/latest/proto"]'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'OK'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X POST "http://127.0.0.1:28985/relay/v1/auto/messages" -H "Content-Type: application/json" -d '{"payload": "U2hhcmRpbmcgd29ya3MhIQ==", "contentTopic": "/toychat/2/huilong/proto", "timestamp": '$(date +%s%N)'}'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'OK'
[35mDEBUG   [0m src.libs.common:common.py:35 Sleeping for 0.1 seconds
[35mDEBUG   [0m src.steps.sharding:sharding.py:159 Checking that peer NODE_1:wakuorg/nwaku:latest can find the published message
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X GET "http://127.0.0.1:28985/relay/v1/auto/messages/%2Ftoychat%2F2%2Fhuilong%2Fproto" -H "Content-Type: application/json" -d 'None'
[1m[31mERROR   [0m src.node.api_clients.base_client:base_client.py:16 HTTP error occurred: 404 Client Error: Not Found for url: http://127.0.0.1:28985/relay/v1/auto/messages/%2Ftoychat%2F2%2Fhuilong%2Fproto. Response content: b'/toychat/2/huilong/proto'
[35mDEBUG   [0m tests.conftest:conftest.py:59 Running fixture teardown: test_setup
[35mDEBUG   [0m tests.conftest:conftest.py:83 Running fixture teardown: close_open_nodes
[35mDEBUG   [0m src.node.waku_node:waku_node.py:218 Stopping container with id 59f72c7718c5
[35mDEBUG   [0m src.node.waku_node:waku_node.py:225 Container stopped.
[35mDEBUG   [0m src.node.waku_node:waku_node.py:218 Stopping container with id 7b02099fa07b
[35mDEBUG   [0m src.node.waku_node:waku_node.py:225 Container stopped.