[35mDEBUG   [0m tests.conftest:conftest.py:51 Running fixture setup: test_id
[35mDEBUG   [0m tests.conftest:conftest.py:57 Running test: test_main_node_only_lightpush__peer_only_filter with id: 2024-11-27_13-44-37__182dc666-7560-48c5-8676-3e73cc46dca9
[35mDEBUG   [0m src.steps.common:common.py:18 Running fixture setup: common_setup
[35mDEBUG   [0m src.steps.light_push:light_push.py:28 Running fixture setup: light_push_setup
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:19 Docker client initialized with image wakuorg/nwaku:latest
[35mDEBUG   [0m src.node.waku_node:waku_node.py:85 WakuNode instance initialized with log path ./log/docker/receiving_node1_2024-11-27_13-44-37__182dc666-7560-48c5-8676-3e73cc46dca9__wakuorg_nwaku:latest.log
[35mDEBUG   [0m src.node.waku_node:waku_node.py:89 Starting Node...
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:22 Attempting to create or retrieve network waku
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:25 Network waku already exists
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:108 Generated random external IP 172.18.97.217
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:101 Generated ports ['50557', '50558', '50559', '50560', '50561']
[35mDEBUG   [0m src.node.waku_node:waku_node.py:439 RLN credentials were not set
[32mINFO    [0m src.node.waku_node:waku_node.py:168 RLN credentials not set or credential store not available, starting without RLN
[35mDEBUG   [0m src.node.waku_node:waku_node.py:170 Using volumes []
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:49 docker run -i -t -p 50557:50557 -p 50558:50558 -p 50559:50559 -p 50560:50560 -p 50561:50561 wakuorg/nwaku:latest --listen-address=0.0.0.0 --rest=true --rest-admin=true --websocket-support=true --log-level=TRACE --rest-relay-cache-capacity=100 --websocket-port=50559 --rest-port=50557 --tcp-port=50558 --discv5-udp-port=50560 --rest-address=0.0.0.0 --nat=extip:172.18.97.217 --peer-exchange=true --discv5-discovery=true --cluster-id=3 --nodekey=15f0e5cb23cba0c1a00e0bb17dabcbbe5e1b8975b2febde88eba6fc2a9e1fa74 --shard=0 --metrics-server=true --metrics-server-address=0.0.0.0 --metrics-server-port=50561 --metrics-logging=true --lightpush=false --relay=false --filter=true
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:55 docker network connect --ip 172.18.97.217 waku 5c6a4a2c91cd59fdf345c905246396806ad11b2775458b68268614bd6e1acc00
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:58 Container started with ID 5c6a4a2c91cd. Setting up logs at ./log/docker/receiving_node1_2024-11-27_13-44-37__182dc666-7560-48c5-8676-3e73cc46dca9__wakuorg_nwaku:latest.log
[35mDEBUG   [0m src.node.waku_node:waku_node.py:182 Started container from image wakuorg/nwaku:latest. REST: 50557
[35mDEBUG   [0m src.libs.common:common.py:35 Sleeping for 1 seconds
[31m[1mERROR   [0m src.node.docker_mananger:docker_mananger.py:89 Max retries reached for container 1be0fbf441cf. Exiting log stream.
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X GET "http://127.0.0.1:50557/health" -H "Content-Type: application/json" -d 'None'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'{"nodeHealth":"Ready","protocolsHealth":[]}'
[32mINFO    [0m src.node.waku_node:waku_node.py:282 Node protocols are initialized !!
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X GET "http://127.0.0.1:50557/debug/v1/info" -H "Content-Type: application/json" -d 'None'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'{"listenAddresses":["/ip4/172.18.97.217/tcp/50558/p2p/16Uiu2HAmDd8a8dUAAXoD1PpQLEkLsA347Tqp83wAGP6QPuV1C7pm","/ip4/172.18.97.217/tcp/50559/ws/p2p/16Uiu2HAmDd8a8dUAAXoD1PpQLEkLsA347Tqp83wAGP6QPuV1C7pm"],"enrUri":"enr:-L24QD8y_rSOHkdsUW0NcIEPB-Z-a8OvnM2zujipOyL-fOn9ZlcOO-qeSiRBYEpK-iWCRBrMX0TlxPYkubwcv77DMAkCgmlkgnY0gmlwhKwSYdmKbXVsdGlhZGRyc5YACASsEmHZBsV-AAoErBJh2QbFf90DgnJzhQADAQAAiXNlY3AyNTZrMaEDDmHSQLClnl1KDFuU4nPjRCU6y9AZwO37OXEWG0E3--KDdGNwgsV-g3VkcILFgIV3YWt1MgQ"}'
[32mINFO    [0m src.node.waku_node:waku_node.py:287 REST service is ready !!
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:19 Docker client initialized with image wakuorg/go-waku:latest
[35mDEBUG   [0m src.node.waku_node:waku_node.py:85 WakuNode instance initialized with log path ./log/docker/lightpush_node1_2024-11-27_13-44-37__182dc666-7560-48c5-8676-3e73cc46dca9__wakuorg_go-waku:latest.log
[35mDEBUG   [0m src.node.waku_node:waku_node.py:89 Starting Node...
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:22 Attempting to create or retrieve network waku
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:25 Network waku already exists
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:108 Generated random external IP 172.18.2.178
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:101 Generated ports ['34401', '34402', '34403', '34404', '34405']
[35mDEBUG   [0m src.node.waku_node:waku_node.py:439 RLN credentials were not set
[32mINFO    [0m src.node.waku_node:waku_node.py:168 RLN credentials not set or credential store not available, starting without RLN
[35mDEBUG   [0m src.node.waku_node:waku_node.py:170 Using volumes []
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:49 docker run -i -t -p 34401:34401 -p 34402:34402 -p 34403:34403 -p 34404:34404 -p 34405:34405 wakuorg/go-waku:latest --listen-address=0.0.0.0 --rest=true --rest-admin=true --websocket-support=true --log-level=DEBUG --rest-relay-cache-capacity=100 --websocket-port=34403 --rest-port=34401 --tcp-port=34402 --discv5-udp-port=34404 --rest-address=0.0.0.0 --nat=extip:172.18.2.178 --peer-exchange=true --discv5-discovery=true --cluster-id=3 --nodekey=d2cc86cda3397e0c5fce3ff2dc9bddee01cdbeb67bc8d9c5f15dbfc89de09eea --min-relay-peers-to-publish=1 --rest-filter-cache-capacity=50 --peer-store-capacity=10 --discv5-bootstrap-node=enr:-L24QD8y_rSOHkdsUW0NcIEPB-Z-a8OvnM2zujipOyL-fOn9ZlcOO-qeSiRBYEpK-iWCRBrMX0TlxPYkubwcv77DMAkCgmlkgnY0gmlwhKwSYdmKbXVsdGlhZGRyc5YACASsEmHZBsV-AAoErBJh2QbFf90DgnJzhQADAQAAiXNlY3AyNTZrMaEDDmHSQLClnl1KDFuU4nPjRCU6y9AZwO37OXEWG0E3--KDdGNwgsV-g3VkcILFgIV3YWt1MgQ --lightpushnode=/ip4/172.18.97.217/tcp/50558/p2p/16Uiu2HAmDd8a8dUAAXoD1PpQLEkLsA347Tqp83wAGP6QPuV1C7pm --lightpush=true --relay=false --pubsub-topic=/waku/2/rs/3/1
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:55 docker network connect --ip 172.18.2.178 waku 9aea75c85ec11186152d08dd55df698e60319e016d11fc78e7fd87d71b41cf2d
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:58 Container started with ID 9aea75c85ec1. Setting up logs at ./log/docker/lightpush_node1_2024-11-27_13-44-37__182dc666-7560-48c5-8676-3e73cc46dca9__wakuorg_go-waku:latest.log
[35mDEBUG   [0m src.node.waku_node:waku_node.py:182 Started container from image wakuorg/go-waku:latest. REST: 34401
[35mDEBUG   [0m src.libs.common:common.py:35 Sleeping for 1 seconds
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X GET "http://127.0.0.1:34401/debug/v1/info" -H "Content-Type: application/json" -d 'None'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'{"enrUri":"enr:-KG4QADGx8Iila4oZ6ce7ZBgQ31bYa9vmlFEtA57jB0kM5G6CteAj16_y8WbXGDUP3-IfANcGmLmbuqHQc0s1nU_6leGAZNt3elwgmlkgnY0gmlwhKwRAASCcnOFAAMBAAGJc2VjcDI1NmsxoQKDs5fvVz-FwrhViOZd1cWXfqmA9dvJa82Qcgu0ylff-YN0Y3CChmKDdWRwgoZkhXdha3UyCA","listenAddresses":["/ip4/127.0.0.1/tcp/34402/p2p/16Uiu2HAm4HnDpQft9erdYEirNwYgwC9QipHAKmx74Mk1JY51UPua","/ip4/127.0.0.1/tcp/34403/ws/p2p/16Uiu2HAm4HnDpQft9erdYEirNwYgwC9QipHAKmx74Mk1JY51UPua","/ip4/172.17.0.4/tcp/34402/p2p/16Uiu2HAm4HnDpQft9erdYEirNwYgwC9QipHAKmx74Mk1JY51UPua","/ip4/172.17.0.4/tcp/34403/ws/p2p/16Uiu2HAm4HnDpQft9erdYEirNwYgwC9QipHAKmx74Mk1JY51UPua"]}'
[32mINFO    [0m src.node.waku_node:waku_node.py:287 REST service is ready !!
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X POST "http://127.0.0.1:34401/admin/v1/peers" -H "Content-Type: application/json" -d '{"multiaddr": "/ip4/172.18.97.217/tcp/50558/p2p/16Uiu2HAmDd8a8dUAAXoD1PpQLEkLsA347Tqp83wAGP6QPuV1C7pm", "protocols": ["/vac/waku/relay/2.0.0"], "shards": [0, 1, 2, 3, 4, 5, 6, 7, 8]}'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'null'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X POST "http://127.0.0.1:34401/lightpush/v1/message" -H "Content-Type: application/json" -d '{"pubsubTopic": "/waku/2/rs/3/0", "message": {"payload": "TGlnaHQgcHVzaCB3b3JrcyEh", "contentTopic": "/myapp/1/latest/proto", "timestamp": 1732715081129540608}}'
[31m[1mERROR   [0m src.node.api_clients.base_client:base_client.py:16 HTTP error occurred: 503 Server Error: Service Unavailable for url: http://127.0.0.1:34401/lightpush/v1/message. Response content: b'lightpush error'
[35mDEBUG   [0m tests.conftest:conftest.py:59 Running fixture teardown: test_setup
[35mDEBUG   [0m tests.conftest:conftest.py:83 Running fixture teardown: close_open_nodes
[35mDEBUG   [0m src.node.waku_node:waku_node.py:226 Stopping container with id 5c6a4a2c91cd
[35mDEBUG   [0m src.node.waku_node:waku_node.py:233 Container stopped.
[35mDEBUG   [0m src.node.waku_node:waku_node.py:226 Stopping container with id 9aea75c85ec1
[31m[1mERROR   [0m src.node.docker_mananger:docker_mananger.py:89 Max retries reached for container 5c6a4a2c91cd. Exiting log stream.
[35mDEBUG   [0m src.node.waku_node:waku_node.py:233 Container stopped.
[35mDEBUG   [0m tests.conftest:conftest.py:98 Running fixture teardown: check_waku_log_errors
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:144 No errors found in the waku logs.
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:144 No errors found in the waku logs.