[35mDEBUG   [0m tests.conftest:conftest.py:43 Running fixture setup: test_id
[35mDEBUG   [0m tests.conftest:conftest.py:49 Running test: test_optional_nodes_not_subscribed_to_same_topic with id: 2024-04-18_09-42-34__6a87ed31-0332-4225-88d6-495edc774096
[35mDEBUG   [0m src.steps.filter:filter.py:27 Running fixture setup: filter_setup
[35mDEBUG   [0m src.steps.filter:filter.py:33 Running fixture setup: setup_main_relay_node
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:17 Docker client initialized with image harbor.status.im/wakuorg/nwaku:latest
[35mDEBUG   [0m src.node.waku_node:waku_node.py:50 WakuNode instance initialized with log path ./log/docker/node1_2024-04-18_09-42-34__6a87ed31-0332-4225-88d6-495edc774096__harbor.status.im_wakuorg_nwaku:latest.log
[35mDEBUG   [0m src.node.waku_node:waku_node.py:54 Starting Node...
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:20 Attempting to create or retrieve network waku
[35mDEBUG   [0m src.node.waku_node:waku_node.py:54 Starting Node...
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:20 Attempting to create or retrieve network waku
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:23 Network waku already exists
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:80 Generated random external IP 172.18.190.27
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:73 Generated ports ['4856', '4857', '4858', '4859', '4860']
[35mDEBUG   [0m src.node.waku_node:waku_node.py:315 RLN credentials were not set
[32mINFO    [0m src.node.waku_node:waku_node.py:115 RLN credentials not set or credential store not available, starting without RLN
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:47 docker run -i -t -p 4856:4856 -p 4857:4857 -p 4858:4858 -p 4859:4859 -p 4860:4860 harbor.status.im/wakuorg/nwaku:latest --listen-address=0.0.0.0 --rest=true --rest-admin=true --websocket-support=true --log-level=TRACE --rest-relay-cache-capacity=100 --websocket-port=4858 --rest-port=4856 --tcp-port=4857 --discv5-udp-port=4859 --rest-address=0.0.0.0 --nat=extip:172.18.190.27 --peer-exchange=true --discv5-discovery=true --cluster-id=0 --metrics-server=true --metrics-server-address=0.0.0.0 --metrics-server-port=4860 --metrics-logging=true --relay=true --filter=true --nodekey=30348dd51465150e04a5d9d932c72864c8967f806cce60b5d26afeca1e77eb68
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:53 docker network connect --ip 172.18.190.27 waku f68e0dd6def812965627df1127ba4ef6b70355aaa375a4a336bba547dc289cf0
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:56 Container started with ID f68e0dd6def8. Setting up logs at ./log/docker/node1_2024-04-18_09-42-34__6a87ed31-0332-4225-88d6-495edc774096__harbor.status.im_wakuorg_nwaku:latest.log
[35mDEBUG   [0m src.node.waku_node:waku_node.py:121 Started container from image harbor.status.im/wakuorg/nwaku:latest. REST: 4856
[35mDEBUG   [0m src.libs.common:common.py:35 Sleeping for 1 seconds
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X GET "http://127.0.0.1:4856/debug/v1/info" -H "Content-Type: application/json" -d 'None'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'{"listenAddresses":["/ip4/172.18.190.27/tcp/4857/p2p/16Uiu2HAmGNtM2rQ8abySFNhqPDFY4cmfAEpfo9Z9fD3NekoFR2ip","/ip4/172.18.190.27/tcp/4858/ws/p2p/16Uiu2HAmGNtM2rQ8abySFNhqPDFY4cmfAEpfo9Z9fD3NekoFR2ip"],"enrUri":"enr:-LO4QMysmCbOI5MqOsl0EE2-4G5BHHUEsKW6g5Xb8tUsZPx8XSmvNwnV876lNgZW7ogWcxXIYf7KKG4FhBGkSJ8GctgBgmlkgnY0gmlwhKwSvhuKbXVsdGlhZGRyc4wACgSsEr4bBhL63QOCcnOFAAABAACJc2VjcDI1NmsxoQM3Tqpf5eFn4Jztm4gB0Y0JVSJyxyZsW8QR-QU5DZb-PYN0Y3CCEvmDdWRwghL7hXdha3UyBQ"}'
[32mINFO    [0m src.node.waku_node:waku_node.py:191 REST service is ready !!
[35mDEBUG   [0m src.steps.filter:filter.py:38 Running fixture setup: setup_main_filter_node
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:17 Docker client initialized with image harbor.status.im/wakuorg/nwaku:latest
[35mDEBUG   [0m src.node.waku_node:waku_node.py:50 WakuNode instance initialized with log path ./log/docker/node2_2024-04-18_09-42-34__6a87ed31-0332-4225-88d6-495edc774096__harbor.status.im_wakuorg_nwaku:latest.log
[35mDEBUG   [0m src.node.waku_node:waku_node.py:54 Starting Node...
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:20 Attempting to create or retrieve network waku
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:23 Network waku already exists
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:80 Generated random external IP 172.18.80.51
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:73 Generated ports ['57310', '57311', '57312', '57313', '57314']
[35mDEBUG   [0m src.node.waku_node:waku_node.py:315 RLN credentials were not set
[32mINFO    [0m src.node.waku_node:waku_node.py:115 RLN credentials not set or credential store not available, starting without RLN
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:47 docker run -i -t -p 57310:57310 -p 57311:57311 -p 57312:57312 -p 57313:57313 -p 57314:57314 harbor.status.im/wakuorg/nwaku:latest --listen-address=0.0.0.0 --rest=true --rest-admin=true --websocket-support=true --log-level=TRACE --rest-relay-cache-capacity=100 --websocket-port=57312 --rest-port=57310 --tcp-port=57311 --discv5-udp-port=57313 --rest-address=0.0.0.0 --nat=extip:172.18.80.51 --peer-exchange=true --discv5-discovery=true --cluster-id=0 --metrics-server=true --metrics-server-address=0.0.0.0 --metrics-server-port=57314 --metrics-logging=true --relay=false --discv5-bootstrap-node=enr:-LO4QMysmCbOI5MqOsl0EE2-4G5BHHUEsKW6g5Xb8tUsZPx8XSmvNwnV876lNgZW7ogWcxXIYf7KKG4FhBGkSJ8GctgBgmlkgnY0gmlwhKwSvhuKbXVsdGlhZGRyc4wACgSsEr4bBhL63QOCcnOFAAABAACJc2VjcDI1NmsxoQM3Tqpf5eFn4Jztm4gB0Y0JVSJyxyZsW8QR-QU5DZb-PYN0Y3CCEvmDdWRwghL7hXdha3UyBQ --filternode=/ip4/172.18.190.27/tcp/4857/p2p/16Uiu2HAmGNtM2rQ8abySFNhqPDFY4cmfAEpfo9Z9fD3NekoFR2ip
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:53 docker network connect --ip 172.18.80.51 waku c6c06b1545764c08552eb4009c194bdc6d89ad5509042920caf48107d72e4a38
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:56 Container started with ID c6c06b154576. Setting up logs at ./log/docker/node2_2024-04-18_09-42-34__6a87ed31-0332-4225-88d6-495edc774096__harbor.status.im_wakuorg_nwaku:latest.log
[35mDEBUG   [0m src.node.waku_node:waku_node.py:121 Started container from image harbor.status.im/wakuorg/nwaku:latest. REST: 57310
[35mDEBUG   [0m src.libs.common:common.py:35 Sleeping for 1 seconds
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X GET "http://127.0.0.1:57310/debug/v1/info" -H "Content-Type: application/json" -d 'None'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'{"listenAddresses":["/ip4/172.18.80.51/tcp/57311/p2p/16Uiu2HAmKgwxfZiUVqw5KR5yxR8LFAVg8QYV7J3i9CT2NJPTJJLg","/ip4/172.18.80.51/tcp/57312/ws/p2p/16Uiu2HAmKgwxfZiUVqw5KR5yxR8LFAVg8QYV7J3i9CT2NJPTJJLg"],"enrUri":"enr:-LO4QGhd21ldsjtLK_q7bOIHIGicg8QDGFS0Da8VNCsby6XSdQnDdxWi50MClz2HKmUcCzr9c6fJ0zGr1ceZzb_7K98BgmlkgnY0gmlwhKwSUDOKbXVsdGlhZGRyc4wACgSsElAzBt_g3QOCcnOFAAABAACJc2VjcDI1NmsxoQNogkSEC76pFlQLPRP2G6I3ask2-4v6ulwlacLGdoqXoYN0Y3CC39-DdWRwgt_hhXdha3UyAA"}'
[32mINFO    [0m src.node.waku_node:waku_node.py:191 REST service is ready !!
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X POST "http://127.0.0.1:57310/admin/v1/peers" -H "Content-Type: application/json" -d '["/ip4/172.18.190.27/tcp/4857/p2p/16Uiu2HAmGNtM2rQ8abySFNhqPDFY4cmfAEpfo9Z9fD3NekoFR2ip"]'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'OK'
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:17 Docker client initialized with image harbor.status.im/wakuorg/nwaku:latest
[35mDEBUG   [0m src.node.waku_node:waku_node.py:50 WakuNode instance initialized with log path ./log/docker/node3_2024-04-18_09-42-34__6a87ed31-0332-4225-88d6-495edc774096__harbor.status.im_wakuorg_nwaku:latest.log
[35mDEBUG   [0m src.node.waku_node:waku_node.py:54 Starting Node...
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:20 Attempting to create or retrieve network waku
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:23 Network waku already exists
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:80 Generated random external IP 172.18.170.183
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:73 Generated ports ['14933', '14934', '14935', '14936', '14937']
[35mDEBUG   [0m src.node.waku_node:waku_node.py:315 RLN credentials were not set
[32mINFO    [0m src.node.waku_node:waku_node.py:115 RLN credentials not set or credential store not available, starting without RLN
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:47 docker run -i -t -p 14933:14933 -p 14934:14934 -p 14935:14935 -p 14936:14936 -p 14937:14937 harbor.status.im/wakuorg/nwaku:latest --listen-address=0.0.0.0 --rest=true --rest-admin=true --websocket-support=true --log-level=TRACE --rest-relay-cache-capacity=100 --websocket-port=14935 --rest-port=14933 --tcp-port=14934 --discv5-udp-port=14936 --rest-address=0.0.0.0 --nat=extip:172.18.170.183 --peer-exchange=true --discv5-discovery=true --cluster-id=0 --metrics-server=true --metrics-server-address=0.0.0.0 --metrics-server-port=14937 --metrics-logging=true --relay=false --discv5-bootstrap-node=enr:-LO4QMysmCbOI5MqOsl0EE2-4G5BHHUEsKW6g5Xb8tUsZPx8XSmvNwnV876lNgZW7ogWcxXIYf7KKG4FhBGkSJ8GctgBgmlkgnY0gmlwhKwSvhuKbXVsdGlhZGRyc4wACgSsEr4bBhL63QOCcnOFAAABAACJc2VjcDI1NmsxoQM3Tqpf5eFn4Jztm4gB0Y0JVSJyxyZsW8QR-QU5DZb-PYN0Y3CCEvmDdWRwghL7hXdha3UyBQ --filternode=/ip4/172.18.190.27/tcp/4857/p2p/16Uiu2HAmGNtM2rQ8abySFNhqPDFY4cmfAEpfo9Z9fD3NekoFR2ip
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:53 docker network connect --ip 172.18.170.183 waku e57cb01c609dc3e0219729a160287c02d00316373a4cc8520fe31a30bead2992
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:56 Container started with ID e57cb01c609d. Setting up logs at ./log/docker/node3_2024-04-18_09-42-34__6a87ed31-0332-4225-88d6-495edc774096__harbor.status.im_wakuorg_nwaku:latest.log
[35mDEBUG   [0m src.node.waku_node:waku_node.py:121 Started container from image harbor.status.im/wakuorg/nwaku:latest. REST: 14933
[35mDEBUG   [0m src.libs.common:common.py:35 Sleeping for 1 seconds
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X GET "http://127.0.0.1:14933/debug/v1/info" -H "Content-Type: application/json" -d 'None'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'{"listenAddresses":["/ip4/172.18.170.183/tcp/14934/p2p/16Uiu2HAmRKR1ink9ohBZXqobXAzfKsrT97UDAAc2vSQH72oUKay1","/ip4/172.18.170.183/tcp/14935/ws/p2p/16Uiu2HAmRKR1ink9ohBZXqobXAzfKsrT97UDAAc2vSQH72oUKay1"],"enrUri":"enr:-LO4QMzk-w_al4lulyaC5t2ZnqFZC0lWf_gCsFoLrYUXCwgqYHzDvoEPMzJaHo7G5OwhTjbLWsa-P-UailXCK6fYt-0BgmlkgnY0gmlwhKwSqreKbXVsdGlhZGRyc4wACgSsEqq3BjpX3QOCcnOFAAABAACJc2VjcDI1NmsxoQO8JDMw2kUQVxUKNSxvM1x-yu2uoYp1atYwvhjfdK9f1IN0Y3CCOlaDdWRwgjpYhXdha3UyAA"}'
[32mINFO    [0m src.node.waku_node:waku_node.py:191 REST service is ready !!
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X POST "http://127.0.0.1:14933/admin/v1/peers" -H "Content-Type: application/json" -d '["/ip4/172.18.190.27/tcp/4857/p2p/16Uiu2HAmGNtM2rQ8abySFNhqPDFY4cmfAEpfo9Z9fD3NekoFR2ip"]'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'OK'
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:17 Docker client initialized with image harbor.status.im/wakuorg/go-waku:latest
[35mDEBUG   [0m src.node.waku_node:waku_node.py:50 WakuNode instance initialized with log path ./log/docker/node4_2024-04-18_09-42-34__6a87ed31-0332-4225-88d6-495edc774096__harbor.status.im_wakuorg_go-waku:latest.log
[35mDEBUG   [0m src.node.waku_node:waku_node.py:54 Starting Node...
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:20 Attempting to create or retrieve network waku
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:23 Network waku already exists
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:80 Generated random external IP 172.18.74.165
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:73 Generated ports ['38132', '38133', '38134', '38135', '38136']
[35mDEBUG   [0m src.node.waku_node:waku_node.py:315 RLN credentials were not set
[32mINFO    [0m src.node.waku_node:waku_node.py:115 RLN credentials not set or credential store not available, starting without RLN
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:47 docker run -i -t -p 38132:38132 -p 38133:38133 -p 38134:38134 -p 38135:38135 -p 38136:38136 harbor.status.im/wakuorg/go-waku:latest --listen-address=0.0.0.0 --rest=true --rest-admin=true --websocket-support=true --log-level=DEBUG --rest-relay-cache-capacity=100 --websocket-port=38134 --rest-port=38132 --tcp-port=38133 --discv5-udp-port=38135 --rest-address=0.0.0.0 --nat=extip:172.18.74.165 --peer-exchange=true --discv5-discovery=true --cluster-id=0 --min-relay-peers-to-publish=1 --rest-filter-cache-capacity=50 --relay=false --discv5-bootstrap-node=enr:-LO4QMysmCbOI5MqOsl0EE2-4G5BHHUEsKW6g5Xb8tUsZPx8XSmvNwnV876lNgZW7ogWcxXIYf7KKG4FhBGkSJ8GctgBgmlkgnY0gmlwhKwSvhuKbXVsdGlhZGRyc4wACgSsEr4bBhL63QOCcnOFAAABAACJc2VjcDI1NmsxoQM3Tqpf5eFn4Jztm4gB0Y0JVSJyxyZsW8QR-QU5DZb-PYN0Y3CCEvmDdWRwghL7hXdha3UyBQ --filternode=/ip4/172.18.190.27/tcp/4857/p2p/16Uiu2HAmGNtM2rQ8abySFNhqPDFY4cmfAEpfo9Z9fD3NekoFR2ip
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:53 docker network connect --ip 172.18.74.165 waku 3f2dd8728b5976f8a97170a69548500fac6396d10ec56dcf9e34475d31f5755a
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:56 Container started with ID 3f2dd8728b59. Setting up logs at ./log/docker/node4_2024-04-18_09-42-34__6a87ed31-0332-4225-88d6-495edc774096__harbor.status.im_wakuorg_go-waku:latest.log
[35mDEBUG   [0m src.node.waku_node:waku_node.py:121 Started container from image harbor.status.im/wakuorg/go-waku:latest. REST: 38132
[35mDEBUG   [0m src.libs.common:common.py:35 Sleeping for 1 seconds
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X GET "http://127.0.0.1:38132/debug/v1/info" -H "Content-Type: application/json" -d 'None'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'{"enrUri":"enr:-Ly4QHcXYE_qsAPQ3hK7OnFO4tHXbmV4IBcCvzTNQ6hsdt4OSeKV6ObtuCEbhcj2ZH_mG19WxVHp9rW-mvO4PyJZBoeGAY7wloS5gmlkgnY0gmlwhKwRAAmKbXVsdGlhZGRyc5gACgR_AAABBpT23QMACgSsEQAJBpT23QOJc2VjcDI1NmsxoQO3hgvWFEi15DSQby_pr45MOw-ilGOXut4DgXoMpOkUVoN0Y3CClPWDdWRwgpT3hXdha3UygA","listenAddresses":["/ip4/127.0.0.1/tcp/38133/p2p/16Uiu2HAmR1PWZY5HtSWLsmuuLo24YJ5PNm3bEZTaBsYoKz1rn89s","/ip4/127.0.0.1/tcp/38134/ws/p2p/16Uiu2HAmR1PWZY5HtSWLsmuuLo24YJ5PNm3bEZTaBsYoKz1rn89s","/ip4/172.17.0.9/tcp/38133/p2p/16Uiu2HAmR1PWZY5HtSWLsmuuLo24YJ5PNm3bEZTaBsYoKz1rn89s","/ip4/172.17.0.9/tcp/38134/ws/p2p/16Uiu2HAmR1PWZY5HtSWLsmuuLo24YJ5PNm3bEZTaBsYoKz1rn89s"]}'
[32mINFO    [0m src.node.waku_node:waku_node.py:191 REST service is ready !!
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:17 Docker client initialized with image harbor.status.im/wakuorg/nwaku:latest
[35mDEBUG   [0m src.node.waku_node:waku_node.py:50 WakuNode instance initialized with log path ./log/docker/node5_2024-04-18_09-42-34__6a87ed31-0332-4225-88d6-495edc774096__harbor.status.im_wakuorg_nwaku:latest.log
[35mDEBUG   [0m src.node.waku_node:waku_node.py:54 Starting Node...
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:20 Attempting to create or retrieve network waku
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:23 Network waku already exists
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:80 Generated random external IP 172.18.101.202
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:73 Generated ports ['41711', '41712', '41713', '41714', '41715']
[35mDEBUG   [0m src.node.waku_node:waku_node.py:315 RLN credentials were not set
[32mINFO    [0m src.node.waku_node:waku_node.py:115 RLN credentials not set or credential store not available, starting without RLN
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:47 docker run -i -t -p 41711:41711 -p 41712:41712 -p 41713:41713 -p 41714:41714 -p 41715:41715 harbor.status.im/wakuorg/nwaku:latest --listen-address=0.0.0.0 --rest=true --rest-admin=true --websocket-support=true --log-level=TRACE --rest-relay-cache-capacity=100 --websocket-port=41713 --rest-port=41711 --tcp-port=41712 --discv5-udp-port=41714 --rest-address=0.0.0.0 --nat=extip:172.18.101.202 --peer-exchange=true --discv5-discovery=true --cluster-id=0 --metrics-server=true --metrics-server-address=0.0.0.0 --metrics-server-port=41715 --metrics-logging=true --relay=false --discv5-bootstrap-node=enr:-LO4QMysmCbOI5MqOsl0EE2-4G5BHHUEsKW6g5Xb8tUsZPx8XSmvNwnV876lNgZW7ogWcxXIYf7KKG4FhBGkSJ8GctgBgmlkgnY0gmlwhKwSvhuKbXVsdGlhZGRyc4wACgSsEr4bBhL63QOCcnOFAAABAACJc2VjcDI1NmsxoQM3Tqpf5eFn4Jztm4gB0Y0JVSJyxyZsW8QR-QU5DZb-PYN0Y3CCEvmDdWRwghL7hXdha3UyBQ --filternode=/ip4/172.18.190.27/tcp/4857/p2p/16Uiu2HAmGNtM2rQ8abySFNhqPDFY4cmfAEpfo9Z9fD3NekoFR2ip
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:53 docker network connect --ip 172.18.101.202 waku 2ea882a39eefba4265606f10654280f354483c5f36a23022a161c4a014b4f72a
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:56 Container started with ID 2ea882a39eef. Setting up logs at ./log/docker/node5_2024-04-18_09-42-34__6a87ed31-0332-4225-88d6-495edc774096__harbor.status.im_wakuorg_nwaku:latest.log
[35mDEBUG   [0m src.node.waku_node:waku_node.py:121 Started container from image harbor.status.im/wakuorg/nwaku:latest. REST: 41711
[35mDEBUG   [0m src.libs.common:common.py:35 Sleeping for 1 seconds
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X GET "http://127.0.0.1:41711/debug/v1/info" -H "Content-Type: application/json" -d 'None'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'{"listenAddresses":["/ip4/172.18.101.202/tcp/41712/p2p/16Uiu2HAmPefGdY1rix122tb3i2VABLx65waS3Ca9CjVexe62AM7L","/ip4/172.18.101.202/tcp/41713/ws/p2p/16Uiu2HAmPefGdY1rix122tb3i2VABLx65waS3Ca9CjVexe62AM7L"],"enrUri":"enr:-LO4QFBQhVhxew4hZTtZ0ckZNZRPhrI0ObbNXYvh4fJ-ovS9f-ucZcREURTziNw_mRc5g1qIcN0bBXhsajxkkim639IBgmlkgnY0gmlwhKwSZcqKbXVsdGlhZGRyc4wACgSsEmXKBqLx3QOCcnOFAAABAACJc2VjcDI1NmsxoQOjWvtjz-whuIYoCgZDk_ks8wLNT_7UpQwMtimeAyXSl4N0Y3CCovCDdWRwgqLyhXdha3UyAA"}'
[32mINFO    [0m src.node.waku_node:waku_node.py:191 REST service is ready !!
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X POST "http://127.0.0.1:41711/admin/v1/peers" -H "Content-Type: application/json" -d '["/ip4/172.18.190.27/tcp/4857/p2p/16Uiu2HAmGNtM2rQ8abySFNhqPDFY4cmfAEpfo9Z9fD3NekoFR2ip"]'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'OK'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X POST "http://127.0.0.1:4856/relay/v1/subscriptions" -H "Content-Type: application/json" -d '["/waku/2/rs/0/1"]'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'OK'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X POST "http://127.0.0.1:57310/filter/v2/subscriptions" -H "Content-Type: application/json" -d '{"requestId": "c44d6a49-49c6-44db-bf44-0a0a376a44b5", "contentFilters": ["/test/1/waku-filter/proto"], "pubsubTopic": "/waku/2/rs/0/1"}'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'{"requestId":"c44d6a49-49c6-44db-bf44-0a0a376a44b5","statusDesc":"OK"}'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X POST "http://127.0.0.1:14933/filter/v2/subscriptions" -H "Content-Type: application/json" -d '{"requestId": "1c187a87-8e72-4195-9583-319504e7f25f", "contentFilters": ["/test/2/waku-filter/proto"], "pubsubTopic": "/waku/2/rs/0/1"}'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'{"requestId":"1c187a87-8e72-4195-9583-319504e7f25f","statusDesc":"OK"}'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X POST "http://127.0.0.1:38132/filter/v2/subscriptions" -H "Content-Type: application/json" -d '{"requestId": "eb78f110-76dc-4ecf-9a24-40e113218d59", "contentFilters": ["/test/2/waku-filter/proto"], "pubsubTopic": "/waku/2/rs/0/1"}'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'{"requestId":"eb78f110-76dc-4ecf-9a24-40e113218d59","statusDesc":"OK"}'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X POST "http://127.0.0.1:41711/filter/v2/subscriptions" -H "Content-Type: application/json" -d '{"requestId": "e048ffea-fc53-49c9-8ffa-01d92ac6690e", "contentFilters": ["/test/2/waku-filter/proto"], "pubsubTopic": "/waku/2/rs/0/1"}'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'{"requestId":"e048ffea-fc53-49c9-8ffa-01d92ac6690e","statusDesc":"OK"}'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X POST "http://127.0.0.1:4856/relay/v1/messages/%2Fwaku%2F2%2Frs%2F0%2F1" -H "Content-Type: application/json" -d '{"payload": "RmlsdGVyIHdvcmtzISE=", "contentTopic": "/test/1/waku-filter/proto", "timestamp": '$(date +%s%N)'}'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'OK'
[35mDEBUG   [0m src.libs.common:common.py:35 Sleeping for 0.1 seconds
[35mDEBUG   [0m src.steps.filter:filter.py:98 Checking that peer NODE_2:harbor.status.im/wakuorg/nwaku:latest can find the published message
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X GET "http://127.0.0.1:57310/filter/v2/messages/%2Ftest%2F1%2Fwaku-filter%2Fproto" -H "Content-Type: application/json" -d 'None'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'[{"payload":"RmlsdGVyIHdvcmtzISE=","contentTopic":"/test/1/waku-filter/proto","version":0,"timestamp":1713433395297501440,"ephemeral":false}]'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X POST "http://127.0.0.1:4856/relay/v1/messages/%2Fwaku%2F2%2Frs%2F0%2F1" -H "Content-Type: application/json" -d '{"payload": "RmlsdGVyIHdvcmtzISE=", "contentTopic": "/test/1/waku-filter/proto", "timestamp": '$(date +%s%N)'}'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'OK'
[35mDEBUG   [0m src.libs.common:common.py:35 Sleeping for 0.1 seconds
[35mDEBUG   [0m src.steps.filter:filter.py:98 Checking that peer NODE_2:harbor.status.im/wakuorg/nwaku:latest can find the published message
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X GET "http://127.0.0.1:14933/filter/v2/messages/%2Ftest%2F1%2Fwaku-filter%2Fproto" -H "Content-Type: application/json" -d 'None'
[31m[1mERROR   [0m src.node.api_clients.base_client:base_client.py:16 HTTP error occurred: 400 Client Error: Bad Request for url: http://127.0.0.1:14933/filter/v2/messages/%2Ftest%2F1%2Fwaku-filter%2Fproto. Response content: b'Not subscribed to topic: /test/1/waku-filter/proto'
[35mDEBUG   [0m tests.conftest:conftest.py:51 Running fixture teardown: test_setup
[35mDEBUG   [0m tests.conftest:conftest.py:75 Running fixture teardown: close_open_nodes
[35mDEBUG   [0m src.node.waku_node:waku_node.py:168 Stopping container with id f68e0dd6def8
[35mDEBUG   [0m src.node.waku_node:waku_node.py:171 Container stopped.
[35mDEBUG   [0m src.node.waku_node:waku_node.py:168 Stopping container with id c6c06b154576
[35mDEBUG   [0m src.node.waku_node:waku_node.py:171 Container stopped.
[35mDEBUG   [0m src.node.waku_node:waku_node.py:168 Stopping container with id e57cb01c609d
[35mDEBUG   [0m src.node.waku_node:waku_node.py:171 Container stopped.
[35mDEBUG   [0m src.node.waku_node:waku_node.py:168 Stopping container with id 3f2dd8728b59
[35mDEBUG   [0m src.node.waku_node:waku_node.py:171 Container stopped.
[35mDEBUG   [0m src.node.waku_node:waku_node.py:168 Stopping container with id 2ea882a39eef
[35mDEBUG   [0m src.node.waku_node:waku_node.py:171 Container stopped.