[35mDEBUG   [0m tests.conftest:conftest.py:51 Running fixture setup: test_id
[35mDEBUG   [0m tests.conftest:conftest.py:57 Running test: test_2_receiving_nodes__relay_node1_forwards_lightpushed_message_to_relay_node2 with id: 2025-02-06_15-41-24__f0efc0fe-d88b-4ea4-ac8f-1c841e1004fb
[35mDEBUG   [0m src.steps.common:common.py:18 Running fixture setup: common_setup
[35mDEBUG   [0m src.steps.light_push:light_push.py:28 Running fixture setup: light_push_setup
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:19 Docker client initialized with image quay.io/wakuorg/nwaku-pr:3281
[35mDEBUG   [0m src.node.waku_node:waku_node.py:85 WakuNode instance initialized with log path ./log/docker/receiving_node1_2025-02-06_15-41-24__f0efc0fe-d88b-4ea4-ac8f-1c841e1004fb__quay.io_wakuorg_nwaku-pr:3281.log
[35mDEBUG   [0m src.node.waku_node:waku_node.py:89 Starting Node...
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:22 Attempting to create or retrieve network waku
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:25 Network waku already exists
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:108 Generated random external IP 172.18.197.175
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:101 Generated ports ['22595', '22596', '22597', '22598', '22599']
[35mDEBUG   [0m src.node.waku_node:waku_node.py:439 RLN credentials were not set
[32mINFO    [0m src.node.waku_node:waku_node.py:168 RLN credentials not set or credential store not available, starting without RLN
[35mDEBUG   [0m src.node.waku_node:waku_node.py:170 Using volumes []
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:49 docker run -i -t -p 22595:22595 -p 22596:22596 -p 22597:22597 -p 22598:22598 -p 22599:22599 quay.io/wakuorg/nwaku-pr:3281 --listen-address=0.0.0.0 --rest=true --rest-admin=true --websocket-support=true --log-level=TRACE --rest-relay-cache-capacity=100 --websocket-port=22597 --rest-port=22595 --tcp-port=22596 --discv5-udp-port=22598 --rest-address=0.0.0.0 --nat=extip:172.18.197.175 --peer-exchange=true --discv5-discovery=true --cluster-id=3 --nodekey=2da88af99b66bab9b6fdbb837dccaabace1a5bdb5d3b5d710d7bb5f71f0bfd8c --shard=0 --metrics-server=true --metrics-server-address=0.0.0.0 --metrics-server-port=22599 --metrics-logging=true --lightpush=true --relay=true
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:55 docker network connect --ip 172.18.197.175 waku 499ef2f65791c74ff0509442cda8bbefae165ce1ac6de356c9deda6bc4e21473
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:58 Container started with ID 499ef2f65791. Setting up logs at ./log/docker/receiving_node1_2025-02-06_15-41-24__f0efc0fe-d88b-4ea4-ac8f-1c841e1004fb__quay.io_wakuorg_nwaku-pr:3281.log
[35mDEBUG   [0m src.node.waku_node:waku_node.py:182 Started container from image quay.io/wakuorg/nwaku-pr:3281. REST: 22595
[35mDEBUG   [0m src.libs.common:common.py:47 Sleeping for 1 seconds
[1m[31mERROR   [0m src.node.docker_mananger:docker_mananger.py:89 Max retries reached for container c8dccdb43048. Exiting log stream.
[1m[31mERROR   [0m src.node.docker_mananger:docker_mananger.py:89 Max retries reached for container 948d296401dc. Exiting log stream.
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X GET "http://127.0.0.1:22595/health" -H "Content-Type: application/json" -d 'None'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'{"nodeHealth":"Ready","protocolsHealth":[]}'
[32mINFO    [0m src.node.waku_node:waku_node.py:282 Node protocols are initialized !!
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X GET "http://127.0.0.1:22595/debug/v1/info" -H "Content-Type: application/json" -d 'None'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'{"listenAddresses":["/ip4/172.18.197.175/tcp/22596/p2p/16Uiu2HAm8HFejTS5mKmrNHpZeJsCeivBis8xicMpVpx2ivhDa2VP","/ip4/172.18.197.175/tcp/22597/ws/p2p/16Uiu2HAm8HFejTS5mKmrNHpZeJsCeivBis8xicMpVpx2ivhDa2VP"],"enrUri":"enr:-L24QIctULi2tvd5pzyiUqYbPdvOpdjnPQsQy_6p9PVViU-sPosVHnuKQOlPJjdczAscy02G1aedGbIZDoaOrnse9pMCgmlkgnY0gmlwhKwSxa-KbXVsdGlhZGRyc5YACASsEsWvBlhEAAoErBLFrwZYRd0DgnJzhQADAQAAiXNlY3AyNTZrMaECvv_GbMPL4OOAXamq_7XKS5yop8iLq4hg-8-NrAOTDTqDdGNwglhEg3VkcIJYRoV3YWt1Mgk"}'
[32mINFO    [0m src.node.waku_node:waku_node.py:287 REST service is ready !!
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:19 Docker client initialized with image quay.io/wakuorg/nwaku-pr:3281
[35mDEBUG   [0m src.node.waku_node:waku_node.py:85 WakuNode instance initialized with log path ./log/docker/receiving_node2_2025-02-06_15-41-24__f0efc0fe-d88b-4ea4-ac8f-1c841e1004fb__quay.io_wakuorg_nwaku-pr:3281.log
[35mDEBUG   [0m src.node.waku_node:waku_node.py:89 Starting Node...
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:22 Attempting to create or retrieve network waku
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:25 Network waku already exists
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:108 Generated random external IP 172.18.148.86
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:101 Generated ports ['18025', '18026', '18027', '18028', '18029']
[35mDEBUG   [0m src.node.waku_node:waku_node.py:439 RLN credentials were not set
[32mINFO    [0m src.node.waku_node:waku_node.py:168 RLN credentials not set or credential store not available, starting without RLN
[35mDEBUG   [0m src.node.waku_node:waku_node.py:170 Using volumes []
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:49 docker run -i -t -p 18025:18025 -p 18026:18026 -p 18027:18027 -p 18028:18028 -p 18029:18029 quay.io/wakuorg/nwaku-pr:3281 --listen-address=0.0.0.0 --rest=true --rest-admin=true --websocket-support=true --log-level=TRACE --rest-relay-cache-capacity=100 --websocket-port=18027 --rest-port=18025 --tcp-port=18026 --discv5-udp-port=18028 --rest-address=0.0.0.0 --nat=extip:172.18.148.86 --peer-exchange=true --discv5-discovery=true --cluster-id=3 --nodekey=bcca941b82ce23a1bcea6756feb0cb3fc51f75125dd127dd3f506929c53bdebd --shard=0 --metrics-server=true --metrics-server-address=0.0.0.0 --metrics-server-port=18029 --metrics-logging=true --lightpush=false --relay=true
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:55 docker network connect --ip 172.18.148.86 waku 44837f75ca122877fbc245a8b57f47b4792254a7d358a6d4280065b68208af9c
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:58 Container started with ID 44837f75ca12. Setting up logs at ./log/docker/receiving_node2_2025-02-06_15-41-24__f0efc0fe-d88b-4ea4-ac8f-1c841e1004fb__quay.io_wakuorg_nwaku-pr:3281.log
[35mDEBUG   [0m src.node.waku_node:waku_node.py:182 Started container from image quay.io/wakuorg/nwaku-pr:3281. REST: 18025
[35mDEBUG   [0m src.libs.common:common.py:47 Sleeping for 1 seconds
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X GET "http://127.0.0.1:18025/health" -H "Content-Type: application/json" -d 'None'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'{"nodeHealth":"Ready","protocolsHealth":[]}'
[32mINFO    [0m src.node.waku_node:waku_node.py:282 Node protocols are initialized !!
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X GET "http://127.0.0.1:18025/debug/v1/info" -H "Content-Type: application/json" -d 'None'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'{"listenAddresses":["/ip4/172.18.148.86/tcp/18026/p2p/16Uiu2HAkyAt5iG3T9C6tk2hG7bcpAQaWPNwq7qUtpVe95xApk6q9","/ip4/172.18.148.86/tcp/18027/ws/p2p/16Uiu2HAkyAt5iG3T9C6tk2hG7bcpAQaWPNwq7qUtpVe95xApk6q9"],"enrUri":"enr:-L24QE8KvDrRUOxCEfb4FHlopm5-w0ehkbp6HIPDa7kUWodXVfrbDa-4-jOh2tt0mCEQy2fajGDfMCJB0Cyn2M23QYcCgmlkgnY0gmlwhKwSlFaKbXVsdGlhZGRyc5YACASsEpRWBkZqAAoErBKUVgZGa90DgnJzhQADAQAAiXNlY3AyNTZrMaECN6S4KltJ1szSWsO1xTU_vbMU-aR9FqBd3WrEWtAN3aSDdGNwgkZqg3VkcIJGbIV3YWt1MgE"}'
[32mINFO    [0m src.node.waku_node:waku_node.py:287 REST service is ready !!
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X POST "http://127.0.0.1:18025/admin/v1/peers" -H "Content-Type: application/json" -d '["/ip4/172.18.197.175/tcp/22596/p2p/16Uiu2HAm8HFejTS5mKmrNHpZeJsCeivBis8xicMpVpx2ivhDa2VP"]'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'OK'
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:19 Docker client initialized with image wakuorg/go-waku:latest
[35mDEBUG   [0m src.node.waku_node:waku_node.py:85 WakuNode instance initialized with log path ./log/docker/lightpush_node1_2025-02-06_15-41-24__f0efc0fe-d88b-4ea4-ac8f-1c841e1004fb__wakuorg_go-waku:latest.log
[35mDEBUG   [0m src.node.waku_node:waku_node.py:89 Starting Node...
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:22 Attempting to create or retrieve network waku
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:25 Network waku already exists
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:108 Generated random external IP 172.18.54.106
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:101 Generated ports ['29024', '29025', '29026', '29027', '29028']
[35mDEBUG   [0m src.node.waku_node:waku_node.py:439 RLN credentials were not set
[32mINFO    [0m src.node.waku_node:waku_node.py:168 RLN credentials not set or credential store not available, starting without RLN
[35mDEBUG   [0m src.node.waku_node:waku_node.py:170 Using volumes []
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:49 docker run -i -t -p 29024:29024 -p 29025:29025 -p 29026:29026 -p 29027:29027 -p 29028:29028 wakuorg/go-waku:latest --listen-address=0.0.0.0 --rest=true --rest-admin=true --websocket-support=true --log-level=DEBUG --rest-relay-cache-capacity=100 --websocket-port=29026 --rest-port=29024 --tcp-port=29025 --discv5-udp-port=29027 --rest-address=0.0.0.0 --nat=extip:172.18.54.106 --peer-exchange=true --discv5-discovery=true --cluster-id=3 --nodekey=f12862bde5dbabd7edd5e15cfb51d3c05af6ffb30d2b7c38df2d6c8af76ac747 --min-relay-peers-to-publish=1 --rest-filter-cache-capacity=50 --peer-store-capacity=10 --discv5-bootstrap-node=enr:-L24QIctULi2tvd5pzyiUqYbPdvOpdjnPQsQy_6p9PVViU-sPosVHnuKQOlPJjdczAscy02G1aedGbIZDoaOrnse9pMCgmlkgnY0gmlwhKwSxa-KbXVsdGlhZGRyc5YACASsEsWvBlhEAAoErBLFrwZYRd0DgnJzhQADAQAAiXNlY3AyNTZrMaECvv_GbMPL4OOAXamq_7XKS5yop8iLq4hg-8-NrAOTDTqDdGNwglhEg3VkcIJYRoV3YWt1Mgk --lightpushnode=/ip4/172.18.197.175/tcp/22596/p2p/16Uiu2HAm8HFejTS5mKmrNHpZeJsCeivBis8xicMpVpx2ivhDa2VP --lightpush=true --relay=false --pubsub-topic=/waku/2/rs/3/1
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:55 docker network connect --ip 172.18.54.106 waku 4f0bdd810c7229e937186fa9fa896bd16c9b5706b5b534f7031a521185abf6a1
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:58 Container started with ID 4f0bdd810c72. Setting up logs at ./log/docker/lightpush_node1_2025-02-06_15-41-24__f0efc0fe-d88b-4ea4-ac8f-1c841e1004fb__wakuorg_go-waku:latest.log
[35mDEBUG   [0m src.node.waku_node:waku_node.py:182 Started container from image wakuorg/go-waku:latest. REST: 29024
[35mDEBUG   [0m src.libs.common:common.py:47 Sleeping for 1 seconds
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X GET "http://127.0.0.1:29024/debug/v1/info" -H "Content-Type: application/json" -d 'None'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'{"enrUri":"enr:-KG4QCNhL2vIcQwrCc8XksWQnX2qhPrYk6KD0qXLdKWaqvXKRhSUrrrNpWQTRcKzv8z04ent8xzIlrzWsTfULpq1XcKGAZTb7FhbgmlkgnY0gmlwhKwRAASCcnOFAAMBAAGJc2VjcDI1NmsxoQPT8rr9aP0sOuv_GXrLK2wzNv_JXYy85qDWblMf_KjMOIN0Y3CCcWGDdWRwgnFjhXdha3UyCA","listenAddresses":["/ip4/127.0.0.1/tcp/29025/p2p/16Uiu2HAmSvM3fx5GkgkfRB2qeSEmz5sJCqdE12RwZ5xnwedqcUYo","/ip4/127.0.0.1/tcp/29026/ws/p2p/16Uiu2HAmSvM3fx5GkgkfRB2qeSEmz5sJCqdE12RwZ5xnwedqcUYo","/ip4/172.17.0.4/tcp/29025/p2p/16Uiu2HAmSvM3fx5GkgkfRB2qeSEmz5sJCqdE12RwZ5xnwedqcUYo","/ip4/172.17.0.4/tcp/29026/ws/p2p/16Uiu2HAmSvM3fx5GkgkfRB2qeSEmz5sJCqdE12RwZ5xnwedqcUYo"]}'
[32mINFO    [0m src.node.waku_node:waku_node.py:287 REST service is ready !!
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X POST "http://127.0.0.1:29024/admin/v1/peers" -H "Content-Type: application/json" -d '{"multiaddr": "/ip4/172.18.197.175/tcp/22596/p2p/16Uiu2HAm8HFejTS5mKmrNHpZeJsCeivBis8xicMpVpx2ivhDa2VP", "protocols": ["/vac/waku/relay/2.0.0"], "shards": [0, 1, 2, 3, 4, 5, 6, 7, 8]}'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'null'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X POST "http://127.0.0.1:29024/admin/v1/peers" -H "Content-Type: application/json" -d '{"multiaddr": "/ip4/172.18.148.86/tcp/18026/p2p/16Uiu2HAkyAt5iG3T9C6tk2hG7bcpAQaWPNwq7qUtpVe95xApk6q9", "protocols": ["/vac/waku/relay/2.0.0"], "shards": [0, 1, 2, 3, 4, 5, 6, 7, 8]}'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'null'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X POST "http://127.0.0.1:22595/relay/v1/subscriptions" -H "Content-Type: application/json" -d '["/waku/2/rs/3/0"]'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'OK'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X POST "http://127.0.0.1:18025/relay/v1/subscriptions" -H "Content-Type: application/json" -d '["/waku/2/rs/3/0"]'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'OK'
[35mDEBUG   [0m src.steps.light_push:light_push.py:121 Lightpushing message
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X POST "http://127.0.0.1:29024/lightpush/v1/message" -H "Content-Type: application/json" -d '{"pubsubTopic": "/waku/2/rs/3/0", "message": {"payload": "TGlnaHQgcHVzaCB3b3JrcyEh", "contentTopic": "/myapp/1/latest/proto", "timestamp": 1738856488044487680}}'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'true'
[35mDEBUG   [0m src.libs.common:common.py:47 Sleeping for 0.1 seconds
[35mDEBUG   [0m src.steps.light_push:light_push.py:125 Checking that peer NODE_1:quay.io/wakuorg/nwaku-pr:3281 can find the lightpushed message
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X GET "http://127.0.0.1:22595/relay/v1/messages/%2Fwaku%2F2%2Frs%2F3%2F0" -H "Content-Type: application/json" -d 'None'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'[{"payload":"TGlnaHQgcHVzaCB3b3JrcyEh","contentTopic":"/myapp/1/latest/proto","version":0,"timestamp":1738856488044487680,"ephemeral":false}]'
[35mDEBUG   [0m src.steps.light_push:light_push.py:125 Checking that peer NODE_2:quay.io/wakuorg/nwaku-pr:3281 can find the lightpushed message
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X GET "http://127.0.0.1:18025/relay/v1/messages/%2Fwaku%2F2%2Frs%2F3%2F0" -H "Content-Type: application/json" -d 'None'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'[{"payload":"TGlnaHQgcHVzaCB3b3JrcyEh","contentTopic":"/myapp/1/latest/proto","version":0,"timestamp":1738856488044487680,"ephemeral":false}]'
[35mDEBUG   [0m tests.conftest:conftest.py:59 Running fixture teardown: test_setup
[35mDEBUG   [0m tests.conftest:conftest.py:83 Running fixture teardown: close_open_nodes
[35mDEBUG   [0m src.node.waku_node:waku_node.py:226 Stopping container with id 499ef2f65791
[35mDEBUG   [0m src.node.waku_node:waku_node.py:233 Container stopped.
[35mDEBUG   [0m src.node.waku_node:waku_node.py:226 Stopping container with id 44837f75ca12
[1m[31mERROR   [0m src.node.docker_mananger:docker_mananger.py:89 Max retries reached for container 499ef2f65791. Exiting log stream.
[35mDEBUG   [0m src.node.waku_node:waku_node.py:233 Container stopped.
[35mDEBUG   [0m src.node.waku_node:waku_node.py:226 Stopping container with id 4f0bdd810c72
[35mDEBUG   [0m src.node.waku_node:waku_node.py:233 Container stopped.
[35mDEBUG   [0m tests.conftest:conftest.py:98 Running fixture teardown: check_waku_log_errors
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:144 No errors found in the waku logs.
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:144 No errors found in the waku logs.
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:144 No errors found in the waku logs.