[35mDEBUG   [0m tests.conftest:conftest.py:43 Running fixture setup: test_id
[35mDEBUG   [0m tests.conftest:conftest.py:49 Running test: test_filter_subscribe_with_no_request_id with id: 2024-04-08_14-16-32__7acfaa0c-2b51-41e0-9e38-af7ad9d6680d
[35mDEBUG   [0m src.steps.filter:filter.py:27 Running fixture setup: filter_setup
[35mDEBUG   [0m src.steps.filter:filter.py:33 Running fixture setup: setup_main_relay_node
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:17 Docker client initialized with image harbor.status.im/wakuorg/nwaku:latest
[35mDEBUG   [0m src.node.waku_node:waku_node.py:50 WakuNode instance initialized with log path ./log/docker/node1_2024-04-08_14-16-32__7acfaa0c-2b51-41e0-9e38-af7ad9d6680d__harbor.status.im_wakuorg_nwaku:latest.log
[35mDEBUG   [0m src.node.waku_node:waku_node.py:54 Starting Node...
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:20 Attempting to create or retrieve network waku
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:23 Network waku already exists
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:80 Generated random external IP 172.18.190.68
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:73 Generated ports ['29394', '29395', '29396', '29397', '29398']
[35mDEBUG   [0m src.node.waku_node:waku_node.py:297 RLN credentials were not set
[32mINFO    [0m src.node.waku_node:waku_node.py:115 RLN credentials not set or credential store not available, starting without RLN
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:47 docker run -i -t -p 29394:29394 -p 29395:29395 -p 29396:29396 -p 29397:29397 -p 29398:29398 harbor.status.im/wakuorg/nwaku:latest --listen-address=0.0.0.0 --rest=true --rest-admin=true --websocket-support=true --log-level=TRACE --rest-relay-cache-capacity=100 --websocket-port=29396 --rest-port=29394 --tcp-port=29395 --discv5-udp-port=29397 --rest-address=0.0.0.0 --nat=extip:172.18.190.68 --peer-exchange=true --discv5-discovery=true --cluster-id=0 --metrics-server=true --metrics-server-address=0.0.0.0 --metrics-server-port=29398 --metrics-logging=true --relay=true --filter=true --nodekey=30348dd51465150e04a5d9d932c72864c8967f806cce60b5d26afeca1e77eb68
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:53 docker network connect --ip 172.18.190.68 waku 8fa53214794a94babee5ab545775bc98a146eb86394150d83d3d8cbd23a5cc45
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:56 Container started with ID 8fa53214794a. Setting up logs at ./log/docker/node1_2024-04-08_14-16-32__7acfaa0c-2b51-41e0-9e38-af7ad9d6680d__harbor.status.im_wakuorg_nwaku:latest.log
[35mDEBUG   [0m src.node.waku_node:waku_node.py:121 Started container from image harbor.status.im/wakuorg/nwaku:latest. REST: 29394
[35mDEBUG   [0m src.libs.common:common.py:35 Sleeping for 1 seconds
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X GET "http://127.0.0.1:29394/debug/v1/info" -H "Content-Type: application/json" -d 'None'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'{"listenAddresses":["/ip4/172.18.190.68/tcp/29395/p2p/16Uiu2HAmGNtM2rQ8abySFNhqPDFY4cmfAEpfo9Z9fD3NekoFR2ip","/ip4/172.18.190.68/tcp/29396/ws/p2p/16Uiu2HAmGNtM2rQ8abySFNhqPDFY4cmfAEpfo9Z9fD3NekoFR2ip"],"enrUri":"enr:-LG4QAr4ySKcrjTRLZVpXMWsmkuUJek1lgb_KUgo9k_ikpCUJhXDr9an_8N44FKC0eShCyiS2h2wllc4Rv-rmyjD6NMBgmlkgnY0gmlwhKwSvkSKbXVsdGlhZGRyc4wACgSsEr5EBnLU3QOCcnODAAAAiXNlY3AyNTZrMaEDN06qX-XhZ-Cc7ZuIAdGNCVUicscmbFvEEfkFOQ2W_j2DdGNwgnLTg3VkcIJy1YV3YWt1MgU"}'
[32mINFO    [0m src.node.waku_node:waku_node.py:191 REST service is ready !!
[35mDEBUG   [0m src.steps.filter:filter.py:38 Running fixture setup: setup_main_filter_node
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:17 Docker client initialized with image harbor.status.im/wakuorg/go-waku:latest
[35mDEBUG   [0m src.node.waku_node:waku_node.py:50 WakuNode instance initialized with log path ./log/docker/node2_2024-04-08_14-16-32__7acfaa0c-2b51-41e0-9e38-af7ad9d6680d__harbor.status.im_wakuorg_go-waku:latest.log
[35mDEBUG   [0m src.node.waku_node:waku_node.py:54 Starting Node...
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:20 Attempting to create or retrieve network waku
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:23 Network waku already exists
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:80 Generated random external IP 172.18.244.234
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:73 Generated ports ['52421', '52422', '52423', '52424', '52425']
[35mDEBUG   [0m src.node.waku_node:waku_node.py:297 RLN credentials were not set
[32mINFO    [0m src.node.waku_node:waku_node.py:115 RLN credentials not set or credential store not available, starting without RLN
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:47 docker run -i -t -p 52421:52421 -p 52422:52422 -p 52423:52423 -p 52424:52424 -p 52425:52425 harbor.status.im/wakuorg/go-waku:latest --listen-address=0.0.0.0 --rest=true --rest-admin=true --websocket-support=true --log-level=DEBUG --rest-relay-cache-capacity=100 --websocket-port=52423 --rest-port=52421 --tcp-port=52422 --discv5-udp-port=52424 --rest-address=0.0.0.0 --nat=extip:172.18.244.234 --peer-exchange=true --discv5-discovery=true --cluster-id=0 --min-relay-peers-to-publish=1 --rest-filter-cache-capacity=50 --relay=false --discv5-bootstrap-node=enr:-LG4QAr4ySKcrjTRLZVpXMWsmkuUJek1lgb_KUgo9k_ikpCUJhXDr9an_8N44FKC0eShCyiS2h2wllc4Rv-rmyjD6NMBgmlkgnY0gmlwhKwSvkSKbXVsdGlhZGRyc4wACgSsEr5EBnLU3QOCcnODAAAAiXNlY3AyNTZrMaEDN06qX-XhZ-Cc7ZuIAdGNCVUicscmbFvEEfkFOQ2W_j2DdGNwgnLTg3VkcIJy1YV3YWt1MgU --filternode=/ip4/172.18.190.68/tcp/29395/p2p/16Uiu2HAmGNtM2rQ8abySFNhqPDFY4cmfAEpfo9Z9fD3NekoFR2ip
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:53 docker network connect --ip 172.18.244.234 waku 25a5e0504050aafaf970635b30c91289fd471082ccc52f2512d4f5a50209c625
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:56 Container started with ID 25a5e0504050. Setting up logs at ./log/docker/node2_2024-04-08_14-16-32__7acfaa0c-2b51-41e0-9e38-af7ad9d6680d__harbor.status.im_wakuorg_go-waku:latest.log
[35mDEBUG   [0m src.node.waku_node:waku_node.py:121 Started container from image harbor.status.im/wakuorg/go-waku:latest. REST: 52421
[35mDEBUG   [0m src.libs.common:common.py:35 Sleeping for 1 seconds
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X GET "http://127.0.0.1:52421/debug/v1/info" -H "Content-Type: application/json" -d 'None'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'{"enrUri":"enr:-Ly4QMDOH7JF4bYU-SsLYfFu9u8YkeBjTT2gT7YQkdEwJwKAGpkknMBdkYeMXrKzQjGamo6GaDjLpi-qU2xixbmI_o6GAY6-EWOPgmlkgnY0gmlwhKwRAAiKbXVsdGlhZGRyc5gACgSsEQAIBszH3QMACgR_AAABBszH3QOJc2VjcDI1NmsxoQK2kVdAN4L5WOFf2tQDZ31YatUHJnTw9dTD7TqX2brxvYN0Y3CCzMaDdWRwgszIhXdha3UygA","listenAddresses":["/ip4/127.0.0.1/tcp/52422/p2p/16Uiu2HAm7iLinDdoaHgaZ8Az4WsphCLUPJaVUrxYV85dzRQVMtNG","/ip4/127.0.0.1/tcp/52423/ws/p2p/16Uiu2HAm7iLinDdoaHgaZ8Az4WsphCLUPJaVUrxYV85dzRQVMtNG","/ip4/172.17.0.8/tcp/52422/p2p/16Uiu2HAm7iLinDdoaHgaZ8Az4WsphCLUPJaVUrxYV85dzRQVMtNG","/ip4/172.17.0.8/tcp/52423/ws/p2p/16Uiu2HAm7iLinDdoaHgaZ8Az4WsphCLUPJaVUrxYV85dzRQVMtNG"]}'
[32mINFO    [0m src.node.waku_node:waku_node.py:191 REST service is ready !!
[35mDEBUG   [0m src.steps.filter:filter.py:47 Running fixture setup: subscribe_main_nodes
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X POST "http://127.0.0.1:29394/relay/v1/subscriptions" -H "Content-Type: application/json" -d '["/waku/2/rs/0/1"]'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'OK'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X POST "http://127.0.0.1:52421/filter/v2/subscriptions" -H "Content-Type: application/json" -d '{"requestId": "d7d947e1-c5a5-4371-a8e2-bc7dcb6a5a7b", "contentFilters": ["/test/1/waku-filter/proto"], "pubsubTopic": "/waku/2/rs/0/1"}'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'{"requestId":"d7d947e1-c5a5-4371-a8e2-bc7dcb6a5a7b","statusDesc":"OK"}'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X POST "http://127.0.0.1:52421/filter/v2/subscriptions" -H "Content-Type: application/json" -d '{"contentFilters": ["/test/1/waku-filter/proto"], "pubsubTopic": "/waku/2/rs/0/1"}'
[1m[31mERROR   [0m src.node.api_clients.base_client:base_client.py:16 HTTP error occurred: 400 Client Error: Bad Request for url: http://127.0.0.1:52421/filter/v2/subscriptions. Response content: b'{"requestId":"","statusDesc":"subscription failed"}'
[35mDEBUG   [0m tests.conftest:conftest.py:51 Running fixture teardown: test_setup
[35mDEBUG   [0m tests.conftest:conftest.py:75 Running fixture teardown: close_open_nodes
[35mDEBUG   [0m src.node.waku_node:waku_node.py:168 Stopping container with id 8fa53214794a
[35mDEBUG   [0m src.node.waku_node:waku_node.py:171 Container stopped.
[35mDEBUG   [0m src.node.waku_node:waku_node.py:168 Stopping container with id 25a5e0504050
[35mDEBUG   [0m src.node.waku_node:waku_node.py:171 Container stopped.