[35mDEBUG   [0m tests.conftest:conftest.py:51 Running fixture setup: test_id
[35mDEBUG   [0m tests.conftest:conftest.py:57 Running test: test_light_push_with_missing_payload with id: 2024-09-24_03-21-30__8be33b41-5769-4d59-8de5-8bb6ad2eceb2
[35mDEBUG   [0m src.steps.common:common.py:17 Running fixture setup: common_setup
[35mDEBUG   [0m src.steps.light_push:light_push.py:27 Running fixture setup: light_push_setup
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:18 Docker client initialized with image wakuorg/nwaku:latest
[35mDEBUG   [0m src.node.waku_node:waku_node.py:85 WakuNode instance initialized with log path ./log/docker/receiving_node1_2024-09-24_03-21-30__8be33b41-5769-4d59-8de5-8bb6ad2eceb2__wakuorg_nwaku:latest.log
[35mDEBUG   [0m src.node.waku_node:waku_node.py:89 Starting Node...
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:21 Attempting to create or retrieve network waku
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:24 Network waku already exists
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:81 Generated random external IP 172.18.133.192
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:74 Generated ports ['36946', '36947', '36948', '36949', '36950']
[35mDEBUG   [0m src.node.waku_node:waku_node.py:434 RLN credentials were not set
[32mINFO    [0m src.node.waku_node:waku_node.py:163 RLN credentials not set or credential store not available, starting without RLN
[35mDEBUG   [0m src.node.waku_node:waku_node.py:165 Using volumes []
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:48 docker run -i -t -p 36946:36946 -p 36947:36947 -p 36948:36948 -p 36949:36949 -p 36950:36950 wakuorg/nwaku:latest --listen-address=0.0.0.0 --rest=true --rest-admin=true --websocket-support=true --log-level=TRACE --rest-relay-cache-capacity=100 --websocket-port=36948 --rest-port=36946 --tcp-port=36947 --discv5-udp-port=36949 --rest-address=0.0.0.0 --nat=extip:172.18.133.192 --peer-exchange=true --discv5-discovery=true --cluster-id=3 --nodekey=a3ddd7eaf484650bfdd8e5d50848af8d52ed4ddafd858de497ba4620a50d8bfb --shard=0 --metrics-server=true --metrics-server-address=0.0.0.0 --metrics-server-port=36950 --metrics-logging=true --lightpush=true --relay=true
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:54 docker network connect --ip 172.18.133.192 waku fe8f6d1c84dbdf2576963c61322f02b2f39c144fa88715cc3fca35f4666f12b5
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:57 Container started with ID fe8f6d1c84db. Setting up logs at ./log/docker/receiving_node1_2024-09-24_03-21-30__8be33b41-5769-4d59-8de5-8bb6ad2eceb2__wakuorg_nwaku:latest.log
[35mDEBUG   [0m src.node.waku_node:waku_node.py:177 Started container from image wakuorg/nwaku:latest. REST: 36946
[35mDEBUG   [0m src.libs.common:common.py:35 Sleeping for 1 seconds
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X GET "http://127.0.0.1:36946/health" -H "Content-Type: application/json" -d 'None'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'{"nodeHealth":"Ready","protocolsHealth":[]}'
[32mINFO    [0m src.node.waku_node:waku_node.py:277 Node protocols are initialized !!
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X GET "http://127.0.0.1:36946/debug/v1/info" -H "Content-Type: application/json" -d 'None'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'{"listenAddresses":["/ip4/172.18.133.192/tcp/36947/p2p/16Uiu2HAm44CNduMG2FE2uMx1fzhyN29bwbVYFcowUMAHBsVkovEj","/ip4/172.18.133.192/tcp/36948/ws/p2p/16Uiu2HAm44CNduMG2FE2uMx1fzhyN29bwbVYFcowUMAHBsVkovEj"],"enrUri":"enr:-LO4QLEA0MaTdw0PZ_pB9NV-UkCaFIehsNGhJeY9I5FxBaYyHUQTbpjbwyNMQHFFjbDIydwXEEL3KNRnJnyd02ox1xsBgmlkgnY0gmlwhKwShcCKbXVsdGlhZGRyc4wACgSsEoXABpBU3QOCcnOFAAMBAACJc2VjcDI1NmsxoQKAOMVe0y-bvVmBYPtH4H7-aJRrr07nPhzWuX5DdyoBcIN0Y3CCkFODdWRwgpBVhXdha3UyCQ"}'
[32mINFO    [0m src.node.waku_node:waku_node.py:282 REST service is ready !!
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:18 Docker client initialized with image wakuorg/nwaku:latest
[35mDEBUG   [0m src.node.waku_node:waku_node.py:85 WakuNode instance initialized with log path ./log/docker/receiving_node2_2024-09-24_03-21-30__8be33b41-5769-4d59-8de5-8bb6ad2eceb2__wakuorg_nwaku:latest.log
[35mDEBUG   [0m src.node.waku_node:waku_node.py:89 Starting Node...
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:21 Attempting to create or retrieve network waku
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:24 Network waku already exists
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:81 Generated random external IP 172.18.135.37
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:74 Generated ports ['7213', '7214', '7215', '7216', '7217']
[35mDEBUG   [0m src.node.waku_node:waku_node.py:434 RLN credentials were not set
[32mINFO    [0m src.node.waku_node:waku_node.py:163 RLN credentials not set or credential store not available, starting without RLN
[35mDEBUG   [0m src.node.waku_node:waku_node.py:165 Using volumes []
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:48 docker run -i -t -p 7213:7213 -p 7214:7214 -p 7215:7215 -p 7216:7216 -p 7217:7217 wakuorg/nwaku:latest --listen-address=0.0.0.0 --rest=true --rest-admin=true --websocket-support=true --log-level=TRACE --rest-relay-cache-capacity=100 --websocket-port=7215 --rest-port=7213 --tcp-port=7214 --discv5-udp-port=7216 --rest-address=0.0.0.0 --nat=extip:172.18.135.37 --peer-exchange=true --discv5-discovery=true --cluster-id=3 --nodekey=ceb78dcdce814dca1b3b0ebc1d5ff77bbadb52b9ac9eeb679aa34f12daf3c65f --shard=0 --metrics-server=true --metrics-server-address=0.0.0.0 --metrics-server-port=7217 --metrics-logging=true --lightpush=false --relay=true
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:54 docker network connect --ip 172.18.135.37 waku 1e694a4012f581b4f6d8155498909ed3eabf6fa038a3ed744db8d1de4eacdafe
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:57 Container started with ID 1e694a4012f5. Setting up logs at ./log/docker/receiving_node2_2024-09-24_03-21-30__8be33b41-5769-4d59-8de5-8bb6ad2eceb2__wakuorg_nwaku:latest.log
[35mDEBUG   [0m src.node.waku_node:waku_node.py:177 Started container from image wakuorg/nwaku:latest. REST: 7213
[35mDEBUG   [0m src.libs.common:common.py:35 Sleeping for 1 seconds
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X GET "http://127.0.0.1:7213/health" -H "Content-Type: application/json" -d 'None'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'{"nodeHealth":"Ready","protocolsHealth":[]}'
[32mINFO    [0m src.node.waku_node:waku_node.py:277 Node protocols are initialized !!
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X GET "http://127.0.0.1:7213/debug/v1/info" -H "Content-Type: application/json" -d 'None'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'{"listenAddresses":["/ip4/172.18.135.37/tcp/7214/p2p/16Uiu2HAmEipNKYP79JaKhRuc9frxczKqPPh1SgCtaMskDAkFZEqB","/ip4/172.18.135.37/tcp/7215/ws/p2p/16Uiu2HAmEipNKYP79JaKhRuc9frxczKqPPh1SgCtaMskDAkFZEqB"],"enrUri":"enr:-LO4QJWObvMyrqzqH745jjJV4BPnqBqPr2TEFNoEMsT0OccbQxwXgAj23eqvouOO1oWOBCIxdIIvbEwg8IuE0Pc8MFIBgmlkgnY0gmlwhKwShyWKbXVsdGlhZGRyc4wACgSsEoclBhwv3QOCcnOFAAMBAACJc2VjcDI1NmsxoQMesmj_PYTdvAhWEj2GYuupfpoNFLhq6jct04pCj4TwvoN0Y3CCHC6DdWRwghwwhXdha3UyAQ"}'
[32mINFO    [0m src.node.waku_node:waku_node.py:282 REST service is ready !!
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X POST "http://127.0.0.1:7213/admin/v1/peers" -H "Content-Type: application/json" -d '["/ip4/172.18.133.192/tcp/36947/p2p/16Uiu2HAm44CNduMG2FE2uMx1fzhyN29bwbVYFcowUMAHBsVkovEj"]'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'OK'
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:18 Docker client initialized with image wakuorg/go-waku:latest
[35mDEBUG   [0m src.node.waku_node:waku_node.py:85 WakuNode instance initialized with log path ./log/docker/lightpush_node1_2024-09-24_03-21-30__8be33b41-5769-4d59-8de5-8bb6ad2eceb2__wakuorg_go-waku:latest.log
[35mDEBUG   [0m src.node.waku_node:waku_node.py:89 Starting Node...
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:21 Attempting to create or retrieve network waku
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:24 Network waku already exists
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:81 Generated random external IP 172.18.201.20
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:74 Generated ports ['32654', '32655', '32656', '32657', '32658']
[35mDEBUG   [0m src.node.waku_node:waku_node.py:434 RLN credentials were not set
[32mINFO    [0m src.node.waku_node:waku_node.py:163 RLN credentials not set or credential store not available, starting without RLN
[35mDEBUG   [0m src.node.waku_node:waku_node.py:165 Using volumes []
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:48 docker run -i -t -p 32654:32654 -p 32655:32655 -p 32656:32656 -p 32657:32657 -p 32658:32658 wakuorg/go-waku:latest --listen-address=0.0.0.0 --rest=true --rest-admin=true --websocket-support=true --log-level=DEBUG --rest-relay-cache-capacity=100 --websocket-port=32656 --rest-port=32654 --tcp-port=32655 --discv5-udp-port=32657 --rest-address=0.0.0.0 --nat=extip:172.18.201.20 --peer-exchange=true --discv5-discovery=true --cluster-id=3 --nodekey=bfcb1af05cdf78ee105746dd09db14feba990d404ba6b6e98e6cb9fc7ba61d27 --min-relay-peers-to-publish=1 --rest-filter-cache-capacity=50 --peer-store-capacity=10 --discv5-bootstrap-node=enr:-LO4QLEA0MaTdw0PZ_pB9NV-UkCaFIehsNGhJeY9I5FxBaYyHUQTbpjbwyNMQHFFjbDIydwXEEL3KNRnJnyd02ox1xsBgmlkgnY0gmlwhKwShcCKbXVsdGlhZGRyc4wACgSsEoXABpBU3QOCcnOFAAMBAACJc2VjcDI1NmsxoQKAOMVe0y-bvVmBYPtH4H7-aJRrr07nPhzWuX5DdyoBcIN0Y3CCkFODdWRwgpBVhXdha3UyCQ --lightpushnode=/ip4/172.18.133.192/tcp/36947/p2p/16Uiu2HAm44CNduMG2FE2uMx1fzhyN29bwbVYFcowUMAHBsVkovEj --lightpush=true --relay=false
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:54 docker network connect --ip 172.18.201.20 waku ef4a7dbb4832ed0ef8c5cf2f0ae0c82437f58690f2b7532f5e5697299646d755
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:57 Container started with ID ef4a7dbb4832. Setting up logs at ./log/docker/lightpush_node1_2024-09-24_03-21-30__8be33b41-5769-4d59-8de5-8bb6ad2eceb2__wakuorg_go-waku:latest.log
[35mDEBUG   [0m src.node.waku_node:waku_node.py:177 Started container from image wakuorg/go-waku:latest. REST: 32654
[35mDEBUG   [0m src.libs.common:common.py:35 Sleeping for 1 seconds
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X GET "http://127.0.0.1:32654/debug/v1/info" -H "Content-Type: application/json" -d 'None'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'{"enrUri":"enr:-Ji4QOXHpVLRZecpTn7vIljEjpdYa7aWTRKS40k0Ffa8eJyHY6KsXo_cJZ939mgdjfJcxXLKGBjtjFuQD0wvF63ZsN6GAZIiDHPYgmlkgnY0gmlwhKwRAAmJc2VjcDI1NmsxoQKTgZ6qqFQEuEnQ2xZTwpza2gW88Ml7vt2HWTRb_P_4bYN0Y3CCf4-DdWRwgn-RhXdha3UyCA","listenAddresses":["/ip4/127.0.0.1/tcp/32655/p2p/16Uiu2HAm5MUYjdizjYXZmbzyDmw63pgiiyE5vRXdjhn9c4RPcevY","/ip4/127.0.0.1/tcp/32656/ws/p2p/16Uiu2HAm5MUYjdizjYXZmbzyDmw63pgiiyE5vRXdjhn9c4RPcevY","/ip4/172.17.0.9/tcp/32655/p2p/16Uiu2HAm5MUYjdizjYXZmbzyDmw63pgiiyE5vRXdjhn9c4RPcevY","/ip4/172.17.0.9/tcp/32656/ws/p2p/16Uiu2HAm5MUYjdizjYXZmbzyDmw63pgiiyE5vRXdjhn9c4RPcevY"]}'
[32mINFO    [0m src.node.waku_node:waku_node.py:282 REST service is ready !!
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X POST "http://127.0.0.1:32654/admin/v1/peers" -H "Content-Type: application/json" -d '{"multiaddr": "/ip4/172.18.133.192/tcp/36947/p2p/16Uiu2HAm44CNduMG2FE2uMx1fzhyN29bwbVYFcowUMAHBsVkovEj", "protocols": ["/vac/waku/relay/2.0.0"], "shards": [0, 1, 2, 3, 4, 5, 6, 7, 8]}'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'null'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X POST "http://127.0.0.1:32654/admin/v1/peers" -H "Content-Type: application/json" -d '{"multiaddr": "/ip4/172.18.135.37/tcp/7214/p2p/16Uiu2HAmEipNKYP79JaKhRuc9frxczKqPPh1SgCtaMskDAkFZEqB", "protocols": ["/vac/waku/relay/2.0.0"], "shards": [0, 1, 2, 3, 4, 5, 6, 7, 8]}'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'null'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X POST "http://127.0.0.1:36946/relay/v1/subscriptions" -H "Content-Type: application/json" -d '["/waku/2/rs/3/0"]'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'OK'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X POST "http://127.0.0.1:7213/relay/v1/subscriptions" -H "Content-Type: application/json" -d '["/waku/2/rs/3/0"]'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'OK'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X POST "http://127.0.0.1:32654/lightpush/v1/message" -H "Content-Type: application/json" -d '{"pubsubTopic": "/waku/2/rs/3/0", "message": {"contentTopic": "/myapp/1/latest/proto", "timestamp": 1727148095500214528}}'
[31m[1mERROR   [0m src.node.api_clients.base_client:base_client.py:16 HTTP error occurred: 503 Server Error: Service Unavailable for url: http://127.0.0.1:32654/lightpush/v1/message. Response content: b'missing Payload field'
[35mDEBUG   [0m tests.conftest:conftest.py:59 Running fixture teardown: test_setup
[35mDEBUG   [0m tests.conftest:conftest.py:83 Running fixture teardown: close_open_nodes
[35mDEBUG   [0m src.node.waku_node:waku_node.py:221 Stopping container with id fe8f6d1c84db
[35mDEBUG   [0m src.node.waku_node:waku_node.py:228 Container stopped.
[35mDEBUG   [0m src.node.waku_node:waku_node.py:221 Stopping container with id 1e694a4012f5
[35mDEBUG   [0m src.node.waku_node:waku_node.py:228 Container stopped.
[35mDEBUG   [0m src.node.waku_node:waku_node.py:221 Stopping container with id ef4a7dbb4832
[35mDEBUG   [0m src.node.waku_node:waku_node.py:228 Container stopped.
[35mDEBUG   [0m tests.conftest:conftest.py:98 Running fixture teardown: check_waku_log_errors
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:117 No errors found in the waku logs.
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:117 No errors found in the waku logs.
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:117 No errors found in the waku logs.