[35mDEBUG   [0m tests.conftest:conftest.py:51 Running fixture setup: test_id
[35mDEBUG   [0m tests.conftest:conftest.py:57 Running test: test_filter_get_message_with_extra_field with id: 2024-07-31_03-12-08__78af1bce-e516-476f-984c-56b50317337c
[35mDEBUG   [0m src.steps.common:common.py:17 Running fixture setup: common_setup
[35mDEBUG   [0m src.steps.filter:filter.py:28 Running fixture setup: filter_setup
[35mDEBUG   [0m src.steps.filter:filter.py:34 Running fixture setup: setup_main_relay_node
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:17 Docker client initialized with image wakuorg/nwaku:latest
[35mDEBUG   [0m src.node.waku_node:waku_node.py:81 WakuNode instance initialized with log path ./log/docker/node1_2024-07-31_03-12-08__78af1bce-e516-476f-984c-56b50317337c__wakuorg_nwaku:latest.log
[35mDEBUG   [0m src.node.waku_node:waku_node.py:85 Starting Node...
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:20 Attempting to create or retrieve network waku
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:23 Network waku already exists
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:80 Generated random external IP 172.18.206.157
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:73 Generated ports ['54247', '54248', '54249', '54250', '54251']
[35mDEBUG   [0m src.node.waku_node:waku_node.py:428 RLN credentials were not set
[32mINFO    [0m src.node.waku_node:waku_node.py:157 RLN credentials not set or credential store not available, starting without RLN
[35mDEBUG   [0m src.node.waku_node:waku_node.py:159 Using volumes []
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:47 docker run -i -t -p 54247:54247 -p 54248:54248 -p 54249:54249 -p 54250:54250 -p 54251:54251 wakuorg/nwaku:latest --listen-address=0.0.0.0 --rest=true --rest-admin=true --websocket-support=true --log-level=TRACE --rest-relay-cache-capacity=100 --websocket-port=54249 --rest-port=54247 --tcp-port=54248 --discv5-udp-port=54250 --rest-address=0.0.0.0 --nat=extip:172.18.206.157 --peer-exchange=true --discv5-discovery=true --cluster-id=3 --shard=0 --metrics-server=true --metrics-server-address=0.0.0.0 --metrics-server-port=54251 --metrics-logging=true --relay=true --filter=true --nodekey=30348dd51465150e04a5d9d932c72864c8967f806cce60b5d26afeca1e77eb68
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:53 docker network connect --ip 172.18.206.157 waku 8c23141897208e1d3e5050b9e98561c0f02cb81472939406b5ab86c06308f24b
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:56 Container started with ID 8c2314189720. Setting up logs at ./log/docker/node1_2024-07-31_03-12-08__78af1bce-e516-476f-984c-56b50317337c__wakuorg_nwaku:latest.log
[35mDEBUG   [0m src.node.waku_node:waku_node.py:171 Started container from image wakuorg/nwaku:latest. REST: 54247
[35mDEBUG   [0m src.libs.common:common.py:35 Sleeping for 1 seconds
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X GET "http://127.0.0.1:54247/health" -H "Content-Type: application/json" -d 'None'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'{"nodeHealth":"Ready","protocolsHealth":[]}'
[32mINFO    [0m src.node.waku_node:waku_node.py:274 Node protocols are initialized !!
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X GET "http://127.0.0.1:54247/debug/v1/info" -H "Content-Type: application/json" -d 'None'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'{"listenAddresses":["/ip4/172.18.206.157/tcp/54248/p2p/16Uiu2HAmGNtM2rQ8abySFNhqPDFY4cmfAEpfo9Z9fD3NekoFR2ip","/ip4/172.18.206.157/tcp/54249/ws/p2p/16Uiu2HAmGNtM2rQ8abySFNhqPDFY4cmfAEpfo9Z9fD3NekoFR2ip"],"enrUri":"enr:-LO4QIHsqaHHJI0zCTzxsGGdr9KsQKEXLEizHbx_2GuEkIAweRv_UZbxnkM1Lvopd5TGZ1pBLkaZ4F1V1nAITrnuX8oBgmlkgnY0gmlwhKwSzp2KbXVsdGlhZGRyc4wACgSsEs6dBtPp3QOCcnOFAAMBAACJc2VjcDI1NmsxoQM3Tqpf5eFn4Jztm4gB0Y0JVSJyxyZsW8QR-QU5DZb-PYN0Y3CC0-iDdWRwgtPqhXdha3UyBQ"}'
[32mINFO    [0m src.node.waku_node:waku_node.py:279 REST service is ready !!
[35mDEBUG   [0m src.steps.filter:filter.py:39 Running fixture setup: setup_main_filter_node
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:17 Docker client initialized with image wakuorg/go-waku:latest
[35mDEBUG   [0m src.node.waku_node:waku_node.py:81 WakuNode instance initialized with log path ./log/docker/node2_2024-07-31_03-12-08__78af1bce-e516-476f-984c-56b50317337c__wakuorg_go-waku:latest.log
[35mDEBUG   [0m src.node.waku_node:waku_node.py:85 Starting Node...
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:20 Attempting to create or retrieve network waku
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:23 Network waku already exists
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:80 Generated random external IP 172.18.10.129
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:73 Generated ports ['39020', '39021', '39022', '39023', '39024']
[35mDEBUG   [0m src.node.waku_node:waku_node.py:428 RLN credentials were not set
[32mINFO    [0m src.node.waku_node:waku_node.py:157 RLN credentials not set or credential store not available, starting without RLN
[35mDEBUG   [0m src.node.waku_node:waku_node.py:159 Using volumes []
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:47 docker run -i -t -p 39020:39020 -p 39021:39021 -p 39022:39022 -p 39023:39023 -p 39024:39024 wakuorg/go-waku:latest --listen-address=0.0.0.0 --rest=true --rest-admin=true --websocket-support=true --log-level=DEBUG --rest-relay-cache-capacity=100 --websocket-port=39022 --rest-port=39020 --tcp-port=39021 --discv5-udp-port=39023 --rest-address=0.0.0.0 --nat=extip:172.18.10.129 --peer-exchange=true --discv5-discovery=true --cluster-id=3 --min-relay-peers-to-publish=1 --rest-filter-cache-capacity=50 --peer-store-capacity=10 --relay=false --discv5-bootstrap-node=enr:-LO4QIHsqaHHJI0zCTzxsGGdr9KsQKEXLEizHbx_2GuEkIAweRv_UZbxnkM1Lvopd5TGZ1pBLkaZ4F1V1nAITrnuX8oBgmlkgnY0gmlwhKwSzp2KbXVsdGlhZGRyc4wACgSsEs6dBtPp3QOCcnOFAAMBAACJc2VjcDI1NmsxoQM3Tqpf5eFn4Jztm4gB0Y0JVSJyxyZsW8QR-QU5DZb-PYN0Y3CC0-iDdWRwgtPqhXdha3UyBQ --filternode=/ip4/172.18.206.157/tcp/54248/p2p/16Uiu2HAmGNtM2rQ8abySFNhqPDFY4cmfAEpfo9Z9fD3NekoFR2ip
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:53 docker network connect --ip 172.18.10.129 waku b2e8a45e96b4b1ca4ee642b3f3f56d21542655bd3ae1172d86824b918347b6a9
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:56 Container started with ID b2e8a45e96b4. Setting up logs at ./log/docker/node2_2024-07-31_03-12-08__78af1bce-e516-476f-984c-56b50317337c__wakuorg_go-waku:latest.log
[35mDEBUG   [0m src.node.waku_node:waku_node.py:171 Started container from image wakuorg/go-waku:latest. REST: 39020
[35mDEBUG   [0m src.libs.common:common.py:35 Sleeping for 1 seconds
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X GET "http://127.0.0.1:39020/debug/v1/info" -H "Content-Type: application/json" -d 'None'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'{"enrUri":"enr:-Ji4QMlSfoHCbLVLR-CMem4Z9mvH24soGzu8YI4cuA8GWvTXb3BuDmqzpJrrKP8TmUDnn3RsoY6L8OVuaFdyUuANtsSGAZEGxhgWgmlkgnY0gmlwhKwRAASJc2VjcDI1NmsxoQOS_vumBAFmXPuQDcJV6TmqQSkHUI7RzpAAIBBJ_4q-xYN0Y3CCmG2DdWRwgphvhXdha3UygA","listenAddresses":["/ip4/127.0.0.1/tcp/39021/p2p/16Uiu2HAmNYoP9rsF3NdyDGHEuRQj8ECsWyGjCXTWyKhj87Zp1JLc","/ip4/127.0.0.1/tcp/39022/ws/p2p/16Uiu2HAmNYoP9rsF3NdyDGHEuRQj8ECsWyGjCXTWyKhj87Zp1JLc","/ip4/172.17.0.4/tcp/39021/p2p/16Uiu2HAmNYoP9rsF3NdyDGHEuRQj8ECsWyGjCXTWyKhj87Zp1JLc","/ip4/172.17.0.4/tcp/39022/ws/p2p/16Uiu2HAmNYoP9rsF3NdyDGHEuRQj8ECsWyGjCXTWyKhj87Zp1JLc"]}'
[32mINFO    [0m src.node.waku_node:waku_node.py:279 REST service is ready !!
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X POST "http://127.0.0.1:39020/admin/v1/peers" -H "Content-Type: application/json" -d '{"multiaddr": "/ip4/172.18.206.157/tcp/54248/p2p/16Uiu2HAmGNtM2rQ8abySFNhqPDFY4cmfAEpfo9Z9fD3NekoFR2ip", "protocols": ["/vac/waku/relay/2.0.0"], "shards": [0, 1, 2, 3, 4, 5, 6, 7, 8]}'
[1m[31mERROR   [0m src.node.api_clients.base_client:base_client.py:16 HTTP error occurred: 500 Server Error: Internal Server Error for url: http://127.0.0.1:39020/admin/v1/peers. Response content: b''
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X POST "http://127.0.0.1:39020/admin/v1/peers" -H "Content-Type: application/json" -d '{"multiaddr": "/ip4/172.18.206.157/tcp/54248/p2p/16Uiu2HAmGNtM2rQ8abySFNhqPDFY4cmfAEpfo9Z9fD3NekoFR2ip", "protocols": ["/vac/waku/relay/2.0.0"], "shards": [0, 1, 2, 3, 4, 5, 6, 7, 8]}'
[1m[31mERROR   [0m src.node.api_clients.base_client:base_client.py:16 HTTP error occurred: 500 Server Error: Internal Server Error for url: http://127.0.0.1:39020/admin/v1/peers. Response content: b''
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X POST "http://127.0.0.1:39020/admin/v1/peers" -H "Content-Type: application/json" -d '{"multiaddr": "/ip4/172.18.206.157/tcp/54248/p2p/16Uiu2HAmGNtM2rQ8abySFNhqPDFY4cmfAEpfo9Z9fD3NekoFR2ip", "protocols": ["/vac/waku/relay/2.0.0"], "shards": [0, 1, 2, 3, 4, 5, 6, 7, 8]}'
[1m[31mERROR   [0m src.node.api_clients.base_client:base_client.py:16 HTTP error occurred: 500 Server Error: Internal Server Error for url: http://127.0.0.1:39020/admin/v1/peers. Response content: b''
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X POST "http://127.0.0.1:39020/admin/v1/peers" -H "Content-Type: application/json" -d '{"multiaddr": "/ip4/172.18.206.157/tcp/54248/p2p/16Uiu2HAmGNtM2rQ8abySFNhqPDFY4cmfAEpfo9Z9fD3NekoFR2ip", "protocols": ["/vac/waku/relay/2.0.0"], "shards": [0, 1, 2, 3, 4, 5, 6, 7, 8]}'
[1m[31mERROR   [0m src.node.api_clients.base_client:base_client.py:16 HTTP error occurred: 500 Server Error: Internal Server Error for url: http://127.0.0.1:39020/admin/v1/peers. Response content: b''
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X POST "http://127.0.0.1:39020/admin/v1/peers" -H "Content-Type: application/json" -d '{"multiaddr": "/ip4/172.18.206.157/tcp/54248/p2p/16Uiu2HAmGNtM2rQ8abySFNhqPDFY4cmfAEpfo9Z9fD3NekoFR2ip", "protocols": ["/vac/waku/relay/2.0.0"], "shards": [0, 1, 2, 3, 4, 5, 6, 7, 8]}'
[1m[31mERROR   [0m src.node.api_clients.base_client:base_client.py:16 HTTP error occurred: 500 Server Error: Internal Server Error for url: http://127.0.0.1:39020/admin/v1/peers. Response content: b''
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X POST "http://127.0.0.1:39020/admin/v1/peers" -H "Content-Type: application/json" -d '{"multiaddr": "/ip4/172.18.206.157/tcp/54248/p2p/16Uiu2HAmGNtM2rQ8abySFNhqPDFY4cmfAEpfo9Z9fD3NekoFR2ip", "protocols": ["/vac/waku/relay/2.0.0"], "shards": [0, 1, 2, 3, 4, 5, 6, 7, 8]}'
[1m[31mERROR   [0m src.node.api_clients.base_client:base_client.py:16 HTTP error occurred: 500 Server Error: Internal Server Error for url: http://127.0.0.1:39020/admin/v1/peers. Response content: b''
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X POST "http://127.0.0.1:39020/admin/v1/peers" -H "Content-Type: application/json" -d '{"multiaddr": "/ip4/172.18.206.157/tcp/54248/p2p/16Uiu2HAmGNtM2rQ8abySFNhqPDFY4cmfAEpfo9Z9fD3NekoFR2ip", "protocols": ["/vac/waku/relay/2.0.0"], "shards": [0, 1, 2, 3, 4, 5, 6, 7, 8]}'
[1m[31mERROR   [0m src.node.api_clients.base_client:base_client.py:16 HTTP error occurred: 500 Server Error: Internal Server Error for url: http://127.0.0.1:39020/admin/v1/peers. Response content: b''
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X POST "http://127.0.0.1:39020/admin/v1/peers" -H "Content-Type: application/json" -d '{"multiaddr": "/ip4/172.18.206.157/tcp/54248/p2p/16Uiu2HAmGNtM2rQ8abySFNhqPDFY4cmfAEpfo9Z9fD3NekoFR2ip", "protocols": ["/vac/waku/relay/2.0.0"], "shards": [0, 1, 2, 3, 4, 5, 6, 7, 8]}'
[1m[31mERROR   [0m src.node.api_clients.base_client:base_client.py:16 HTTP error occurred: 500 Server Error: Internal Server Error for url: http://127.0.0.1:39020/admin/v1/peers. Response content: b''
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X POST "http://127.0.0.1:39020/admin/v1/peers" -H "Content-Type: application/json" -d '{"multiaddr": "/ip4/172.18.206.157/tcp/54248/p2p/16Uiu2HAmGNtM2rQ8abySFNhqPDFY4cmfAEpfo9Z9fD3NekoFR2ip", "protocols": ["/vac/waku/relay/2.0.0"], "shards": [0, 1, 2, 3, 4, 5, 6, 7, 8]}'
[1m[31mERROR   [0m src.node.api_clients.base_client:base_client.py:16 HTTP error occurred: 500 Server Error: Internal Server Error for url: http://127.0.0.1:39020/admin/v1/peers. Response content: b''
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X POST "http://127.0.0.1:39020/admin/v1/peers" -H "Content-Type: application/json" -d '{"multiaddr": "/ip4/172.18.206.157/tcp/54248/p2p/16Uiu2HAmGNtM2rQ8abySFNhqPDFY4cmfAEpfo9Z9fD3NekoFR2ip", "protocols": ["/vac/waku/relay/2.0.0"], "shards": [0, 1, 2, 3, 4, 5, 6, 7, 8]}'
[1m[31mERROR   [0m src.node.api_clients.base_client:base_client.py:16 HTTP error occurred: 500 Server Error: Internal Server Error for url: http://127.0.0.1:39020/admin/v1/peers. Response content: b''
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X POST "http://127.0.0.1:39020/admin/v1/peers" -H "Content-Type: application/json" -d '{"multiaddr": "/ip4/172.18.206.157/tcp/54248/p2p/16Uiu2HAmGNtM2rQ8abySFNhqPDFY4cmfAEpfo9Z9fD3NekoFR2ip", "protocols": ["/vac/waku/relay/2.0.0"], "shards": [0, 1, 2, 3, 4, 5, 6, 7, 8]}'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'null'
[35mDEBUG   [0m src.steps.filter:filter.py:47 Running fixture setup: subscribe_main_nodes
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X POST "http://127.0.0.1:54247/relay/v1/subscriptions" -H "Content-Type: application/json" -d '["/waku/2/rs/3/1"]'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'OK'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X POST "http://127.0.0.1:39020/filter/v2/subscriptions" -H "Content-Type: application/json" -d '{"requestId": "8ee75934-700e-48c4-a0ec-a446de155463", "contentFilters": ["/test/1/waku-filter/proto"], "pubsubTopic": "/waku/2/rs/3/1"}'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'{"requestId":"8ee75934-700e-48c4-a0ec-a446de155463","statusDesc":"OK"}'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X POST "http://127.0.0.1:54247/relay/v1/messages/%2Fwaku%2F2%2Frs%2F3%2F1" -H "Content-Type: application/json" -d '{"payload": "RmlsdGVyIHdvcmtzISE=", "contentTopic": "/test/1/waku-filter/proto", "timestamp": '$(date +%s%N)', "extraField": "extraValue"}'
[1m[31mERROR   [0m src.node.api_clients.base_client:base_client.py:16 HTTP error occurred: 400 Client Error: Bad Request for url: http://127.0.0.1:54247/relay/v1/messages/%2Fwaku%2F2%2Frs%2F3%2F1. Response content: b'Invalid content body, could not decode. Unable to deserialize data'
[35mDEBUG   [0m tests.conftest:conftest.py:59 Running fixture teardown: test_setup
[35mDEBUG   [0m tests.conftest:conftest.py:83 Running fixture teardown: close_open_nodes
[35mDEBUG   [0m src.node.waku_node:waku_node.py:218 Stopping container with id 8c2314189720
[35mDEBUG   [0m src.node.waku_node:waku_node.py:225 Container stopped.
[35mDEBUG   [0m src.node.waku_node:waku_node.py:218 Stopping container with id b2e8a45e96b4
[35mDEBUG   [0m src.node.waku_node:waku_node.py:225 Container stopped.