[35mDEBUG   [0m tests.conftest:conftest.py:51 Running fixture setup: test_id
[35mDEBUG   [0m tests.conftest:conftest.py:57 Running test: test_filter_update_subscription_with_no_content_topic with id: 2024-12-17_03-21-59__32dd5f9c-d5fc-4092-92c8-133884fd1726
[35mDEBUG   [0m src.steps.common:common.py:18 Running fixture setup: common_setup
[35mDEBUG   [0m src.steps.filter:filter.py:28 Running fixture setup: filter_setup
[35mDEBUG   [0m src.steps.filter:filter.py:34 Running fixture setup: setup_main_relay_node
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:19 Docker client initialized with image wakuorg/nwaku:latest
[35mDEBUG   [0m src.node.waku_node:waku_node.py:85 WakuNode instance initialized with log path ./log/docker/node1_2024-12-17_03-21-59__32dd5f9c-d5fc-4092-92c8-133884fd1726__wakuorg_nwaku:latest.log
[35mDEBUG   [0m src.node.waku_node:waku_node.py:89 Starting Node...
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:22 Attempting to create or retrieve network waku
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:25 Network waku already exists
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:108 Generated random external IP 172.18.28.185
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:101 Generated ports ['5903', '5904', '5905', '5906', '5907']
[35mDEBUG   [0m src.node.waku_node:waku_node.py:439 RLN credentials were not set
[32mINFO    [0m src.node.waku_node:waku_node.py:168 RLN credentials not set or credential store not available, starting without RLN
[35mDEBUG   [0m src.node.waku_node:waku_node.py:170 Using volumes []
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:49 docker run -i -t -p 5903:5903 -p 5904:5904 -p 5905:5905 -p 5906:5906 -p 5907:5907 wakuorg/nwaku:latest --listen-address=0.0.0.0 --rest=true --rest-admin=true --websocket-support=true --log-level=TRACE --rest-relay-cache-capacity=100 --websocket-port=5905 --rest-port=5903 --tcp-port=5904 --discv5-udp-port=5906 --rest-address=0.0.0.0 --nat=extip:172.18.28.185 --peer-exchange=true --discv5-discovery=true --cluster-id=3 --nodekey=d0facb19fa140ca5cecdfcae11b708ff4fe36d392e82d76f52421ff072d2ee16 --shard=0 --metrics-server=true --metrics-server-address=0.0.0.0 --metrics-server-port=5907 --metrics-logging=true --relay=true --filter=true
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:55 docker network connect --ip 172.18.28.185 waku 0058ff91bcef51b0a8ed3ee2061851dd9ade6e272475a2fcbd6681c87ed399bd
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:58 Container started with ID 0058ff91bcef. Setting up logs at ./log/docker/node1_2024-12-17_03-21-59__32dd5f9c-d5fc-4092-92c8-133884fd1726__wakuorg_nwaku:latest.log
[35mDEBUG   [0m src.node.waku_node:waku_node.py:182 Started container from image wakuorg/nwaku:latest. REST: 5903
[35mDEBUG   [0m src.libs.common:common.py:35 Sleeping for 1 seconds
[31m[1mERROR   [0m src.node.docker_mananger:docker_mananger.py:89 Max retries reached for container 517c9ac65a7a. Exiting log stream.
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X GET "http://127.0.0.1:5903/health" -H "Content-Type: application/json" -d 'None'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'{"nodeHealth":"Ready","protocolsHealth":[]}'
[32mINFO    [0m src.node.waku_node:waku_node.py:282 Node protocols are initialized !!
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X GET "http://127.0.0.1:5903/debug/v1/info" -H "Content-Type: application/json" -d 'None'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'{"listenAddresses":["/ip4/172.18.28.185/tcp/5904/p2p/16Uiu2HAmJnzGTVZ9XpBhNnCKkWq7xytthK1gE9HzmxvtsbhG37UE","/ip4/172.18.28.185/tcp/5905/ws/p2p/16Uiu2HAmJnzGTVZ9XpBhNnCKkWq7xytthK1gE9HzmxvtsbhG37UE"],"enrUri":"enr:-L24QMqWOOsgYzvnwRZCKnAStJ9bjwu40gBhpaIoEE9K0kCoPuHEoSbGuum9cgoIIBt1tH_NFXK45-x28wNPKimnd6gCgmlkgnY0gmlwhKwSHLmKbXVsdGlhZGRyc5YACASsEhy5BhcQAAoErBIcuQYXEd0DgnJzhQADAQAAiXNlY3AyNTZrMaEDWzKsf9ZjvowPQnWwECHZ3YYbLJV41P_aLMJzuKBrsMODdGNwghcQg3VkcIIXEoV3YWt1MgU"}'
[32mINFO    [0m src.node.waku_node:waku_node.py:287 REST service is ready !!
[35mDEBUG   [0m src.steps.filter:filter.py:39 Running fixture setup: setup_main_filter_node
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:19 Docker client initialized with image wakuorg/go-waku:latest
[35mDEBUG   [0m src.node.waku_node:waku_node.py:85 WakuNode instance initialized with log path ./log/docker/node2_2024-12-17_03-21-59__32dd5f9c-d5fc-4092-92c8-133884fd1726__wakuorg_go-waku:latest.log
[35mDEBUG   [0m src.node.waku_node:waku_node.py:89 Starting Node...
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:22 Attempting to create or retrieve network waku
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:25 Network waku already exists
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:108 Generated random external IP 172.18.40.149
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:101 Generated ports ['18596', '18597', '18598', '18599', '18600']
[35mDEBUG   [0m src.node.waku_node:waku_node.py:439 RLN credentials were not set
[32mINFO    [0m src.node.waku_node:waku_node.py:168 RLN credentials not set or credential store not available, starting without RLN
[35mDEBUG   [0m src.node.waku_node:waku_node.py:170 Using volumes []
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:49 docker run -i -t -p 18596:18596 -p 18597:18597 -p 18598:18598 -p 18599:18599 -p 18600:18600 wakuorg/go-waku:latest --listen-address=0.0.0.0 --rest=true --rest-admin=true --websocket-support=true --log-level=DEBUG --rest-relay-cache-capacity=100 --websocket-port=18598 --rest-port=18596 --tcp-port=18597 --discv5-udp-port=18599 --rest-address=0.0.0.0 --nat=extip:172.18.40.149 --peer-exchange=true --discv5-discovery=true --cluster-id=3 --nodekey=1480e6ab9eff335308f12b5e3cc2ced761c1c32f304af62c3afb120efc218056 --min-relay-peers-to-publish=1 --rest-filter-cache-capacity=50 --peer-store-capacity=10 --relay=false --discv5-bootstrap-node=enr:-L24QMqWOOsgYzvnwRZCKnAStJ9bjwu40gBhpaIoEE9K0kCoPuHEoSbGuum9cgoIIBt1tH_NFXK45-x28wNPKimnd6gCgmlkgnY0gmlwhKwSHLmKbXVsdGlhZGRyc5YACASsEhy5BhcQAAoErBIcuQYXEd0DgnJzhQADAQAAiXNlY3AyNTZrMaEDWzKsf9ZjvowPQnWwECHZ3YYbLJV41P_aLMJzuKBrsMODdGNwghcQg3VkcIIXEoV3YWt1MgU --filternode=/ip4/172.18.28.185/tcp/5904/p2p/16Uiu2HAmJnzGTVZ9XpBhNnCKkWq7xytthK1gE9HzmxvtsbhG37UE --pubsub-topic=/waku/2/rs/3/1
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:55 docker network connect --ip 172.18.40.149 waku 3cdda078285f4076ead4d54de2679bb5d677b61832d38d8f18f1f5b23e91d981
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:58 Container started with ID 3cdda078285f. Setting up logs at ./log/docker/node2_2024-12-17_03-21-59__32dd5f9c-d5fc-4092-92c8-133884fd1726__wakuorg_go-waku:latest.log
[35mDEBUG   [0m src.node.waku_node:waku_node.py:182 Started container from image wakuorg/go-waku:latest. REST: 18596
[35mDEBUG   [0m src.libs.common:common.py:35 Sleeping for 1 seconds
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X GET "http://127.0.0.1:18596/debug/v1/info" -H "Content-Type: application/json" -d 'None'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'{"enrUri":"enr:-KG4QIvqLeqDG7YUbGYjikzC_fqs_6vRfYM7D8vmQzjwYM08PM641wo40xJeZJ_cB7c-x_H8Z91aAVC-d1ZwyQKxfUKGAZPSow9igmlkgnY0gmlwhKwRAAOCcnOFAAMBAAGJc2VjcDI1NmsxoQIVB3gJhN_89EVf0ym83tITgIw3IReggvv1XDG8EW5saYN0Y3CCSKWDdWRwgkinhXdha3UygA","listenAddresses":["/ip4/127.0.0.1/tcp/18597/p2p/16Uiu2HAkvqm9VNpf6Ubcywa9E9UcZbpNGBRgDmRbBGUuEGTEsXTn","/ip4/127.0.0.1/tcp/18598/ws/p2p/16Uiu2HAkvqm9VNpf6Ubcywa9E9UcZbpNGBRgDmRbBGUuEGTEsXTn","/ip4/172.17.0.3/tcp/18597/p2p/16Uiu2HAkvqm9VNpf6Ubcywa9E9UcZbpNGBRgDmRbBGUuEGTEsXTn","/ip4/172.17.0.3/tcp/18598/ws/p2p/16Uiu2HAkvqm9VNpf6Ubcywa9E9UcZbpNGBRgDmRbBGUuEGTEsXTn"]}'
[32mINFO    [0m src.node.waku_node:waku_node.py:287 REST service is ready !!
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X POST "http://127.0.0.1:18596/admin/v1/peers" -H "Content-Type: application/json" -d '{"multiaddr": "/ip4/172.18.28.185/tcp/5904/p2p/16Uiu2HAmJnzGTVZ9XpBhNnCKkWq7xytthK1gE9HzmxvtsbhG37UE", "protocols": ["/vac/waku/relay/2.0.0"], "shards": [0, 1, 2, 3, 4, 5, 6, 7, 8]}'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'null'
[35mDEBUG   [0m src.steps.filter:filter.py:47 Running fixture setup: subscribe_main_nodes
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X POST "http://127.0.0.1:5903/relay/v1/subscriptions" -H "Content-Type: application/json" -d '["/waku/2/rs/3/1"]'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'OK'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X POST "http://127.0.0.1:18596/filter/v2/subscriptions" -H "Content-Type: application/json" -d '{"requestId": "817de050-2e5f-4aeb-bd02-80d1950d27f8", "contentFilters": ["/test/1/waku-filter/proto"], "pubsubTopic": "/waku/2/rs/3/1"}'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'{"requestId":"817de050-2e5f-4aeb-bd02-80d1950d27f8","statusDesc":"OK"}'
[35mDEBUG   [0m tests.conftest:conftest.py:59 Running fixture teardown: test_setup
[35mDEBUG   [0m tests.conftest:conftest.py:83 Running fixture teardown: close_open_nodes
[35mDEBUG   [0m src.node.waku_node:waku_node.py:226 Stopping container with id 0058ff91bcef
[35mDEBUG   [0m src.node.waku_node:waku_node.py:233 Container stopped.
[35mDEBUG   [0m src.node.waku_node:waku_node.py:226 Stopping container with id 3cdda078285f
[35mDEBUG   [0m src.node.waku_node:waku_node.py:233 Container stopped.
[35mDEBUG   [0m tests.conftest:conftest.py:98 Running fixture teardown: check_waku_log_errors
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:144 No errors found in the waku logs.
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:144 No errors found in the waku logs.