[35mDEBUG   [0m tests.conftest:conftest.py:43 Running fixture setup: test_id
[35mDEBUG   [0m tests.conftest:conftest.py:49 Running test: test_filter_get_message_with_150_kb_payload with id: 2024-03-25_11-09-12__b2269629-27f4-41ba-b2c1-27807d4c27a4
[35mDEBUG   [0m src.steps.filter:filter.py:27 Running fixture setup: filter_setup
[35mDEBUG   [0m src.steps.filter:filter.py:33 Running fixture setup: setup_main_relay_node
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:17 Docker client initialized with image harbor.status.im/wakuorg/nwaku:latest
[35mDEBUG   [0m src.node.waku_node:waku_node.py:50 WakuNode instance initialized with log path ./log/docker/node1_2024-03-25_11-09-12__b2269629-27f4-41ba-b2c1-27807d4c27a4__harbor.status.im_wakuorg_nwaku:latest.log
[35mDEBUG   [0m src.node.waku_node:waku_node.py:54 Starting Node...
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:20 Attempting to create or retrieve network waku
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:23 Network waku already exists
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:80 Generated random external IP 172.18.247.17
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:73 Generated ports ['65161', '65162', '65163', '65164', '65165']
[35mDEBUG   [0m src.node.waku_node:waku_node.py:279 RLN credentials were not set
[32mINFO    [0m src.node.waku_node:waku_node.py:115 RLN credentials not set or credential store not available, starting without RLN
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:47 docker run -i -t -p 65161:65161 -p 65162:65162 -p 65163:65163 -p 65164:65164 -p 65165:65165 harbor.status.im/wakuorg/nwaku:latest --listen-address=0.0.0.0 --rest=true --rest-admin=true --websocket-support=true --log-level=TRACE --rest-relay-cache-capacity=100 --websocket-port=65163 --rest-port=65161 --tcp-port=65162 --discv5-udp-port=65164 --rest-address=0.0.0.0 --nat=extip:172.18.247.17 --peer-exchange=true --discv5-discovery=true --cluster-id=0 --metrics-server=true --metrics-server-address=0.0.0.0 --metrics-server-port=65165 --metrics-logging=true --relay=true --filter=true --nodekey=30348dd51465150e04a5d9d932c72864c8967f806cce60b5d26afeca1e77eb68
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:53 docker network connect --ip 172.18.247.17 waku 1f3fb9ab15ed25f410e446afe76d8492be2299b4f47f8c45d56c0e04ecef1b05
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:56 Container started with ID 1f3fb9ab15ed. Setting up logs at ./log/docker/node1_2024-03-25_11-09-12__b2269629-27f4-41ba-b2c1-27807d4c27a4__harbor.status.im_wakuorg_nwaku:latest.log
[35mDEBUG   [0m src.node.waku_node:waku_node.py:121 Started container from image harbor.status.im/wakuorg/nwaku:latest. REST: 65161
[35mDEBUG   [0m src.libs.common:common.py:35 Sleeping for 1 seconds
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:38 curl -v -X GET "http://127.0.0.1:65161/debug/v1/info" -H "Content-Type: application/json" -d 'None'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:23 Response status code: 200. Response content: b'{"listenAddresses":["/ip4/172.18.247.17/tcp/65162/p2p/16Uiu2HAmGNtM2rQ8abySFNhqPDFY4cmfAEpfo9Z9fD3NekoFR2ip","/ip4/172.18.247.17/tcp/65163/ws/p2p/16Uiu2HAmGNtM2rQ8abySFNhqPDFY4cmfAEpfo9Z9fD3NekoFR2ip"],"enrUri":"enr:-LO4QAZor0OQvaWNt3gMGt7EqpiW9an5ZMHZCR6GgSBoRgPEICSgDOvcKqdYSTg6HdrT_SFLvO2djK1fgAcXQ8GFva0BgmlkgnY0gmlwhKwS9xGKbXVsdGlhZGRyc4wACgSsEvcRBv6L3QOCcnOFAAABAACJc2VjcDI1NmsxoQM3Tqpf5eFn4Jztm4gB0Y0JVSJyxyZsW8QR-QU5DZb-PYN0Y3CC_oqDdWRwgv6MhXdha3UyBQ"}'
[32mINFO    [0m src.node.waku_node:waku_node.py:191 REST service is ready !!
[35mDEBUG   [0m src.steps.filter:filter.py:38 Running fixture setup: setup_main_filter_node
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:17 Docker client initialized with image harbor.status.im/wakuorg/nwaku:latest
[35mDEBUG   [0m src.node.waku_node:waku_node.py:50 WakuNode instance initialized with log path ./log/docker/node2_2024-03-25_11-09-12__b2269629-27f4-41ba-b2c1-27807d4c27a4__harbor.status.im_wakuorg_nwaku:latest.log
[35mDEBUG   [0m src.node.waku_node:waku_node.py:54 Starting Node...
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:20 Attempting to create or retrieve network waku
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:23 Network waku already exists
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:80 Generated random external IP 172.18.227.143
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:73 Generated ports ['63881', '63882', '63883', '63884', '63885']
[35mDEBUG   [0m src.node.waku_node:waku_node.py:279 RLN credentials were not set
[32mINFO    [0m src.node.waku_node:waku_node.py:115 RLN credentials not set or credential store not available, starting without RLN
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:47 docker run -i -t -p 63881:63881 -p 63882:63882 -p 63883:63883 -p 63884:63884 -p 63885:63885 harbor.status.im/wakuorg/nwaku:latest --listen-address=0.0.0.0 --rest=true --rest-admin=true --websocket-support=true --log-level=TRACE --rest-relay-cache-capacity=100 --websocket-port=63883 --rest-port=63881 --tcp-port=63882 --discv5-udp-port=63884 --rest-address=0.0.0.0 --nat=extip:172.18.227.143 --peer-exchange=true --discv5-discovery=true --cluster-id=0 --metrics-server=true --metrics-server-address=0.0.0.0 --metrics-server-port=63885 --metrics-logging=true --relay=false --discv5-bootstrap-node=enr:-LO4QAZor0OQvaWNt3gMGt7EqpiW9an5ZMHZCR6GgSBoRgPEICSgDOvcKqdYSTg6HdrT_SFLvO2djK1fgAcXQ8GFva0BgmlkgnY0gmlwhKwS9xGKbXVsdGlhZGRyc4wACgSsEvcRBv6L3QOCcnOFAAABAACJc2VjcDI1NmsxoQM3Tqpf5eFn4Jztm4gB0Y0JVSJyxyZsW8QR-QU5DZb-PYN0Y3CC_oqDdWRwgv6MhXdha3UyBQ --filternode=/ip4/172.18.247.17/tcp/65162/p2p/16Uiu2HAmGNtM2rQ8abySFNhqPDFY4cmfAEpfo9Z9fD3NekoFR2ip
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:53 docker network connect --ip 172.18.227.143 waku 804b9d56db1066c9c5a538005d477dee03e0493323dc950275803e8380f06021
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:56 Container started with ID 804b9d56db10. Setting up logs at ./log/docker/node2_2024-03-25_11-09-12__b2269629-27f4-41ba-b2c1-27807d4c27a4__harbor.status.im_wakuorg_nwaku:latest.log
[35mDEBUG   [0m src.node.waku_node:waku_node.py:121 Started container from image harbor.status.im/wakuorg/nwaku:latest. REST: 63881
[35mDEBUG   [0m src.libs.common:common.py:35 Sleeping for 1 seconds
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:38 curl -v -X GET "http://127.0.0.1:63881/debug/v1/info" -H "Content-Type: application/json" -d 'None'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:23 Response status code: 200. Response content: b'{"listenAddresses":["/ip4/172.18.227.143/tcp/63882/p2p/16Uiu2HAmVkARNo1CM67V1ijtwZQHBUQpghBEEAGtFGDDXVMVqaaZ","/ip4/172.18.227.143/tcp/63883/ws/p2p/16Uiu2HAmVkARNo1CM67V1ijtwZQHBUQpghBEEAGtFGDDXVMVqaaZ"],"enrUri":"enr:-LO4QDI-VkwzJoz7OwbdfW7D0ArCu5aml-DTMTT_AxNfhevQFm_sV7-rfsmJHRl1HY1gOuXpzhC69nv-rS9qYn0e040BgmlkgnY0gmlwhKwS44-KbXVsdGlhZGRyc4wACgSsEuOPBvmL3QOCcnOFAAABAACJc2VjcDI1NmsxoQP96ffvitvNCKJZUX0DS8KCZ8RKb_ZHdt4v1RYYsUZI_oN0Y3CC-YqDdWRwgvmMhXdha3UyAA"}'
[32mINFO    [0m src.node.waku_node:waku_node.py:191 REST service is ready !!
[35mDEBUG   [0m src.steps.filter:filter.py:45 Running fixture setup: subscribe_main_nodes
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:38 curl -v -X POST "http://127.0.0.1:65161/relay/v1/subscriptions" -H "Content-Type: application/json" -d '["/waku/2/rs/0/1"]'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:23 Response status code: 200. Response content: b'OK'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:38 curl -v -X POST "http://127.0.0.1:63881/filter/v2/subscriptions" -H "Content-Type: application/json" -d '{"requestId": "feae9142-6bd6-480a-b988-96c35255cd71", "contentFilters": ["/test/1/waku-filter/proto"], "pubsubTopic": "/waku/2/rs/0/1"}'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:23 Response status code: 200. Response content: b'{"requestId":"feae9142-6bd6-480a-b988-96c35255cd71","statusDesc":"OK"}'
[32mINFO    [0m src.node.api_clients.base_client:custom_logger.py:10 Log line was discarded because it's longer than max_log_line_length=5000
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:23 Response status code: 200. Response content: b'OK'
[35mDEBUG   [0m src.libs.common:common.py:35 Sleeping for 2 seconds
[35mDEBUG   [0m src.steps.filter:filter.py:94 Checking that peer NODE_2:harbor.status.im/wakuorg/nwaku:latest can find the published message
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:38 curl -v -X GET "http://127.0.0.1:63881/filter/v2/messages/%2Ftest%2F1%2Fwaku-filter%2Fproto" -H "Content-Type: application/json" -d 'None'
[32mINFO    [0m src.node.api_clients.base_client:custom_logger.py:10 Log line was discarded because it's longer than max_log_line_length=5000
[35mDEBUG   [0m tests.conftest:conftest.py:51 Running fixture teardown: test_setup
[35mDEBUG   [0m tests.conftest:conftest.py:75 Running fixture teardown: close_open_nodes
[35mDEBUG   [0m src.node.waku_node:waku_node.py:168 Stopping container with id 1f3fb9ab15ed
[35mDEBUG   [0m src.node.waku_node:waku_node.py:171 Container stopped.
[35mDEBUG   [0m src.node.waku_node:waku_node.py:168 Stopping container with id 804b9d56db10
[35mDEBUG   [0m src.node.waku_node:waku_node.py:171 Container stopped.