[35mDEBUG   [0m tests.conftest:conftest.py:43 Running fixture setup: test_id
[35mDEBUG   [0m tests.conftest:conftest.py:49 Running test: test_ping_only_some_nodes_have_subscriptions with id: 2024-01-25_04-13-13__40421568-af6c-4687-8a92-4b117e1d734d
[35mDEBUG   [0m src.steps.filter:filter.py:27 Running fixture setup: filter_setup
[35mDEBUG   [0m src.steps.filter:filter.py:33 Running fixture setup: setup_main_relay_node
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:17 Docker client initialized with image harbor.status.im/wakuorg/nwaku:latest
[35mDEBUG   [0m src.node.waku_node:waku_node.py:21 WakuNode instance initialized with log path ./log/docker/node1_2024-01-25_04-13-13__40421568-af6c-4687-8a92-4b117e1d734d__harbor.status.im_wakuorg_nwaku:latest.log
[35mDEBUG   [0m src.node.waku_node:waku_node.py:25 Starting Node...
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:20 Attempting to create or retrieve network waku
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:23 Network waku already exists
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:73 Generated random external IP 172.18.162.30
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:66 Generated ports ['32233', '32234', '32235', '32236', '32237']
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:42 Starting container with image harbor.status.im/wakuorg/nwaku:latest
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:43 Using args ['--listen-address=0.0.0.0', '--rest=true', '--rest-admin=true', '--websocket-support=true', '--log-level=TRACE', '--rest-relay-cache-capacity=100', '--websocket-port=32235', '--rest-port=32233', '--tcp-port=32234', '--discv5-udp-port=32236', '--rest-address=0.0.0.0', '--nat=extip:172.18.162.30', '--peer-exchange=true', '--discv5-discovery=true', '--cluster-id=0', '--metrics-server=true', '--metrics-server-address=0.0.0.0', '--metrics-server-port=32237', '--metrics-logging=true', '--relay=true', '--filter=true', '--nodekey=30348dd51465150e04a5d9d932c72864c8967f806cce60b5d26afeca1e77eb68']
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:49 Container started with ID 92842ee22e80. Setting up logs at ./log/docker/node1_2024-01-25_04-13-13__40421568-af6c-4687-8a92-4b117e1d734d__harbor.status.im_wakuorg_nwaku:latest.log
[35mDEBUG   [0m src.node.waku_node:waku_node.py:78 Started container from image harbor.status.im/wakuorg/nwaku:latest. REST: 32233
[35mDEBUG   [0m src.libs.common:common.py:33 Sleeping for 1 seconds
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:11 GET call: http://127.0.0.1:32233/debug/v1/info with payload: None
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'{"listenAddresses":["/ip4/172.18.162.30/tcp/32234/p2p/16Uiu2HAmGNtM2rQ8abySFNhqPDFY4cmfAEpfo9Z9fD3NekoFR2ip","/ip4/172.18.162.30/tcp/32235/ws/p2p/16Uiu2HAmGNtM2rQ8abySFNhqPDFY4cmfAEpfo9Z9fD3NekoFR2ip"],"enrUri":"enr:-Kq4QHbNFC1kQiCQYjEnSXDbe5w6civSBZw0AKSrbpfibR-LYjmMM83QjhV5caxMT_g_mPK97XEz__O6n1JPeLbVgeYBgmlkgnY0gmlwhKwSoh6KbXVsdGlhZGRyc4wACgSsEqIeBn3r3QOJc2VjcDI1NmsxoQM3Tqpf5eFn4Jztm4gB0Y0JVSJyxyZsW8QR-QU5DZb-PYN0Y3CCfeqDdWRwgn3shXdha3UyBQ"}'
[32mINFO    [0m src.node.waku_node:waku_node.py:113 REST service is ready !!
[35mDEBUG   [0m src.steps.filter:filter.py:38 Running fixture setup: setup_main_filter_node
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:17 Docker client initialized with image harbor.status.im/wakuorg/nwaku:latest
[35mDEBUG   [0m src.node.waku_node:waku_node.py:21 WakuNode instance initialized with log path ./log/docker/node2_2024-01-25_04-13-13__40421568-af6c-4687-8a92-4b117e1d734d__harbor.status.im_wakuorg_nwaku:latest.log
[35mDEBUG   [0m src.node.waku_node:waku_node.py:25 Starting Node...
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:20 Attempting to create or retrieve network waku
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:23 Network waku already exists
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:73 Generated random external IP 172.18.133.135
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:66 Generated ports ['52516', '52517', '52518', '52519', '52520']
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:42 Starting container with image harbor.status.im/wakuorg/nwaku:latest
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:43 Using args ['--listen-address=0.0.0.0', '--rest=true', '--rest-admin=true', '--websocket-support=true', '--log-level=TRACE', '--rest-relay-cache-capacity=100', '--websocket-port=52518', '--rest-port=52516', '--tcp-port=52517', '--discv5-udp-port=52519', '--rest-address=0.0.0.0', '--nat=extip:172.18.133.135', '--peer-exchange=true', '--discv5-discovery=true', '--cluster-id=0', '--metrics-server=true', '--metrics-server-address=0.0.0.0', '--metrics-server-port=52520', '--metrics-logging=true', '--relay=false', '--filter=true', '--discv5-bootstrap-node=enr:-Kq4QHbNFC1kQiCQYjEnSXDbe5w6civSBZw0AKSrbpfibR-LYjmMM83QjhV5caxMT_g_mPK97XEz__O6n1JPeLbVgeYBgmlkgnY0gmlwhKwSoh6KbXVsdGlhZGRyc4wACgSsEqIeBn3r3QOJc2VjcDI1NmsxoQM3Tqpf5eFn4Jztm4gB0Y0JVSJyxyZsW8QR-QU5DZb-PYN0Y3CCfeqDdWRwgn3shXdha3UyBQ', '--filternode=/ip4/172.18.162.30/tcp/32234/p2p/16Uiu2HAmGNtM2rQ8abySFNhqPDFY4cmfAEpfo9Z9fD3NekoFR2ip']
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:49 Container started with ID b0a495752703. Setting up logs at ./log/docker/node2_2024-01-25_04-13-13__40421568-af6c-4687-8a92-4b117e1d734d__harbor.status.im_wakuorg_nwaku:latest.log
[35mDEBUG   [0m src.node.waku_node:waku_node.py:78 Started container from image harbor.status.im/wakuorg/nwaku:latest. REST: 52516
[35mDEBUG   [0m src.libs.common:common.py:33 Sleeping for 1 seconds
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:11 GET call: http://127.0.0.1:52516/debug/v1/info with payload: None
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'{"listenAddresses":["/ip4/172.18.133.135/tcp/52517/p2p/16Uiu2HAmDF6BAbVZ22BXDit9PET99hc8WYM2AzSnZnRgknUm1RgF","/ip4/172.18.133.135/tcp/52518/ws/p2p/16Uiu2HAmDF6BAbVZ22BXDit9PET99hc8WYM2AzSnZnRgknUm1RgF"],"enrUri":"enr:-Kq4QDEW3mE6jtJ1hJeX7fEWD-nX_LD-ddTSBKJjgebIM6_YHfA5DMwxtRPmLCyo7LAnuo7aRtCd5zyZLOQ8ohnwuC4BgmlkgnY0gmlwhKwShYeKbXVsdGlhZGRyc4wACgSsEoWHBs0m3QOJc2VjcDI1NmsxoQMIvFWZV2Riq7_E618IOGE3To5gzjRr3kCa46zrRzgCpIN0Y3CCzSWDdWRwgs0nhXdha3UyBA"}'
[32mINFO    [0m src.node.waku_node:waku_node.py:113 REST service is ready !!
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:11 POST call: http://127.0.0.1:32233/relay/v1/subscriptions with payload: ["/waku/2/rs/0/1"]
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'OK'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:11 POST call: http://127.0.0.1:52516/filter/v2/subscriptions with payload: {"requestId": "2c815b0c-7124-4619-a64d-f5cac3947020", "contentFilters": ["/test/1/waku-filter/proto"], "pubsubTopic": "/waku/2/rs/0/1"}
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'{"requestId":"2c815b0c-7124-4619-a64d-f5cac3947020","statusCode":0,"statusDesc":""}'
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:17 Docker client initialized with image harbor.status.im/wakuorg/nwaku:latest
[35mDEBUG   [0m src.node.waku_node:waku_node.py:21 WakuNode instance initialized with log path ./log/docker/additional_node1_2024-01-25_04-13-13__40421568-af6c-4687-8a92-4b117e1d734d__harbor.status.im_wakuorg_nwaku:latest.log
[35mDEBUG   [0m src.node.waku_node:waku_node.py:25 Starting Node...
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:20 Attempting to create or retrieve network waku
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:23 Network waku already exists
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:73 Generated random external IP 172.18.140.178
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:66 Generated ports ['43090', '43091', '43092', '43093', '43094']
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:42 Starting container with image harbor.status.im/wakuorg/nwaku:latest
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:43 Using args ['--listen-address=0.0.0.0', '--rest=true', '--rest-admin=true', '--websocket-support=true', '--log-level=TRACE', '--rest-relay-cache-capacity=100', '--websocket-port=43092', '--rest-port=43090', '--tcp-port=43091', '--discv5-udp-port=43093', '--rest-address=0.0.0.0', '--nat=extip:172.18.140.178', '--peer-exchange=true', '--discv5-discovery=true', '--cluster-id=0', '--metrics-server=true', '--metrics-server-address=0.0.0.0', '--metrics-server-port=43094', '--metrics-logging=true', '--relay=false', '--filter=true', '--discv5-bootstrap-node=enr:-Kq4QHbNFC1kQiCQYjEnSXDbe5w6civSBZw0AKSrbpfibR-LYjmMM83QjhV5caxMT_g_mPK97XEz__O6n1JPeLbVgeYBgmlkgnY0gmlwhKwSoh6KbXVsdGlhZGRyc4wACgSsEqIeBn3r3QOJc2VjcDI1NmsxoQM3Tqpf5eFn4Jztm4gB0Y0JVSJyxyZsW8QR-QU5DZb-PYN0Y3CCfeqDdWRwgn3shXdha3UyBQ', '--filternode=/ip4/172.18.162.30/tcp/32234/p2p/16Uiu2HAmGNtM2rQ8abySFNhqPDFY4cmfAEpfo9Z9fD3NekoFR2ip']
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:49 Container started with ID 5c0f78a3b2ab. Setting up logs at ./log/docker/additional_node1_2024-01-25_04-13-13__40421568-af6c-4687-8a92-4b117e1d734d__harbor.status.im_wakuorg_nwaku:latest.log
[35mDEBUG   [0m src.node.waku_node:waku_node.py:78 Started container from image harbor.status.im/wakuorg/nwaku:latest. REST: 43090
[35mDEBUG   [0m src.libs.common:common.py:33 Sleeping for 1 seconds
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:11 GET call: http://127.0.0.1:43090/debug/v1/info with payload: None
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'{"listenAddresses":["/ip4/172.18.140.178/tcp/43091/p2p/16Uiu2HAkxMmkXHYUpJM7sW7ScZMWWtrVSiYhufRZANXyeS3Rst8T","/ip4/172.18.140.178/tcp/43092/ws/p2p/16Uiu2HAkxMmkXHYUpJM7sW7ScZMWWtrVSiYhufRZANXyeS3Rst8T"],"enrUri":"enr:-Kq4QOMrr_WmegJQkWw3y5ucWPLvfJY8BAeOynSoncgxldi4GI0mpvRRybnZCbybOm42HUr9FtP2V5mTQeWRp2qnUBgBgmlkgnY0gmlwhKwSjLKKbXVsdGlhZGRyc4wACgSsEoyyBqhU3QOJc2VjcDI1NmsxoQIrk0NXrg0gj9qFq5ZQf5wvxhma96BDiaRoKwDEHlVhLIN0Y3CCqFODdWRwgqhVhXdha3UyBA"}'
[32mINFO    [0m src.node.waku_node:waku_node.py:113 REST service is ready !!
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:17 Docker client initialized with image harbor.status.im/wakuorg/go-waku:latest
[35mDEBUG   [0m src.node.waku_node:waku_node.py:21 WakuNode instance initialized with log path ./log/docker/additional_node2_2024-01-25_04-13-13__40421568-af6c-4687-8a92-4b117e1d734d__harbor.status.im_wakuorg_go-waku:latest.log
[35mDEBUG   [0m src.node.waku_node:waku_node.py:25 Starting Node...
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:20 Attempting to create or retrieve network waku
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:23 Network waku already exists
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:73 Generated random external IP 172.18.189.123
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:66 Generated ports ['38814', '38815', '38816', '38817', '38818']
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:42 Starting container with image harbor.status.im/wakuorg/go-waku:latest
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:43 Using args ['--listen-address=0.0.0.0', '--rest=true', '--rest-admin=true', '--websocket-support=true', '--log-level=DEBUG', '--rest-relay-cache-capacity=100', '--websocket-port=38816', '--rest-port=38814', '--tcp-port=38815', '--discv5-udp-port=38817', '--rest-address=0.0.0.0', '--nat=extip:172.18.189.123', '--peer-exchange=true', '--discv5-discovery=true', '--cluster-id=0', '--min-relay-peers-to-publish=1', '--legacy-filter=false', '--rest-filter-cache-capacity=50', '--relay=false', '--filter=true', '--discv5-bootstrap-node=enr:-Kq4QHbNFC1kQiCQYjEnSXDbe5w6civSBZw0AKSrbpfibR-LYjmMM83QjhV5caxMT_g_mPK97XEz__O6n1JPeLbVgeYBgmlkgnY0gmlwhKwSoh6KbXVsdGlhZGRyc4wACgSsEqIeBn3r3QOJc2VjcDI1NmsxoQM3Tqpf5eFn4Jztm4gB0Y0JVSJyxyZsW8QR-QU5DZb-PYN0Y3CCfeqDdWRwgn3shXdha3UyBQ', '--filternode=/ip4/172.18.162.30/tcp/32234/p2p/16Uiu2HAmGNtM2rQ8abySFNhqPDFY4cmfAEpfo9Z9fD3NekoFR2ip']
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:49 Container started with ID c5f30559704a. Setting up logs at ./log/docker/additional_node2_2024-01-25_04-13-13__40421568-af6c-4687-8a92-4b117e1d734d__harbor.status.im_wakuorg_go-waku:latest.log
[35mDEBUG   [0m src.node.waku_node:waku_node.py:78 Started container from image harbor.status.im/wakuorg/go-waku:latest. REST: 38814
[35mDEBUG   [0m src.libs.common:common.py:33 Sleeping for 1 seconds
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:11 GET call: http://127.0.0.1:38814/debug/v1/info with payload: None
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'{"enrUri":"enr:-Ly4QOmLLJTTJbvIQfcNIsEYhx-RkjlB0gck4GpJojp2N-ioPuiNZMnqTA9tx2zsPsMt7wf19NvzIaK3BjNiIOR2XIyGAY0-0n_agmlkgnY0gmlwhKwRAAqKbXVsdGlhZGRyc5gACgSsEQAKBpeg3QMACgR_AAABBpeg3QOJc2VjcDI1NmsxoQOl0ncOKqQB-DfzZsAijw6ytRBi2e4G_qB3yclAkFyV0oN0Y3CCl5-DdWRwgpehhXdha3UyBA","listenAddresses":["/ip4/127.0.0.1/tcp/38815/p2p/16Uiu2HAmPpHksDkGXSG8v8DDEPSboFLvLoYmufp3wj4sLkouFwu3","/ip4/127.0.0.1/tcp/38816/ws/p2p/16Uiu2HAmPpHksDkGXSG8v8DDEPSboFLvLoYmufp3wj4sLkouFwu3","/ip4/172.17.0.10/tcp/38815/p2p/16Uiu2HAmPpHksDkGXSG8v8DDEPSboFLvLoYmufp3wj4sLkouFwu3","/ip4/172.17.0.10/tcp/38816/ws/p2p/16Uiu2HAmPpHksDkGXSG8v8DDEPSboFLvLoYmufp3wj4sLkouFwu3"]}'
[32mINFO    [0m src.node.waku_node:waku_node.py:113 REST service is ready !!
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:17 Docker client initialized with image harbor.status.im/wakuorg/nwaku:latest
[35mDEBUG   [0m src.node.waku_node:waku_node.py:21 WakuNode instance initialized with log path ./log/docker/additional_node3_2024-01-25_04-13-13__40421568-af6c-4687-8a92-4b117e1d734d__harbor.status.im_wakuorg_nwaku:latest.log
[35mDEBUG   [0m src.node.waku_node:waku_node.py:25 Starting Node...
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:20 Attempting to create or retrieve network waku
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:23 Network waku already exists
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:73 Generated random external IP 172.18.153.85
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:66 Generated ports ['2009', '2010', '2011', '2012', '2013']
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:42 Starting container with image harbor.status.im/wakuorg/nwaku:latest
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:43 Using args ['--listen-address=0.0.0.0', '--rest=true', '--rest-admin=true', '--websocket-support=true', '--log-level=TRACE', '--rest-relay-cache-capacity=100', '--websocket-port=2011', '--rest-port=2009', '--tcp-port=2010', '--discv5-udp-port=2012', '--rest-address=0.0.0.0', '--nat=extip:172.18.153.85', '--peer-exchange=true', '--discv5-discovery=true', '--cluster-id=0', '--metrics-server=true', '--metrics-server-address=0.0.0.0', '--metrics-server-port=2013', '--metrics-logging=true', '--relay=false', '--filter=true', '--discv5-bootstrap-node=enr:-Kq4QHbNFC1kQiCQYjEnSXDbe5w6civSBZw0AKSrbpfibR-LYjmMM83QjhV5caxMT_g_mPK97XEz__O6n1JPeLbVgeYBgmlkgnY0gmlwhKwSoh6KbXVsdGlhZGRyc4wACgSsEqIeBn3r3QOJc2VjcDI1NmsxoQM3Tqpf5eFn4Jztm4gB0Y0JVSJyxyZsW8QR-QU5DZb-PYN0Y3CCfeqDdWRwgn3shXdha3UyBQ', '--filternode=/ip4/172.18.162.30/tcp/32234/p2p/16Uiu2HAmGNtM2rQ8abySFNhqPDFY4cmfAEpfo9Z9fD3NekoFR2ip']
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:49 Container started with ID 362d35f4d3d4. Setting up logs at ./log/docker/additional_node3_2024-01-25_04-13-13__40421568-af6c-4687-8a92-4b117e1d734d__harbor.status.im_wakuorg_nwaku:latest.log
[35mDEBUG   [0m src.node.waku_node:waku_node.py:78 Started container from image harbor.status.im/wakuorg/nwaku:latest. REST: 2009
[35mDEBUG   [0m src.libs.common:common.py:33 Sleeping for 1 seconds
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:11 GET call: http://127.0.0.1:2009/debug/v1/info with payload: None
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'{"listenAddresses":["/ip4/172.18.153.85/tcp/2010/p2p/16Uiu2HAm27FnWDhqvqAbQnx3YAbKFwkUxwmpb56YEr8VGfKH1DuJ","/ip4/172.18.153.85/tcp/2011/ws/p2p/16Uiu2HAm27FnWDhqvqAbQnx3YAbKFwkUxwmpb56YEr8VGfKH1DuJ"],"enrUri":"enr:-Kq4QDK0li8jGAX-CIhtjoa09FMq7Lc7W-ZomQR5yjXXzVykfnFQUolqdkKBYS2xOgVEtALjQdbmFbsy4NEk7a02wLIBgmlkgnY0gmlwhKwSmVWKbXVsdGlhZGRyc4wACgSsEplVBgfb3QOJc2VjcDI1NmsxoQJjSf84qEKd0UDgrK_R9CbnF4ybAoTk_ryrmKcl0g1YyYN0Y3CCB9qDdWRwggfchXdha3UyBA"}'
[32mINFO    [0m src.node.waku_node:waku_node.py:113 REST service is ready !!
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:11 GET call: http://127.0.0.1:52516/filter/v2/subscriptions/1 with payload: None
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'{"requestId":"1","statusCode":0,"statusDesc":""}'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:11 GET call: http://127.0.0.1:43090/filter/v2/subscriptions/6f7c59aa-5879-4a24-a86d-16ff83d26652 with payload: None
[1m[31mERROR   [0m src.node.api_clients.base_client:base_client.py:16 HTTP error occurred: 404 Client Error: Not Found for url: http://127.0.0.1:43090/filter/v2/subscriptions/6f7c59aa-5879-4a24-a86d-16ff83d26652. Response content: b'{"requestId":"6f7c59aa-5879-4a24-a86d-16ff83d26652","statusCode":404,"statusDesc":"NOT_FOUND: peer has no subscriptions"}'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:11 GET call: http://127.0.0.1:38814/filter/v2/subscriptions/ebda1634-f0af-4116-b764-111f64808972 with payload: None
[1m[31mERROR   [0m src.node.api_clients.base_client:base_client.py:16 HTTP error occurred: 404 Client Error: Not Found for url: http://127.0.0.1:38814/filter/v2/subscriptions/ebda1634-f0af-4116-b764-111f64808972. Response content: b'{"requestId":"ebda1634-f0af-4116-b764-111f64808972","statusDesc":"peer has no subscription"}'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:11 GET call: http://127.0.0.1:2009/filter/v2/subscriptions/92e909e5-b1ff-4e36-bc67-5a66e4fe2346 with payload: None
[1m[31mERROR   [0m src.node.api_clients.base_client:base_client.py:16 HTTP error occurred: 404 Client Error: Not Found for url: http://127.0.0.1:2009/filter/v2/subscriptions/92e909e5-b1ff-4e36-bc67-5a66e4fe2346. Response content: b'{"requestId":"92e909e5-b1ff-4e36-bc67-5a66e4fe2346","statusCode":404,"statusDesc":"NOT_FOUND: peer has no subscriptions"}'
[35mDEBUG   [0m tests.conftest:conftest.py:51 Running fixture teardown: test_setup
[35mDEBUG   [0m tests.conftest:conftest.py:75 Running fixture teardown: close_open_nodes
[35mDEBUG   [0m src.node.waku_node:waku_node.py:90 Stopping container with id 92842ee22e80
[35mDEBUG   [0m src.node.waku_node:waku_node.py:93 Container stopped.
[35mDEBUG   [0m src.node.waku_node:waku_node.py:90 Stopping container with id b0a495752703
[35mDEBUG   [0m src.node.waku_node:waku_node.py:93 Container stopped.
[35mDEBUG   [0m src.node.waku_node:waku_node.py:90 Stopping container with id 5c0f78a3b2ab
[35mDEBUG   [0m src.node.waku_node:waku_node.py:93 Container stopped.
[35mDEBUG   [0m src.node.waku_node:waku_node.py:90 Stopping container with id c5f30559704a
[35mDEBUG   [0m src.node.waku_node:waku_node.py:93 Container stopped.
[35mDEBUG   [0m src.node.waku_node:waku_node.py:90 Stopping container with id 362d35f4d3d4
[35mDEBUG   [0m src.node.waku_node:waku_node.py:93 Container stopped.