[35mDEBUG   [0m tests.conftest:conftest.py:51 Running fixture setup: test_id
[35mDEBUG   [0m tests.conftest:conftest.py:57 Running test: test_cant_retrieve_messages_on_not_subscribed_content_topic with id: 2024-10-28_04-16-56__837c0764-2dce-4070-a501-8ff24a48157b
[35mDEBUG   [0m src.steps.common:common.py:17 Running fixture setup: common_setup
[35mDEBUG   [0m src.steps.relay:relay.py:28 Running fixture setup: relay_setup
[35mDEBUG   [0m src.steps.sharding:sharding.py:29 Running fixture setup: sharding_setup
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:19 Docker client initialized with image wakuorg/nwaku:latest
[35mDEBUG   [0m src.node.waku_node:waku_node.py:85 WakuNode instance initialized with log path ./log/docker/node1_2024-10-28_04-16-56__837c0764-2dce-4070-a501-8ff24a48157b__wakuorg_nwaku:latest.log
[35mDEBUG   [0m src.node.waku_node:waku_node.py:89 Starting Node...
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:22 Attempting to create or retrieve network waku
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:25 Network waku already exists
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:108 Generated random external IP 172.18.179.26
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:101 Generated ports ['44051', '44052', '44053', '44054', '44055']
[35mDEBUG   [0m src.node.waku_node:waku_node.py:434 RLN credentials were not set
[32mINFO    [0m src.node.waku_node:waku_node.py:163 RLN credentials not set or credential store not available, starting without RLN
[35mDEBUG   [0m src.node.waku_node:waku_node.py:165 Using volumes []
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:49 docker run -i -t -p 44051:44051 -p 44052:44052 -p 44053:44053 -p 44054:44054 -p 44055:44055 wakuorg/nwaku:latest --listen-address=0.0.0.0 --rest=true --rest-admin=true --websocket-support=true --log-level=TRACE --rest-relay-cache-capacity=100 --websocket-port=44053 --rest-port=44051 --tcp-port=44052 --discv5-udp-port=44054 --rest-address=0.0.0.0 --nat=extip:172.18.179.26 --peer-exchange=true --discv5-discovery=true --cluster-id=2 --nodekey=ec5f33c9f1eb00a86adef8f9eb525a7b6e560d3dc97b8abf3deab0ce557bbdc6 --shard=0 --metrics-server=true --metrics-server-address=0.0.0.0 --metrics-server-port=44055 --metrics-logging=true --relay=true --filter=true --content-topic=/myapp/1/latest/proto
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:55 docker network connect --ip 172.18.179.26 waku 7c7f2b43193bed74bb1b6041022b30380d49e8976ca6b500bec420ce56fa2a6e
[1m[31mERROR   [0m src.node.docker_mananger:docker_mananger.py:89 Max retries reached for container 389465d2ec20. Exiting log stream.
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:58 Container started with ID 7c7f2b43193b. Setting up logs at ./log/docker/node1_2024-10-28_04-16-56__837c0764-2dce-4070-a501-8ff24a48157b__wakuorg_nwaku:latest.log
[35mDEBUG   [0m src.node.waku_node:waku_node.py:177 Started container from image wakuorg/nwaku:latest. REST: 44051
[35mDEBUG   [0m src.libs.common:common.py:35 Sleeping for 1 seconds
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X GET "http://127.0.0.1:44051/health" -H "Content-Type: application/json" -d 'None'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'{"nodeHealth":"Ready","protocolsHealth":[]}'
[32mINFO    [0m src.node.waku_node:waku_node.py:277 Node protocols are initialized !!
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X GET "http://127.0.0.1:44051/debug/v1/info" -H "Content-Type: application/json" -d 'None'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'{"listenAddresses":["/ip4/172.18.179.26/tcp/44052/p2p/16Uiu2HAmGgV1xYZvNk16DdQ7bgZr7CM14rVKK4rtXBuwdR3fnLEt","/ip4/172.18.179.26/tcp/44053/ws/p2p/16Uiu2HAmGgV1xYZvNk16DdQ7bgZr7CM14rVKK4rtXBuwdR3fnLEt"],"enrUri":"enr:-LO4QFxQXEO3KKyl1-SgfElx3ZjeoO4sJZVB27OU6X21fSunNIPgzy01MK-9DGHvzYfqxvBdjGTn-QUeRnm_5WV6_0kBgmlkgnY0gmlwhKwSsxqKbXVsdGlhZGRyc4wACgSsErMaBqwV3QOCcnOFAAIBAACJc2VjcDI1NmsxoQM70L33WaO4xUIzV7HljJ0n5kAZnXjDDFj21oX37_IHeYN0Y3CCrBSDdWRwgqwWhXdha3UyBQ"}'
[32mINFO    [0m src.node.waku_node:waku_node.py:282 REST service is ready !!
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:19 Docker client initialized with image wakuorg/nwaku:latest
[35mDEBUG   [0m src.node.waku_node:waku_node.py:85 WakuNode instance initialized with log path ./log/docker/node2_2024-10-28_04-16-56__837c0764-2dce-4070-a501-8ff24a48157b__wakuorg_nwaku:latest.log
[35mDEBUG   [0m src.node.waku_node:waku_node.py:89 Starting Node...
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:22 Attempting to create or retrieve network waku
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:25 Network waku already exists
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:108 Generated random external IP 172.18.217.117
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:101 Generated ports ['27883', '27884', '27885', '27886', '27887']
[35mDEBUG   [0m src.node.waku_node:waku_node.py:434 RLN credentials were not set
[32mINFO    [0m src.node.waku_node:waku_node.py:163 RLN credentials not set or credential store not available, starting without RLN
[35mDEBUG   [0m src.node.waku_node:waku_node.py:165 Using volumes []
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:49 docker run -i -t -p 27883:27883 -p 27884:27884 -p 27885:27885 -p 27886:27886 -p 27887:27887 wakuorg/nwaku:latest --listen-address=0.0.0.0 --rest=true --rest-admin=true --websocket-support=true --log-level=TRACE --rest-relay-cache-capacity=100 --websocket-port=27885 --rest-port=27883 --tcp-port=27884 --discv5-udp-port=27886 --rest-address=0.0.0.0 --nat=extip:172.18.217.117 --peer-exchange=true --discv5-discovery=true --cluster-id=2 --nodekey=c49ccdc08e73a64ffb6b49304a5b83ece0ea42de02a074fca5ba7bd539fc8b01 --shard=0 --metrics-server=true --metrics-server-address=0.0.0.0 --metrics-server-port=27887 --metrics-logging=true --relay=true --discv5-bootstrap-node=enr:-LO4QFxQXEO3KKyl1-SgfElx3ZjeoO4sJZVB27OU6X21fSunNIPgzy01MK-9DGHvzYfqxvBdjGTn-QUeRnm_5WV6_0kBgmlkgnY0gmlwhKwSsxqKbXVsdGlhZGRyc4wACgSsErMaBqwV3QOCcnOFAAIBAACJc2VjcDI1NmsxoQM70L33WaO4xUIzV7HljJ0n5kAZnXjDDFj21oX37_IHeYN0Y3CCrBSDdWRwgqwWhXdha3UyBQ --content-topic=/myapp/1/latest/proto
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:55 docker network connect --ip 172.18.217.117 waku bcf83a0645ea588c5742efd3801ef8f89d079fb0a4be03777bc6b00334736c11
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:58 Container started with ID bcf83a0645ea. Setting up logs at ./log/docker/node2_2024-10-28_04-16-56__837c0764-2dce-4070-a501-8ff24a48157b__wakuorg_nwaku:latest.log
[35mDEBUG   [0m src.node.waku_node:waku_node.py:177 Started container from image wakuorg/nwaku:latest. REST: 27883
[35mDEBUG   [0m src.libs.common:common.py:35 Sleeping for 1 seconds
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X GET "http://127.0.0.1:27883/health" -H "Content-Type: application/json" -d 'None'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'{"nodeHealth":"Ready","protocolsHealth":[]}'
[32mINFO    [0m src.node.waku_node:waku_node.py:277 Node protocols are initialized !!
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X GET "http://127.0.0.1:27883/debug/v1/info" -H "Content-Type: application/json" -d 'None'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'{"listenAddresses":["/ip4/172.18.217.117/tcp/27884/p2p/16Uiu2HAm2bJmA5yGw9nPwF65CfceeSCQR4gVCwawRdK2mEVMKRxG","/ip4/172.18.217.117/tcp/27885/ws/p2p/16Uiu2HAm2bJmA5yGw9nPwF65CfceeSCQR4gVCwawRdK2mEVMKRxG"],"enrUri":"enr:-LO4QK03nxItlavkI3NqoDeh6rL8XMNeh0xkCOv7FM4HgR1HHMOiN4IEi-hT7tTBBWbBA7-oimcH9WO2Ua3nooSkNMQBgmlkgnY0gmlwhKwS2XWKbXVsdGlhZGRyc4wACgSsEtl1Bmzt3QOCcnOFAAIBAACJc2VjcDI1NmsxoQJqeaAeOAD0E7qHP7pIbXQpUe1xH9mCixhJoVPZ0guFtYN0Y3CCbOyDdWRwgmzuhXdha3UyAQ"}'
[32mINFO    [0m src.node.waku_node:waku_node.py:282 REST service is ready !!
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X POST "http://127.0.0.1:27883/admin/v1/peers" -H "Content-Type: application/json" -d '["/ip4/172.18.179.26/tcp/44052/p2p/16Uiu2HAmGgV1xYZvNk16DdQ7bgZr7CM14rVKK4rtXBuwdR3fnLEt"]'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'OK'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X POST "http://127.0.0.1:44051/relay/v1/auto/subscriptions" -H "Content-Type: application/json" -d '["/myapp/1/latest/proto"]'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'OK'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X POST "http://127.0.0.1:27883/relay/v1/auto/subscriptions" -H "Content-Type: application/json" -d '["/myapp/1/latest/proto"]'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'OK'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X POST "http://127.0.0.1:44051/relay/v1/auto/messages" -H "Content-Type: application/json" -d '{"payload": "U2hhcmRpbmcgd29ya3MhIQ==", "contentTopic": "/toychat/2/huilong/proto", "timestamp": '$(date +%s%N)'}'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'OK'
[35mDEBUG   [0m src.libs.common:common.py:35 Sleeping for 0.1 seconds
[35mDEBUG   [0m src.steps.sharding:sharding.py:157 Checking that peer NODE_1:wakuorg/nwaku:latest can find the published message
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X GET "http://127.0.0.1:44051/relay/v1/auto/messages/%2Ftoychat%2F2%2Fhuilong%2Fproto" -H "Content-Type: application/json" -d 'None'
[1m[31mERROR   [0m src.node.api_clients.base_client:base_client.py:16 HTTP error occurred: 404 Client Error: Not Found for url: http://127.0.0.1:44051/relay/v1/auto/messages/%2Ftoychat%2F2%2Fhuilong%2Fproto. Response content: b'/toychat/2/huilong/proto'
[35mDEBUG   [0m tests.conftest:conftest.py:59 Running fixture teardown: test_setup
[35mDEBUG   [0m tests.conftest:conftest.py:83 Running fixture teardown: close_open_nodes
[35mDEBUG   [0m src.node.waku_node:waku_node.py:221 Stopping container with id 7c7f2b43193b
[35mDEBUG   [0m src.node.waku_node:waku_node.py:228 Container stopped.
[35mDEBUG   [0m src.node.waku_node:waku_node.py:221 Stopping container with id bcf83a0645ea
[1m[31mERROR   [0m src.node.docker_mananger:docker_mananger.py:89 Max retries reached for container 7c7f2b43193b. Exiting log stream.
[35mDEBUG   [0m src.node.waku_node:waku_node.py:228 Container stopped.
[35mDEBUG   [0m tests.conftest:conftest.py:98 Running fixture teardown: check_waku_log_errors
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:144 No errors found in the waku logs.
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:144 No errors found in the waku logs.