[35mDEBUG   [0m tests.conftest:conftest.py:51 Running fixture setup: test_id
[35mDEBUG   [0m tests.conftest:conftest.py:57 Running test: test_filter_update_subscription_with_no_request_id with id: 2024-08-22_04-17-41__0a964158-3f0b-497f-90df-e18f22987c89
[35mDEBUG   [0m src.steps.common:common.py:17 Running fixture setup: common_setup
[35mDEBUG   [0m src.steps.filter:filter.py:28 Running fixture setup: filter_setup
[35mDEBUG   [0m src.steps.filter:filter.py:34 Running fixture setup: setup_main_relay_node
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:17 Docker client initialized with image wakuorg/nwaku:latest
[35mDEBUG   [0m src.node.waku_node:waku_node.py:84 WakuNode instance initialized with log path ./log/docker/node1_2024-08-22_04-17-41__0a964158-3f0b-497f-90df-e18f22987c89__wakuorg_nwaku:latest.log
[35mDEBUG   [0m src.node.waku_node:waku_node.py:88 Starting Node...
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:20 Attempting to create or retrieve network waku
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:23 Network waku already exists
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:80 Generated random external IP 172.18.145.163
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:73 Generated ports ['52774', '52775', '52776', '52777', '52778']
[35mDEBUG   [0m src.node.waku_node:waku_node.py:430 RLN credentials were not set
[32mINFO    [0m src.node.waku_node:waku_node.py:162 RLN credentials not set or credential store not available, starting without RLN
[35mDEBUG   [0m src.node.waku_node:waku_node.py:164 Using volumes []
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:47 docker run -i -t -p 52774:52774 -p 52775:52775 -p 52776:52776 -p 52777:52777 -p 52778:52778 wakuorg/nwaku:latest --listen-address=0.0.0.0 --rest=true --rest-admin=true --websocket-support=true --log-level=TRACE --rest-relay-cache-capacity=100 --websocket-port=52776 --rest-port=52774 --tcp-port=52775 --discv5-udp-port=52777 --rest-address=0.0.0.0 --nat=extip:172.18.145.163 --peer-exchange=true --discv5-discovery=true --cluster-id=3 --nodekey=fdddccaae3f0bae74ddf5c1eafb8b8bc81cdc78ede60fed0fecebf9e176cd7a1 --shard=0 --metrics-server=true --metrics-server-address=0.0.0.0 --metrics-server-port=52778 --metrics-logging=true --relay=true --filter=true
[35mDEBUG   [0m src.node.waku_node:waku_node.py:88 Starting Node...
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:20 Attempting to create or retrieve network waku
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:23 Network waku already exists
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:80 Generated random external IP 172.18.33.122
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:73 Generated ports ['31754', '31755', '31756', '31757', '31758']
[35mDEBUG   [0m src.node.waku_node:waku_node.py:430 RLN credentials were not set
[32mINFO    [0m src.node.waku_node:waku_node.py:162 RLN credentials not set or credential store not available, starting without RLN
[35mDEBUG   [0m src.node.waku_node:waku_node.py:164 Using volumes []
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:47 docker run -i -t -p 31754:31754 -p 31755:31755 -p 31756:31756 -p 31757:31757 -p 31758:31758 wakuorg/nwaku:latest --listen-address=0.0.0.0 --rest=true --rest-admin=true --websocket-support=true --log-level=TRACE --rest-relay-cache-capacity=100 --websocket-port=31756 --rest-port=31754 --tcp-port=31755 --discv5-udp-port=31757 --rest-address=0.0.0.0 --nat=extip:172.18.33.122 --peer-exchange=true --discv5-discovery=true --cluster-id=3 --nodekey=da37bdfc85cc37bef4ff86ddb7aaf71896fb17739a73fd8bbb1cabfa7b4047f7 --shard=0 --metrics-server=true --metrics-server-address=0.0.0.0 --metrics-server-port=31758 --metrics-logging=true --relay=true --filter=true
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:53 docker network connect --ip 172.18.33.122 waku 320b820aa4ced9f539ff8e4982ae806abfccdd5a3a1ded2754c017c4e74b8554
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:56 Container started with ID 320b820aa4ce. Setting up logs at ./log/docker/node1_2024-08-22_04-17-41__0a964158-3f0b-497f-90df-e18f22987c89__wakuorg_nwaku:latest.log
[35mDEBUG   [0m src.node.waku_node:waku_node.py:176 Started container from image wakuorg/nwaku:latest. REST: 31754
[35mDEBUG   [0m src.libs.common:common.py:35 Sleeping for 1 seconds
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X GET "http://127.0.0.1:31754/health" -H "Content-Type: application/json" -d 'None'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'{"nodeHealth":"Ready","protocolsHealth":[]}'
[32mINFO    [0m src.node.waku_node:waku_node.py:276 Node protocols are initialized !!
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X GET "http://127.0.0.1:31754/debug/v1/info" -H "Content-Type: application/json" -d 'None'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'{"listenAddresses":["/ip4/172.18.33.122/tcp/31755/p2p/16Uiu2HAkvENrSWpBso1ggCask2UttBiMNJsrHP3E9A5UQsBiX1Uw","/ip4/172.18.33.122/tcp/31756/ws/p2p/16Uiu2HAkvENrSWpBso1ggCask2UttBiMNJsrHP3E9A5UQsBiX1Uw"],"enrUri":"enr:-LO4QNbWeM84tplR_OoCB64m1QWBVjqEV3rETcUsmjvOoq0yANVk7SsueDsiuovy60NOCI76u3Iz7MAtJZGhw9XoqTEBgmlkgnY0gmlwhKwSIXqKbXVsdGlhZGRyc4wACgSsEiF6BnwM3QOCcnOFAAMBAACJc2VjcDI1NmsxoQIL9u7G8cShiUVlCxCLxS2OigrLAZIB0MUNPUv2h9hn1IN0Y3CCfAuDdWRwgnwNhXdha3UyBQ"}'
[32mINFO    [0m src.node.waku_node:waku_node.py:281 REST service is ready !!
[35mDEBUG   [0m src.steps.filter:filter.py:39 Running fixture setup: setup_main_filter_node
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:17 Docker client initialized with image wakuorg/nwaku:latest
[35mDEBUG   [0m src.node.waku_node:waku_node.py:84 WakuNode instance initialized with log path ./log/docker/node2_2024-08-22_04-17-41__0a964158-3f0b-497f-90df-e18f22987c89__wakuorg_nwaku:latest.log
[35mDEBUG   [0m src.node.waku_node:waku_node.py:88 Starting Node...
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:20 Attempting to create or retrieve network waku
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:23 Network waku already exists
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:80 Generated random external IP 172.18.91.156
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:73 Generated ports ['37411', '37412', '37413', '37414', '37415']
[35mDEBUG   [0m src.node.waku_node:waku_node.py:430 RLN credentials were not set
[32mINFO    [0m src.node.waku_node:waku_node.py:162 RLN credentials not set or credential store not available, starting without RLN
[35mDEBUG   [0m src.node.waku_node:waku_node.py:164 Using volumes []
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:47 docker run -i -t -p 37411:37411 -p 37412:37412 -p 37413:37413 -p 37414:37414 -p 37415:37415 wakuorg/nwaku:latest --listen-address=0.0.0.0 --rest=true --rest-admin=true --websocket-support=true --log-level=TRACE --rest-relay-cache-capacity=100 --websocket-port=37413 --rest-port=37411 --tcp-port=37412 --discv5-udp-port=37414 --rest-address=0.0.0.0 --nat=extip:172.18.91.156 --peer-exchange=true --discv5-discovery=true --cluster-id=3 --nodekey=bbb8dcedcc261bdda880afa0fee6f32ed1ba81c38acadc8569da2478f8ba1e97 --shard=0 --metrics-server=true --metrics-server-address=0.0.0.0 --metrics-server-port=37415 --metrics-logging=true --relay=false --discv5-bootstrap-node=enr:-LO4QNbWeM84tplR_OoCB64m1QWBVjqEV3rETcUsmjvOoq0yANVk7SsueDsiuovy60NOCI76u3Iz7MAtJZGhw9XoqTEBgmlkgnY0gmlwhKwSIXqKbXVsdGlhZGRyc4wACgSsEiF6BnwM3QOCcnOFAAMBAACJc2VjcDI1NmsxoQIL9u7G8cShiUVlCxCLxS2OigrLAZIB0MUNPUv2h9hn1IN0Y3CCfAuDdWRwgnwNhXdha3UyBQ --filternode=/ip4/172.18.33.122/tcp/31755/p2p/16Uiu2HAkvENrSWpBso1ggCask2UttBiMNJsrHP3E9A5UQsBiX1Uw
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:53 docker network connect --ip 172.18.91.156 waku ad0ef64398b041904ded93e2284944d3c7349caa5ef6ee749ca37fdb67fa5143
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:56 Container started with ID ad0ef64398b0. Setting up logs at ./log/docker/node2_2024-08-22_04-17-41__0a964158-3f0b-497f-90df-e18f22987c89__wakuorg_nwaku:latest.log
[35mDEBUG   [0m src.node.waku_node:waku_node.py:176 Started container from image wakuorg/nwaku:latest. REST: 37411
[35mDEBUG   [0m src.libs.common:common.py:35 Sleeping for 1 seconds
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X GET "http://127.0.0.1:37411/health" -H "Content-Type: application/json" -d 'None'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'{"nodeHealth":"Ready","protocolsHealth":[]}'
[32mINFO    [0m src.node.waku_node:waku_node.py:276 Node protocols are initialized !!
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X GET "http://127.0.0.1:37411/debug/v1/info" -H "Content-Type: application/json" -d 'None'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'{"listenAddresses":["/ip4/172.18.91.156/tcp/37412/p2p/16Uiu2HAmGyFqamh26PATTM7cvVLGHYcEK7eBE7R4eQCfZ8bBfnL1","/ip4/172.18.91.156/tcp/37413/ws/p2p/16Uiu2HAmGyFqamh26PATTM7cvVLGHYcEK7eBE7R4eQCfZ8bBfnL1"],"enrUri":"enr:-LO4QGNI6aq0BEnXuQ_mxnXMId1aA5-Crm_6-HDiUOGOcAgkM2gI8pA4KHxy8dqWDArRBCdpZfL0-l8dC-1YzRHjQIcBgmlkgnY0gmlwhKwSW5yKbXVsdGlhZGRyc4wACgSsElucBpIl3QOCcnOFAAMBAACJc2VjcDI1NmsxoQNAHLbinv-0MvEQV8n7wgSR7maGgJaZXeKx65RW2DuLMoN0Y3CCkiSDdWRwgpImhXdha3UyAA"}'
[32mINFO    [0m src.node.waku_node:waku_node.py:281 REST service is ready !!
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X POST "http://127.0.0.1:37411/admin/v1/peers" -H "Content-Type: application/json" -d '["/ip4/172.18.33.122/tcp/31755/p2p/16Uiu2HAkvENrSWpBso1ggCask2UttBiMNJsrHP3E9A5UQsBiX1Uw"]'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'OK'
[35mDEBUG   [0m src.steps.filter:filter.py:47 Running fixture setup: subscribe_main_nodes
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X POST "http://127.0.0.1:31754/relay/v1/subscriptions" -H "Content-Type: application/json" -d '["/waku/2/rs/3/1"]'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'OK'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X POST "http://127.0.0.1:37411/filter/v2/subscriptions" -H "Content-Type: application/json" -d '{"requestId": "86a0a6a4-caec-4f2c-9173-101660cc06ba", "contentFilters": ["/test/1/waku-filter/proto"], "pubsubTopic": "/waku/2/rs/3/1"}'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'{"requestId":"86a0a6a4-caec-4f2c-9173-101660cc06ba","statusDesc":"OK"}'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X PUT "http://127.0.0.1:37411/filter/v2/subscriptions" -H "Content-Type: application/json" -d '{"contentFilters": ["/test/1/waku-filter/proto"], "pubsubTopic": "/waku/2/rs/3/1"}'
[1m[31mERROR   [0m src.node.api_clients.base_client:base_client.py:16 HTTP error occurred: 400 Client Error: Bad Request for url: http://127.0.0.1:37411/filter/v2/subscriptions. Response content: b'{"requestId":"unknown","statusDesc":"BAD_REQUEST: Failed to decode request: (status: 400 Bad Request, headers: , kind: Error, errobj: (status: 400 Bad Request, message: \\"Invalid content body, could not decode. Unable to deserialize data\\", contentType: \\"text/plain\\"))"}'
[35mDEBUG   [0m tests.conftest:conftest.py:59 Running fixture teardown: test_setup
[35mDEBUG   [0m tests.conftest:conftest.py:83 Running fixture teardown: close_open_nodes
[35mDEBUG   [0m src.node.waku_node:waku_node.py:220 Stopping container with id 320b820aa4ce
[35mDEBUG   [0m src.node.waku_node:waku_node.py:227 Container stopped.
[35mDEBUG   [0m src.node.waku_node:waku_node.py:220 Stopping container with id ad0ef64398b0
[35mDEBUG   [0m src.node.waku_node:waku_node.py:227 Container stopped.