[35mDEBUG   [0m tests.conftest:conftest.py:51 Running fixture setup: test_id
[35mDEBUG   [0m tests.conftest:conftest.py:57 Running test: test_store_with_invalid_hash with id: 2024-10-08_04-36-56__fa675e61-d787-4710-ba13-0ce8113f5d10
[35mDEBUG   [0m src.steps.common:common.py:17 Running fixture setup: common_setup
[35mDEBUG   [0m src.steps.store:store.py:31 Running fixture setup: store_setup
[35mDEBUG   [0m src.steps.store:store.py:39 Running fixture setup: node_setup
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:18 Docker client initialized with image wakuorg/nwaku:latest
[35mDEBUG   [0m src.node.waku_node:waku_node.py:85 WakuNode instance initialized with log path ./log/docker/publishing_node1_2024-10-08_04-36-56__fa675e61-d787-4710-ba13-0ce8113f5d10__wakuorg_nwaku:latest.log
[35mDEBUG   [0m src.node.waku_node:waku_node.py:89 Starting Node...
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:21 Attempting to create or retrieve network waku
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:24 Network waku already exists
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:81 Generated random external IP 172.18.102.207
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:74 Generated ports ['28716', '28717', '28718', '28719', '28720']
[35mDEBUG   [0m src.node.waku_node:waku_node.py:434 RLN credentials were not set
[32mINFO    [0m src.node.waku_node:waku_node.py:163 RLN credentials not set or credential store not available, starting without RLN
[35mDEBUG   [0m src.node.waku_node:waku_node.py:165 Using volumes []
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:48 docker run -i -t -p 28716:28716 -p 28717:28717 -p 28718:28718 -p 28719:28719 -p 28720:28720 wakuorg/nwaku:latest --listen-address=0.0.0.0 --rest=true --rest-admin=true --websocket-support=true --log-level=TRACE --rest-relay-cache-capacity=100 --websocket-port=28718 --rest-port=28716 --tcp-port=28717 --discv5-udp-port=28719 --rest-address=0.0.0.0 --nat=extip:172.18.102.207 --peer-exchange=true --discv5-discovery=true --cluster-id=3 --nodekey=ecdfcfbe4f4a0bf87decaba92e5eb773dcbf6646eb8f1a5cfaff59c654c20856 --shard=0 --metrics-server=true --metrics-server-address=0.0.0.0 --metrics-server-port=28720 --metrics-logging=true --store=true --relay=true
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:54 docker network connect --ip 172.18.102.207 waku 250b03887d64bbb338b226e05e854c9f24df9a47520303de2c71a304d474bea5
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:57 Container started with ID 250b03887d64. Setting up logs at ./log/docker/publishing_node1_2024-10-08_04-36-56__fa675e61-d787-4710-ba13-0ce8113f5d10__wakuorg_nwaku:latest.log
[35mDEBUG   [0m src.node.waku_node:waku_node.py:177 Started container from image wakuorg/nwaku:latest. REST: 28716
[35mDEBUG   [0m src.libs.common:common.py:35 Sleeping for 1 seconds
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X GET "http://127.0.0.1:28716/health" -H "Content-Type: application/json" -d 'None'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'{"nodeHealth":"Ready","protocolsHealth":[]}'
[32mINFO    [0m src.node.waku_node:waku_node.py:277 Node protocols are initialized !!
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X GET "http://127.0.0.1:28716/debug/v1/info" -H "Content-Type: application/json" -d 'None'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'{"listenAddresses":["/ip4/172.18.102.207/tcp/28717/p2p/16Uiu2HAmCCQ6yBnzSMRCv2g7XbGfRFw2kGssZjsAs1dHfW5NNmCP","/ip4/172.18.102.207/tcp/28718/ws/p2p/16Uiu2HAmCCQ6yBnzSMRCv2g7XbGfRFw2kGssZjsAs1dHfW5NNmCP"],"enrUri":"enr:-LO4QMgscM9bImbV2cT0yWO_riASnEa-yKIC-aQSI0JT4Pe6F60VrA6cjg6DWaXomOwPHWeklHJ05Qw_E3ML1lq-1IUBgmlkgnY0gmlwhKwSZs-KbXVsdGlhZGRyc4wACgSsEmbPBnAu3QOCcnOFAAMBAACJc2VjcDI1NmsxoQL5MC0FsgS5-q_rVqovyDXXbbovyhJWUbU-9dm5upHPHIN0Y3CCcC2DdWRwgnAvhXdha3UyAw"}'
[32mINFO    [0m src.node.waku_node:waku_node.py:282 REST service is ready !!
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:18 Docker client initialized with image wakuorg/nwaku:latest
[35mDEBUG   [0m src.node.waku_node:waku_node.py:85 WakuNode instance initialized with log path ./log/docker/store_node1_2024-10-08_04-36-56__fa675e61-d787-4710-ba13-0ce8113f5d10__wakuorg_nwaku:latest.log
[35mDEBUG   [0m src.node.waku_node:waku_node.py:89 Starting Node...
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:21 Attempting to create or retrieve network waku
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:24 Network waku already exists
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:81 Generated random external IP 172.18.44.225
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:74 Generated ports ['58599', '58600', '58601', '58602', '58603']
[35mDEBUG   [0m src.node.waku_node:waku_node.py:434 RLN credentials were not set
[32mINFO    [0m src.node.waku_node:waku_node.py:163 RLN credentials not set or credential store not available, starting without RLN
[35mDEBUG   [0m src.node.waku_node:waku_node.py:165 Using volumes []
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:48 docker run -i -t -p 58599:58599 -p 58600:58600 -p 58601:58601 -p 58602:58602 -p 58603:58603 wakuorg/nwaku:latest --listen-address=0.0.0.0 --rest=true --rest-admin=true --websocket-support=true --log-level=TRACE --rest-relay-cache-capacity=100 --websocket-port=58601 --rest-port=58599 --tcp-port=58600 --discv5-udp-port=58602 --rest-address=0.0.0.0 --nat=extip:172.18.44.225 --peer-exchange=true --discv5-discovery=true --cluster-id=3 --nodekey=ff22cd58218ed9c68f0d4a5e3b1ffeb5d6e17b4fdabd7fa8d2be8bffbd3bbff8 --shard=0 --metrics-server=true --metrics-server-address=0.0.0.0 --metrics-server-port=58603 --metrics-logging=true --discv5-bootstrap-node=enr:-LO4QMgscM9bImbV2cT0yWO_riASnEa-yKIC-aQSI0JT4Pe6F60VrA6cjg6DWaXomOwPHWeklHJ05Qw_E3ML1lq-1IUBgmlkgnY0gmlwhKwSZs-KbXVsdGlhZGRyc4wACgSsEmbPBnAu3QOCcnOFAAMBAACJc2VjcDI1NmsxoQL5MC0FsgS5-q_rVqovyDXXbbovyhJWUbU-9dm5upHPHIN0Y3CCcC2DdWRwgnAvhXdha3UyAw --storenode=/ip4/172.18.102.207/tcp/28717/p2p/16Uiu2HAmCCQ6yBnzSMRCv2g7XbGfRFw2kGssZjsAs1dHfW5NNmCP --store=true --relay=true
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:54 docker network connect --ip 172.18.44.225 waku 64aa1e1e6e39a97b22fccec29acbf660a227c149015baa37fb4d2264b2a62882
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:57 Container started with ID 64aa1e1e6e39. Setting up logs at ./log/docker/store_node1_2024-10-08_04-36-56__fa675e61-d787-4710-ba13-0ce8113f5d10__wakuorg_nwaku:latest.log
[35mDEBUG   [0m src.node.waku_node:waku_node.py:177 Started container from image wakuorg/nwaku:latest. REST: 58599
[35mDEBUG   [0m src.libs.common:common.py:35 Sleeping for 1 seconds
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X GET "http://127.0.0.1:58599/health" -H "Content-Type: application/json" -d 'None'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'{"nodeHealth":"Ready","protocolsHealth":[]}'
[32mINFO    [0m src.node.waku_node:waku_node.py:277 Node protocols are initialized !!
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X GET "http://127.0.0.1:58599/debug/v1/info" -H "Content-Type: application/json" -d 'None'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'{"listenAddresses":["/ip4/172.18.44.225/tcp/58600/p2p/16Uiu2HAmFPncUke56AQ6nbM24S8iY2a6VYbRRkBz4PdUz8uBbtjD","/ip4/172.18.44.225/tcp/58601/ws/p2p/16Uiu2HAmFPncUke56AQ6nbM24S8iY2a6VYbRRkBz4PdUz8uBbtjD"],"enrUri":"enr:-LO4QFHcm6bjBhRwqBkiTivVFtsvs-xRCYUdBmIMw4ITOxNEJHc9TbS-I-Yu2IEX4WcNgC6OK7pH-yp9DoYjoB5aJdgBgmlkgnY0gmlwhKwSLOGKbXVsdGlhZGRyc4wACgSsEizhBuTp3QOCcnOFAAMBAACJc2VjcDI1NmsxoQMorhOJcPgVCYo2p4GDpo18xSVWiw6tWAyRv4AYD0_NbIN0Y3CC5OiDdWRwguTqhXdha3UyAw"}'
[32mINFO    [0m src.node.waku_node:waku_node.py:282 REST service is ready !!
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X POST "http://127.0.0.1:58599/admin/v1/peers" -H "Content-Type: application/json" -d '["/ip4/172.18.102.207/tcp/28717/p2p/16Uiu2HAmCCQ6yBnzSMRCv2g7XbGfRFw2kGssZjsAs1dHfW5NNmCP"]'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'OK'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X POST "http://127.0.0.1:28716/relay/v1/subscriptions" -H "Content-Type: application/json" -d '["/waku/2/rs/3/0"]'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'OK'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X POST "http://127.0.0.1:58599/relay/v1/subscriptions" -H "Content-Type: application/json" -d '["/waku/2/rs/3/0"]'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'OK'
[35mDEBUG   [0m src.steps.store:store.py:132 Relaying message
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X POST "http://127.0.0.1:28716/relay/v1/messages/%2Fwaku%2F2%2Frs%2F3%2F0" -H "Content-Type: application/json" -d '{"payload": "TWVzc2FnZV8w", "contentTopic": "/myapp/1/latest/proto", "timestamp": '$(date +%s%N)'}'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'OK'
[35mDEBUG   [0m src.libs.common:common.py:35 Sleeping for 0.2 seconds
[35mDEBUG   [0m src.steps.store:store.py:132 Relaying message
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X POST "http://127.0.0.1:28716/relay/v1/messages/%2Fwaku%2F2%2Frs%2F3%2F0" -H "Content-Type: application/json" -d '{"payload": "TWVzc2FnZV8x", "contentTopic": "/myapp/1/latest/proto", "timestamp": '$(date +%s%N)'}'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'OK'
[35mDEBUG   [0m src.libs.common:common.py:35 Sleeping for 0.2 seconds
[35mDEBUG   [0m src.steps.store:store.py:132 Relaying message
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X POST "http://127.0.0.1:28716/relay/v1/messages/%2Fwaku%2F2%2Frs%2F3%2F0" -H "Content-Type: application/json" -d '{"payload": "TWVzc2FnZV8y", "contentTopic": "/myapp/1/latest/proto", "timestamp": '$(date +%s%N)'}'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'OK'
[35mDEBUG   [0m src.libs.common:common.py:35 Sleeping for 0.2 seconds
[35mDEBUG   [0m src.steps.store:store.py:132 Relaying message
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X POST "http://127.0.0.1:28716/relay/v1/messages/%2Fwaku%2F2%2Frs%2F3%2F0" -H "Content-Type: application/json" -d '{"payload": "TWVzc2FnZV8z", "contentTopic": "/myapp/1/latest/proto", "timestamp": '$(date +%s%N)'}'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'OK'
[35mDEBUG   [0m src.libs.common:common.py:35 Sleeping for 0.2 seconds
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X GET "http://127.0.0.1:28716/store/v3/messages?pubsubTopic=%2Fwaku%2F2%2Frs%2F3%2F0&hashes=dGVzdA%3D%3D&pageSize=50&ascending=true" -H "Content-Type: application/json" -d 'None'
[31m[1mERROR   [0m src.node.api_clients.base_client:base_client.py:16 HTTP error occurred: 400 Client Error: Bad Request for url: http://127.0.0.1:28716/store/v3/messages?pubsubTopic=%2Fwaku%2F2%2Frs%2F3%2F0&hashes=dGVzdA%3D%3D&pageSize=50&ascending=true. Response content: b'waku message hash parsing error: invalid hash length: 4'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X GET "http://127.0.0.1:58599/store/v3/messages?pubsubTopic=%2Fwaku%2F2%2Frs%2F3%2F0&hashes=dGVzdA%3D%3D&pageSize=50&ascending=true" -H "Content-Type: application/json" -d 'None'
[31m[1mERROR   [0m src.node.api_clients.base_client:base_client.py:16 HTTP error occurred: 400 Client Error: Bad Request for url: http://127.0.0.1:58599/store/v3/messages?pubsubTopic=%2Fwaku%2F2%2Frs%2F3%2F0&hashes=dGVzdA%3D%3D&pageSize=50&ascending=true. Response content: b'waku message hash parsing error: invalid hash length: 4'
[35mDEBUG   [0m tests.conftest:conftest.py:59 Running fixture teardown: test_setup
[35mDEBUG   [0m tests.conftest:conftest.py:83 Running fixture teardown: close_open_nodes
[35mDEBUG   [0m src.node.waku_node:waku_node.py:221 Stopping container with id 250b03887d64
[35mDEBUG   [0m src.node.waku_node:waku_node.py:228 Container stopped.
[35mDEBUG   [0m src.node.waku_node:waku_node.py:221 Stopping container with id 64aa1e1e6e39
[35mDEBUG   [0m src.node.waku_node:waku_node.py:228 Container stopped.
[35mDEBUG   [0m tests.conftest:conftest.py:98 Running fixture teardown: check_waku_log_errors
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:117 No errors found in the waku logs.
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:117 No errors found in the waku logs.