[35mDEBUG   [0m tests.conftest:conftest.py:51 Running fixture setup: test_id
[35mDEBUG   [0m tests.conftest:conftest.py:57 Running test: test_filter_unsubscribe_with_no_pubsub_topic with id: 2024-10-29_03-13-11__a89f0a37-2df3-49a3-bfb0-28b16dfa28c9
[35mDEBUG   [0m src.steps.common:common.py:18 Running fixture setup: common_setup
[35mDEBUG   [0m src.steps.filter:filter.py:28 Running fixture setup: filter_setup
[35mDEBUG   [0m src.steps.filter:filter.py:34 Running fixture setup: setup_main_relay_node
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:19 Docker client initialized with image wakuorg/nwaku:latest
[35mDEBUG   [0m src.node.waku_node:waku_node.py:85 WakuNode instance initialized with log path ./log/docker/node1_2024-10-29_03-13-11__a89f0a37-2df3-49a3-bfb0-28b16dfa28c9__wakuorg_nwaku:latest.log
[35mDEBUG   [0m src.node.waku_node:waku_node.py:89 Starting Node...
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:22 Attempting to create or retrieve network waku
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:25 Network waku already exists
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:108 Generated random external IP 172.18.194.21
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:101 Generated ports ['40327', '40328', '40329', '40330', '40331']
[35mDEBUG   [0m src.node.waku_node:waku_node.py:434 RLN credentials were not set
[32mINFO    [0m src.node.waku_node:waku_node.py:163 RLN credentials not set or credential store not available, starting without RLN
[35mDEBUG   [0m src.node.waku_node:waku_node.py:165 Using volumes []
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:49 docker run -i -t -p 40327:40327 -p 40328:40328 -p 40329:40329 -p 40330:40330 -p 40331:40331 wakuorg/nwaku:latest --listen-address=0.0.0.0 --rest=true --rest-admin=true --websocket-support=true --log-level=TRACE --rest-relay-cache-capacity=100 --websocket-port=40329 --rest-port=40327 --tcp-port=40328 --discv5-udp-port=40330 --rest-address=0.0.0.0 --nat=extip:172.18.194.21 --peer-exchange=true --discv5-discovery=true --cluster-id=3 --nodekey=83d9eadeaa3b407b777a4b8bad0ade5df24106074ed76d9d8e47552ff3c51cf4 --shard=0 --metrics-server=true --metrics-server-address=0.0.0.0 --metrics-server-port=40331 --metrics-logging=true --relay=true --filter=true
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:55 docker network connect --ip 172.18.194.21 waku c5cb69e49a21b43fc952fc2467eaeec6156ceff791627e0e90f232351dc1d338
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:58 Container started with ID c5cb69e49a21. Setting up logs at ./log/docker/node1_2024-10-29_03-13-11__a89f0a37-2df3-49a3-bfb0-28b16dfa28c9__wakuorg_nwaku:latest.log
[35mDEBUG   [0m src.node.waku_node:waku_node.py:177 Started container from image wakuorg/nwaku:latest. REST: 40327
[35mDEBUG   [0m src.libs.common:common.py:35 Sleeping for 1 seconds
[31m[1mERROR   [0m src.node.docker_mananger:docker_mananger.py:89 Max retries reached for container 304d8c84cb64. Exiting log stream.
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X GET "http://127.0.0.1:40327/health" -H "Content-Type: application/json" -d 'None'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'{"nodeHealth":"Ready","protocolsHealth":[]}'
[32mINFO    [0m src.node.waku_node:waku_node.py:277 Node protocols are initialized !!
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X GET "http://127.0.0.1:40327/debug/v1/info" -H "Content-Type: application/json" -d 'None'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'{"listenAddresses":["/ip4/172.18.194.21/tcp/40328/p2p/16Uiu2HAmQUeE8YdY8ZeKYSZEMD7GScGieWNG8mAhkBGuUPMN6uXo","/ip4/172.18.194.21/tcp/40329/ws/p2p/16Uiu2HAmQUeE8YdY8ZeKYSZEMD7GScGieWNG8mAhkBGuUPMN6uXo"],"enrUri":"enr:-L24QPND3_ibD5D4jVGM9YtrU7cUYWHhx2idXO1kNxkeg0brM6D6BDvGcUsXBLbIrrzkn9pUwqI0fCqYyaPuBkh7CaMCgmlkgnY0gmlwhKwSwhWKbXVsdGlhZGRyc5YACASsEsIVBp2IAAoErBLCFQadid0DgnJzhQADAQAAiXNlY3AyNTZrMaEDr6Wub5ToCucqPySZhy1NyzmjgYSSEp6mqN2mYPq31uKDdGNwgp2Ig3VkcIKdioV3YWt1MgU"}'
[32mINFO    [0m src.node.waku_node:waku_node.py:282 REST service is ready !!
[35mDEBUG   [0m src.steps.filter:filter.py:39 Running fixture setup: setup_main_filter_node
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:19 Docker client initialized with image wakuorg/go-waku:latest
[35mDEBUG   [0m src.node.waku_node:waku_node.py:85 WakuNode instance initialized with log path ./log/docker/node2_2024-10-29_03-13-11__a89f0a37-2df3-49a3-bfb0-28b16dfa28c9__wakuorg_go-waku:latest.log
[35mDEBUG   [0m src.node.waku_node:waku_node.py:89 Starting Node...
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:22 Attempting to create or retrieve network waku
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:25 Network waku already exists
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:108 Generated random external IP 172.18.42.111
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:101 Generated ports ['53140', '53141', '53142', '53143', '53144']
[35mDEBUG   [0m src.node.waku_node:waku_node.py:434 RLN credentials were not set
[32mINFO    [0m src.node.waku_node:waku_node.py:163 RLN credentials not set or credential store not available, starting without RLN
[35mDEBUG   [0m src.node.waku_node:waku_node.py:165 Using volumes []
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:49 docker run -i -t -p 53140:53140 -p 53141:53141 -p 53142:53142 -p 53143:53143 -p 53144:53144 wakuorg/go-waku:latest --listen-address=0.0.0.0 --rest=true --rest-admin=true --websocket-support=true --log-level=DEBUG --rest-relay-cache-capacity=100 --websocket-port=53142 --rest-port=53140 --tcp-port=53141 --discv5-udp-port=53143 --rest-address=0.0.0.0 --nat=extip:172.18.42.111 --peer-exchange=true --discv5-discovery=true --cluster-id=3 --nodekey=e4bd4ec8febab7c8ccddfa1aa1b91e18eceffb8d1ae9dfb05039608777af69ee --min-relay-peers-to-publish=1 --rest-filter-cache-capacity=50 --peer-store-capacity=10 --relay=false --discv5-bootstrap-node=enr:-L24QPND3_ibD5D4jVGM9YtrU7cUYWHhx2idXO1kNxkeg0brM6D6BDvGcUsXBLbIrrzkn9pUwqI0fCqYyaPuBkh7CaMCgmlkgnY0gmlwhKwSwhWKbXVsdGlhZGRyc5YACASsEsIVBp2IAAoErBLCFQadid0DgnJzhQADAQAAiXNlY3AyNTZrMaEDr6Wub5ToCucqPySZhy1NyzmjgYSSEp6mqN2mYPq31uKDdGNwgp2Ig3VkcIKdioV3YWt1MgU --filternode=/ip4/172.18.194.21/tcp/40328/p2p/16Uiu2HAmQUeE8YdY8ZeKYSZEMD7GScGieWNG8mAhkBGuUPMN6uXo
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:55 docker network connect --ip 172.18.42.111 waku 9b199a32d73df361ab874b251a11aed6711bf01150d2eaf980eefaf0f7206865
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:58 Container started with ID 9b199a32d73d. Setting up logs at ./log/docker/node2_2024-10-29_03-13-11__a89f0a37-2df3-49a3-bfb0-28b16dfa28c9__wakuorg_go-waku:latest.log
[35mDEBUG   [0m src.node.waku_node:waku_node.py:177 Started container from image wakuorg/go-waku:latest. REST: 53140
[35mDEBUG   [0m src.libs.common:common.py:35 Sleeping for 1 seconds
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X GET "http://127.0.0.1:53140/debug/v1/info" -H "Content-Type: application/json" -d 'None'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'{"enrUri":"enr:-Ji4QCouFHPaOH2R1cbaZ6vVCi0ddYDNf502ZV0B1PpF1ZszCW2RGLY3KMMzkyleANuW1_v9iZutdKtH0DuofwgQOgCGAZLWQ2PDgmlkgnY0gmlwhKwRAAaJc2VjcDI1NmsxoQKXTC_beXslRjWvMrhNXHtUUkjeM32eQonmY7HDFSghZIN0Y3CCz5WDdWRwgs-XhXdha3UygA","listenAddresses":["/ip4/127.0.0.1/tcp/53141/p2p/16Uiu2HAm5cGvTUrXVx1FJwwYdLRgMRbTvRL1o6RdmAd68da7SkqH","/ip4/127.0.0.1/tcp/53142/ws/p2p/16Uiu2HAm5cGvTUrXVx1FJwwYdLRgMRbTvRL1o6RdmAd68da7SkqH","/ip4/172.17.0.6/tcp/53141/p2p/16Uiu2HAm5cGvTUrXVx1FJwwYdLRgMRbTvRL1o6RdmAd68da7SkqH","/ip4/172.17.0.6/tcp/53142/ws/p2p/16Uiu2HAm5cGvTUrXVx1FJwwYdLRgMRbTvRL1o6RdmAd68da7SkqH"]}'
[32mINFO    [0m src.node.waku_node:waku_node.py:282 REST service is ready !!
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X POST "http://127.0.0.1:53140/admin/v1/peers" -H "Content-Type: application/json" -d '{"multiaddr": "/ip4/172.18.194.21/tcp/40328/p2p/16Uiu2HAmQUeE8YdY8ZeKYSZEMD7GScGieWNG8mAhkBGuUPMN6uXo", "protocols": ["/vac/waku/relay/2.0.0"], "shards": [0, 1, 2, 3, 4, 5, 6, 7, 8]}'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'null'
[35mDEBUG   [0m src.steps.filter:filter.py:47 Running fixture setup: subscribe_main_nodes
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X POST "http://127.0.0.1:40327/relay/v1/subscriptions" -H "Content-Type: application/json" -d '["/waku/2/rs/3/1"]'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'OK'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X POST "http://127.0.0.1:53140/filter/v2/subscriptions" -H "Content-Type: application/json" -d '{"requestId": "a579775e-7a31-4745-a2aa-25ce8424260c", "contentFilters": ["/test/1/waku-filter/proto"], "pubsubTopic": "/waku/2/rs/3/1"}'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'{"requestId":"a579775e-7a31-4745-a2aa-25ce8424260c","statusDesc":"OK"}'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X DELETE "http://127.0.0.1:53140/filter/v2/subscriptions" -H "Content-Type: application/json" -d '{"requestId": "1", "contentFilters": "/test/1/waku-filter/proto"}'
[31m[1mERROR   [0m src.node.api_clients.base_client:base_client.py:16 HTTP error occurred: 400 Client Error: Bad Request for url: http://127.0.0.1:53140/filter/v2/subscriptions. Response content: b''
[35mDEBUG   [0m tests.conftest:conftest.py:59 Running fixture teardown: test_setup
[35mDEBUG   [0m tests.conftest:conftest.py:83 Running fixture teardown: close_open_nodes
[35mDEBUG   [0m src.node.waku_node:waku_node.py:221 Stopping container with id c5cb69e49a21
[35mDEBUG   [0m src.node.waku_node:waku_node.py:228 Container stopped.
[35mDEBUG   [0m src.node.waku_node:waku_node.py:221 Stopping container with id 9b199a32d73d
[31m[1mERROR   [0m src.node.docker_mananger:docker_mananger.py:89 Max retries reached for container c5cb69e49a21. Exiting log stream.
[35mDEBUG   [0m src.node.waku_node:waku_node.py:228 Container stopped.
[35mDEBUG   [0m tests.conftest:conftest.py:98 Running fixture teardown: check_waku_log_errors
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:144 No errors found in the waku logs.
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:144 No errors found in the waku logs.