[35mDEBUG   [0m tests.conftest:conftest.py:43 Running fixture setup: test_id
[35mDEBUG   [0m tests.conftest:conftest.py:49 Running test: test_2_lightpush_nodes_and_1_receiving_node with id: 2024-04-16_04-14-48__926840c0-3488-4c61-ad21-a5a19eba8d13
[35mDEBUG   [0m src.steps.light_push:light_push.py:28 Running fixture setup: light_push_setup
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:17 Docker client initialized with image harbor.status.im/wakuorg/nwaku:latest
[35mDEBUG   [0m src.node.waku_node:waku_node.py:50 WakuNode instance initialized with log path ./log/docker/receiving_node1_2024-04-16_04-14-48__926840c0-3488-4c61-ad21-a5a19eba8d13__harbor.status.im_wakuorg_nwaku:latest.log
[35mDEBUG   [0m src.node.waku_node:waku_node.py:54 Starting Node...
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:20 Attempting to create or retrieve network waku
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:23 Network waku already exists
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:80 Generated random external IP 172.18.155.3
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:73 Generated ports ['30885', '30886', '30887', '30888', '30889']
[35mDEBUG   [0m src.node.waku_node:waku_node.py:297 RLN credentials were not set
[32mINFO    [0m src.node.waku_node:waku_node.py:115 RLN credentials not set or credential store not available, starting without RLN
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:47 docker run -i -t -p 30885:30885 -p 30886:30886 -p 30887:30887 -p 30888:30888 -p 30889:30889 harbor.status.im/wakuorg/nwaku:latest --listen-address=0.0.0.0 --rest=true --rest-admin=true --websocket-support=true --log-level=TRACE --rest-relay-cache-capacity=100 --websocket-port=30887 --rest-port=30885 --tcp-port=30886 --discv5-udp-port=30888 --rest-address=0.0.0.0 --nat=extip:172.18.155.3 --peer-exchange=true --discv5-discovery=true --cluster-id=0 --metrics-server=true --metrics-server-address=0.0.0.0 --metrics-server-port=30889 --metrics-logging=true --lightpush=true --relay=true
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:53 docker network connect --ip 172.18.155.3 waku 5acb101dd5a595046fd6ab679cd72feb0ec6e8c23ae021e7e00ad91adb7781b3
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:56 Container started with ID 5acb101dd5a5. Setting up logs at ./log/docker/receiving_node1_2024-04-16_04-14-48__926840c0-3488-4c61-ad21-a5a19eba8d13__harbor.status.im_wakuorg_nwaku:latest.log
[35mDEBUG   [0m src.node.waku_node:waku_node.py:121 Started container from image harbor.status.im/wakuorg/nwaku:latest. REST: 30885
[35mDEBUG   [0m src.libs.common:common.py:35 Sleeping for 1 seconds
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X GET "http://127.0.0.1:30885/debug/v1/info" -H "Content-Type: application/json" -d 'None'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'{"listenAddresses":["/ip4/172.18.155.3/tcp/30886/p2p/16Uiu2HAmJKuw7yUNzwzmYQatd8rinf6mhwr84UEoYNXfAb4hDBw1","/ip4/172.18.155.3/tcp/30887/ws/p2p/16Uiu2HAmJKuw7yUNzwzmYQatd8rinf6mhwr84UEoYNXfAb4hDBw1"],"enrUri":"enr:-LO4QP6fuysMiBSHpwi6AnlTEd4E3YqtaDfr-9jxIX4YUjk9QxrGrtu2lZcDcgc9EoFC1B58DpuF75Eq1mWjZ3JbNJYBgmlkgnY0gmlwhKwSmwOKbXVsdGlhZGRyc4wACgSsEpsDBnin3QOCcnOFAAABAACJc2VjcDI1NmsxoQNUQxeamLp-AMoK4M4diTIk44q5viDuodK_NK1c50PF5IN0Y3CCeKaDdWRwgniohXdha3UyCQ"}'
[32mINFO    [0m src.node.waku_node:waku_node.py:191 REST service is ready !!
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:17 Docker client initialized with image harbor.status.im/wakuorg/nwaku:latest
[35mDEBUG   [0m src.node.waku_node:waku_node.py:50 WakuNode instance initialized with log path ./log/docker/lightpush_node1_2024-04-16_04-14-48__926840c0-3488-4c61-ad21-a5a19eba8d13__harbor.status.im_wakuorg_nwaku:latest.log
[35mDEBUG   [0m src.node.waku_node:waku_node.py:54 Starting Node...
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:20 Attempting to create or retrieve network waku
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:23 Network waku already exists
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:80 Generated random external IP 172.18.188.77
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:73 Generated ports ['12350', '12351', '12352', '12353', '12354']
[35mDEBUG   [0m src.node.waku_node:waku_node.py:297 RLN credentials were not set
[32mINFO    [0m src.node.waku_node:waku_node.py:115 RLN credentials not set or credential store not available, starting without RLN
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:47 docker run -i -t -p 12350:12350 -p 12351:12351 -p 12352:12352 -p 12353:12353 -p 12354:12354 harbor.status.im/wakuorg/nwaku:latest --listen-address=0.0.0.0 --rest=true --rest-admin=true --websocket-support=true --log-level=TRACE --rest-relay-cache-capacity=100 --websocket-port=12352 --rest-port=12350 --tcp-port=12351 --discv5-udp-port=12353 --rest-address=0.0.0.0 --nat=extip:172.18.188.77 --peer-exchange=true --discv5-discovery=true --cluster-id=0 --metrics-server=true --metrics-server-address=0.0.0.0 --metrics-server-port=12354 --metrics-logging=true --discv5-bootstrap-node=enr:-LO4QP6fuysMiBSHpwi6AnlTEd4E3YqtaDfr-9jxIX4YUjk9QxrGrtu2lZcDcgc9EoFC1B58DpuF75Eq1mWjZ3JbNJYBgmlkgnY0gmlwhKwSmwOKbXVsdGlhZGRyc4wACgSsEpsDBnin3QOCcnOFAAABAACJc2VjcDI1NmsxoQNUQxeamLp-AMoK4M4diTIk44q5viDuodK_NK1c50PF5IN0Y3CCeKaDdWRwgniohXdha3UyCQ --lightpushnode=/ip4/172.18.155.3/tcp/30886/p2p/16Uiu2HAmJKuw7yUNzwzmYQatd8rinf6mhwr84UEoYNXfAb4hDBw1 --lightpush=true --relay=false
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:53 docker network connect --ip 172.18.188.77 waku 909fbe8fce49cd8032c793f9f4c023dc71ed4758f222b98c7fc99e39e48b2de2
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:56 Container started with ID 909fbe8fce49. Setting up logs at ./log/docker/lightpush_node1_2024-04-16_04-14-48__926840c0-3488-4c61-ad21-a5a19eba8d13__harbor.status.im_wakuorg_nwaku:latest.log
[35mDEBUG   [0m src.node.waku_node:waku_node.py:121 Started container from image harbor.status.im/wakuorg/nwaku:latest. REST: 12350
[35mDEBUG   [0m src.libs.common:common.py:35 Sleeping for 1 seconds
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X GET "http://127.0.0.1:12350/debug/v1/info" -H "Content-Type: application/json" -d 'None'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'{"listenAddresses":["/ip4/172.18.188.77/tcp/12351/p2p/16Uiu2HAmJqdSNfiX9kSzMtwyue9JD7uuAYSoQwEPvtjFqegpnhu6","/ip4/172.18.188.77/tcp/12352/ws/p2p/16Uiu2HAmJqdSNfiX9kSzMtwyue9JD7uuAYSoQwEPvtjFqegpnhu6"],"enrUri":"enr:-LO4QHb-oEeYBuVGVOFp2Pe-A2hAK_86ls81bTgjzQDIQ-BUWWw1_TOQWIS2VEbMJWeOISeXO4jNYdb4bOBXsfKDRS8BgmlkgnY0gmlwhKwSvE2KbXVsdGlhZGRyc4wACgSsErxNBjBA3QOCcnOFAAABAACJc2VjcDI1NmsxoQNb391j0ZNfh5rfJB177grYuWc1SzpBC0Gv4wuqm63JBYN0Y3CCMD-DdWRwgjBBhXdha3UyCA"}'
[32mINFO    [0m src.node.waku_node:waku_node.py:191 REST service is ready !!
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X POST "http://127.0.0.1:12350/admin/v1/peers" -H "Content-Type: application/json" -d '["/ip4/172.18.155.3/tcp/30886/p2p/16Uiu2HAmJKuw7yUNzwzmYQatd8rinf6mhwr84UEoYNXfAb4hDBw1"]'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'OK'
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:17 Docker client initialized with image harbor.status.im/wakuorg/nwaku:latest
[35mDEBUG   [0m src.node.waku_node:waku_node.py:50 WakuNode instance initialized with log path ./log/docker/lightpush_node2_2024-04-16_04-14-48__926840c0-3488-4c61-ad21-a5a19eba8d13__harbor.status.im_wakuorg_nwaku:latest.log
[35mDEBUG   [0m src.node.waku_node:waku_node.py:54 Starting Node...
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:20 Attempting to create or retrieve network waku
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:23 Network waku already exists
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:80 Generated random external IP 172.18.124.151
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:73 Generated ports ['38633', '38634', '38635', '38636', '38637']
[35mDEBUG   [0m src.node.waku_node:waku_node.py:297 RLN credentials were not set
[32mINFO    [0m src.node.waku_node:waku_node.py:115 RLN credentials not set or credential store not available, starting without RLN
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:47 docker run -i -t -p 38633:38633 -p 38634:38634 -p 38635:38635 -p 38636:38636 -p 38637:38637 harbor.status.im/wakuorg/nwaku:latest --listen-address=0.0.0.0 --rest=true --rest-admin=true --websocket-support=true --log-level=TRACE --rest-relay-cache-capacity=100 --websocket-port=38635 --rest-port=38633 --tcp-port=38634 --discv5-udp-port=38636 --rest-address=0.0.0.0 --nat=extip:172.18.124.151 --peer-exchange=true --discv5-discovery=true --cluster-id=0 --metrics-server=true --metrics-server-address=0.0.0.0 --metrics-server-port=38637 --metrics-logging=true --discv5-bootstrap-node=enr:-LO4QP6fuysMiBSHpwi6AnlTEd4E3YqtaDfr-9jxIX4YUjk9QxrGrtu2lZcDcgc9EoFC1B58DpuF75Eq1mWjZ3JbNJYBgmlkgnY0gmlwhKwSmwOKbXVsdGlhZGRyc4wACgSsEpsDBnin3QOCcnOFAAABAACJc2VjcDI1NmsxoQNUQxeamLp-AMoK4M4diTIk44q5viDuodK_NK1c50PF5IN0Y3CCeKaDdWRwgniohXdha3UyCQ --lightpushnode=/ip4/172.18.155.3/tcp/30886/p2p/16Uiu2HAmJKuw7yUNzwzmYQatd8rinf6mhwr84UEoYNXfAb4hDBw1 --lightpush=true --relay=false
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:53 docker network connect --ip 172.18.124.151 waku d6f970cbe50a31b4dae27c3650598b24bbb323cb8489801817102cec346f3b44
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:56 Container started with ID d6f970cbe50a. Setting up logs at ./log/docker/lightpush_node2_2024-04-16_04-14-48__926840c0-3488-4c61-ad21-a5a19eba8d13__harbor.status.im_wakuorg_nwaku:latest.log
[35mDEBUG   [0m src.node.waku_node:waku_node.py:121 Started container from image harbor.status.im/wakuorg/nwaku:latest. REST: 38633
[35mDEBUG   [0m src.libs.common:common.py:35 Sleeping for 1 seconds
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X GET "http://127.0.0.1:38633/debug/v1/info" -H "Content-Type: application/json" -d 'None'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'{"listenAddresses":["/ip4/172.18.124.151/tcp/38634/p2p/16Uiu2HAkxykYRvm2cBwkKcfGRsJixqLUYVWqyweEEzEbDRqJud8Y","/ip4/172.18.124.151/tcp/38635/ws/p2p/16Uiu2HAkxykYRvm2cBwkKcfGRsJixqLUYVWqyweEEzEbDRqJud8Y"],"enrUri":"enr:-LO4QMZpiKCnpH64BlCYWeWo5YAR5ntpm2JX1Hg-c7emzQpgKvJH_GsKrYyoZVGe_Bhqygj_VvbdGklJn8zzpWK35dwBgmlkgnY0gmlwhKwSfJeKbXVsdGlhZGRyc4wACgSsEnyXBpbr3QOCcnOFAAABAACJc2VjcDI1NmsxoQI0ys5E-lzfZTFQVMYxqbvSpdKeCviIww_IioDCvbla9YN0Y3CCluqDdWRwgpbshXdha3UyCA"}'
[32mINFO    [0m src.node.waku_node:waku_node.py:191 REST service is ready !!
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X POST "http://127.0.0.1:38633/admin/v1/peers" -H "Content-Type: application/json" -d '["/ip4/172.18.155.3/tcp/30886/p2p/16Uiu2HAmJKuw7yUNzwzmYQatd8rinf6mhwr84UEoYNXfAb4hDBw1"]'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'OK'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X POST "http://127.0.0.1:30885/relay/v1/subscriptions" -H "Content-Type: application/json" -d '["/waku/2/rs/0/0"]'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'OK'
[35mDEBUG   [0m src.steps.light_push:light_push.py:127 Lightpushing message
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X POST "http://127.0.0.1:12350/lightpush/v1/message" -H "Content-Type: application/json" -d '{"pubsubTopic": "/waku/2/rs/0/0", "message": {"payload": "TGlnaHQgcHVzaCB3b3JrcyEh", "contentTopic": "/myapp/1/latest/proto", "timestamp": 1713240893468516608}}'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'OK'
[35mDEBUG   [0m src.libs.common:common.py:35 Sleeping for 0.1 seconds
[35mDEBUG   [0m src.steps.light_push:light_push.py:131 Checking that peer NODE_1:harbor.status.im/wakuorg/nwaku:latest can find the lightpushed message
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X GET "http://127.0.0.1:30885/relay/v1/messages/%2Fwaku%2F2%2Frs%2F0%2F0" -H "Content-Type: application/json" -d 'None'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'[{"payload":"TGlnaHQgcHVzaCB3b3JrcyEh","contentTopic":"/myapp/1/latest/proto","version":0,"timestamp":1713240893468516608,"ephemeral":false}]'
[35mDEBUG   [0m src.steps.light_push:light_push.py:127 Lightpushing message
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X POST "http://127.0.0.1:38633/lightpush/v1/message" -H "Content-Type: application/json" -d '{"pubsubTopic": "/waku/2/rs/0/0", "message": {"payload": "TGlnaHQgcHVzaCB3b3JrcyEh", "contentTopic": "/myapp/1/latest/proto", "timestamp": 1713240893582428672}}'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'OK'
[35mDEBUG   [0m src.libs.common:common.py:35 Sleeping for 0.1 seconds
[35mDEBUG   [0m src.steps.light_push:light_push.py:131 Checking that peer NODE_1:harbor.status.im/wakuorg/nwaku:latest can find the lightpushed message
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X GET "http://127.0.0.1:30885/relay/v1/messages/%2Fwaku%2F2%2Frs%2F0%2F0" -H "Content-Type: application/json" -d 'None'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'[{"payload":"TGlnaHQgcHVzaCB3b3JrcyEh","contentTopic":"/myapp/1/latest/proto","version":0,"timestamp":1713240893582428672,"ephemeral":false}]'
[35mDEBUG   [0m tests.conftest:conftest.py:51 Running fixture teardown: test_setup
[35mDEBUG   [0m tests.conftest:conftest.py:75 Running fixture teardown: close_open_nodes
[35mDEBUG   [0m src.node.waku_node:waku_node.py:168 Stopping container with id 5acb101dd5a5
[35mDEBUG   [0m src.node.waku_node:waku_node.py:171 Container stopped.
[35mDEBUG   [0m src.node.waku_node:waku_node.py:168 Stopping container with id 909fbe8fce49
[35mDEBUG   [0m src.node.waku_node:waku_node.py:171 Container stopped.
[35mDEBUG   [0m src.node.waku_node:waku_node.py:168 Stopping container with id d6f970cbe50a
[35mDEBUG   [0m src.node.waku_node:waku_node.py:171 Container stopped.